SET session_replication_role = replica;

--
-- PostgreSQL database dump
--

-- \restrict RnRttAkET0Gk6Q0okOJBJZnuKmpLR9AzwBPQlAkRPvsHUeIEXYCizQed8s7hUnf

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: data_tbl_feast; Type: TABLE DATA; Schema: data; Owner: -
--

INSERT INTO "data"."data_tbl_feast" ("id", "at", "aw", "inf", "na") VALUES
	(1, '0-23|0-6|1-1|0-0', 192, 'Việt Nam là một trong các nước trên thế giới sử dụng lịch công nguyên, lấy mùng 1 tháng 1 là mốc bắt đầu năm mới. Đây không phải là tết cổ truyền, tuy nhiên đây cũng là dịp để mọi người vui chơi, “xả hơi” sau những tháng ngày miệt mài lao động.', 'Tết Tây'),
	(2, '0-23|0-6|22-22|0-0', 724, 'Tết Táo quân vào ngày 23 tháng Chạp - người ta coi đây là ngày "vua bếp" lên chầu Trời để tâu lại việc bếp núc, làm ăn, cư xử của gia đình trong năm qua. cứ đến phiên chợ 23 tháng Chạp hàng năm, mỗi gia đình thường mua hai mũ ông, một mũ bà bằng giấy và 3 con cá làm "ngựa" (cá chép hóa rồng) để Táo quân lên chầu trời.', 'Tết Táo Quân'),
	(3, '0-23|0-6|28-28|0-0', 193, 'Trừ tịch là buổi tối cuối cùng trong năm theo lịch âm, trong thời gian này các hoạt động chủ yếu xoay quanh tiễn cũ đón mới, giải trừ hoạ hại, cầu phúc.', 'Trừ Tịch'),
	(4, '0-23|0-6|29-29|0-0', 1177, 'Một năm, người Việt có nhiều lễ, tết, riêng Tết Nguyên Ðán (đúng mồng một tháng giêng âm lịch) là ngày tết lớn nhất nên còn được gọi là tết cả. Ðây là thời điểm kết thúc mùa màng, mọi người rảnh rỗi nghỉ ngơi vui chơi, thăm viếng lẫn nhau... và cũng là lúc giao thời của đông tàn xuân tới. Chiều 30 tết, nhà nhà làm lễ cúng "rước" gia tiên và gia thần, thể hiện tình cảm uống nước nhớ nguồn', 'Tết Nguyên Đán'),
	(5, '0-23|0-6|14-14|1-1', 1313, 'Ngày 14 tháng 2 là ngày lễ truyền thống của phương tây. Nam nữ trong ngày này tặng kẹo socola, bưu thiếp và hoa thể hiện tình yêu và bạn bè; ngày nay trở thành ngày lễ được các bạn trẻ thanh niên các nước Âu Mỹ yêu thích. Trên thế giới này có bao nhiêu tình nhân thì có bấy nhiêu cách giải thích về ngày này. Ở Việt Nam cũng đón chào ngày này nồng nhiệt như Lễ giáng sinh vậy. Lễ tình nhân dần dần trở thành một trong những ngày lễ quan trọng ngoài truyền thống của Việt Nam.', 'Lễ Tình Nhân'),
	(6, '0-23|0-6|12-12|1-1', 196, 'Tết Nguyên Tiêu (Tết Thượng Nguyên) vào đúng rằm tháng Giêng - ngày trăng tròn đầu tiên của năm. Phong tục này bắt nguồn từ thời Tây Hán ở Trung Quốc, người ta còn tiến hành nghi thức rước đèn lồng rất đẹp mắt và long trọng, chính vì thế tết Nguyên Tiêu còn gọi là lễ hội lồng đèn. Vì ảnh hưởng tam giáo (Nho, Lão, Phật) cho nên người việt cũng có Lễ Thượng Nguyên, Trong 3 lễ, Thượng Nguyên, Trung Nguyên và Hạ nguyên đó trong dân gian có câu thành ngữ:"Rằm tháng giêng ai siêng thì quải,Rằm tháng bảy kẻ quải, người không.Rằm tháng mười, mười người mười quải."Ngày nay Rằm tháng giêng người Việt theo Phật giáo hay thờ cũng ông bà cũng đi lễ Phật vào rằm tháng giêng và trở thành một tập tục chung cho đông đảo quần chúng.', 'Tết Nguyên Tiêu'),
	(7, '0-23|0-6|8-8|2-2', 724, 'Tết phụ nữ còn gọi là ngày quốc tế phụ nữ, là ngày lễ phụ nữ các quốc gia trên thế giới đấu tranh bình đẳng, bình an, phát triển. Ngày lễ vào mùng 8 tháng 3. Một thế kỷ trở lại đây, phụ nữ các nước trên thế giới đã nỗ lực và đấu tranh không ngừng để đạt được quyền lợi này', 'Ngày QT Phụ Nữ'),
	(9, '0-23|0-6|26-26|2-2', 724, 'Cuối tháng 3 nǎm 1931, Trung ương Đảng Cộng sản Đông Dương đã triệu tập Hội nghị toàn thể lần thứ hai tại Sài Gòn, dưới sự chủ toạ của Tổng bí thư Trần Phú. Tại Hội nghị này, nhận thấy vai trò của lực lượng thanh niên trong sự nghiệp cách mạng nên đã đề ra quyết định "Cần kíp tổ chức ra Cộng sản thanh niên Đoàn" và chỉ thị cho các tổ chức Đảng ở các địa phương quan tâm đến việc xây dựng tổ chức Đoàn thanh niên. Đại hội toàn quốc lần thứ 3 họp từ ngày 22 - 25/3/1961 đã quyết định lấy ngày 26/3/1931  làm ngày thành lập Đoàn', 'Ngày Thành Lập Đoàn TNCS'),
	(10, '0-23|0-6|1-1|3-3', 195, 'Ngày Cá Tháng Tư có lịch sử không rõ ràng, mỗi nền văn hóa khác nhau lại có lịch sử và thời gian kỷ niệm Ngày Nói Dối khác nhau. Ngày Cá tháng Tư chỉ là một ngày vui. Đó không phải là một lễ hội để công chức được nghỉ làm và trẻ em không phải đến trường.', 'Cá Tháng Tư'),
	(11, '0-23|0-6|7-7|3-3', 1515, 'Ngày giỗ tổ Hùng Vương được tổ chức hàng năm vào ngày 10 tháng 3 (âm lịch) tại Đền Hùng, Việt Trì, Phú Thọ. Đây là ngày hội truyền thống của dân tộc nhằm mục đích tưởng nhớ đến công ơn các Vua Hùng đã có công dựng nước. Ngày này công nhận là một trong những ngày quốc lễ của Việt Nam thể hiện rõ đạo lý uống nước nhớ nguồn.', 'Giỗ Tổ Hùng Vương'),
	(12, '0-23|0-6|30-30|3-3', 724, 'Cuộc Tổng tiến công và nổi dậy Mùa Xuân 1975 đã toàn thắng. Sau 55 ngày đêm tiến công thần tốc, quân và dân ta đã quét sạch toàn bộ chế độ thực dân kiểu mới của đế quốc Mỹ ở miền Nam, giải phóng miền Nam thân yêu, giành lại độc lập hoàn toàn cho đất nước vào ngày 30/04/1975. ', 'Ngày Lễ 30/04'),
	(13, '0-23|0-6|1-1|4-4', 1447, 'Ngày Quốc tế Lao động hay ngày 1 tháng 5 là ngày lễ kỷ niệm của phong trào công nhân quốc tế. Vào các ngày 1 tháng 5, tại nhiều nước trên thế giới, đặc biệt tại Mỹ và Canada, thường có các cuộc biểu tình trên đường phố của hàng triệu người lao động và các tổ chức công đoàn của họ.', 'Quốc Tế Lao Động'),
	(15, '0-23|0-6|12-12|4-4', 724, 'Ngày 15 tháng 4 âm lịch hàng năm là ngày kỷ niệm Đức Phật ra đời. Theo Phật giáo Nam truyền và Phật giáo Tây Tạng thì ngày này là ngày Tam hiệp (Phật đản, Phật thành đạo và Phật nhập Niết-bàn). Trước năm 1959 các nước Đông Á, thường tổ chức ngày lễ Phật đản vào ngày mồng 8 tháng 4 âm lịch, nhưng đến năm 1950 tại Hội nghị Phật giáo thế giới tại Sri-lan-ca đã quyết nghị lấy ngày trăng tròn đầu mùa hạ (ngày 15 tháng 4 âm lịch) làm ngày kỷ niệm Phật đản chính thức.', 'Lễ Phật Đản'),
	(17, '0-23|0-6|19-19|4-4', 724, 'Chủ tịch Hồ Chí Minh sinh ngày 19/5/1890 ở xã Kim Liên, huyện Nam Đàn, tỉnh Nghệ An. Chủ tịch Hồ Chí Minh là lãnh tụ vĩ đại của dân tộc Việt Nam, Người đã vận dụng và phát triển sáng tạo chủ nghĩa Mác - Lênin vào điều kiện cụ thể của Việt Nam, sáng lập Đảng Mác - Lênin ở Việt Nam, sáng lập Mặt trận dân tộc thống nhất Việt Nam, sáng lập lực lượng vũ trang nhân dân Việt Nam và sáng lập nước Việt Nam Dân chủ Cộng hoà (nay là Cộng hoà Xã hội chủ nghĩa Việt Nam)', 'Ngày Sinh Bác Hồ'),
	(19, '0-23|0-6|1-1|5-5', 1517, 'Ngày quốc tế thiếu nhi, là ngày lễ bảo vệ quyền sinh tồn, sống khoẻ mạnh, quyền được giáo dục, cải thiện cuộc sống trẻ em toàn thế giới; phản đối ngược đãi và giết hại trẻ em. Đa số các nước trên thế giới đều lấy ngày 1.6 là ngày quốc tế thiếu nhi. Hiện tại chính phủ các nước đều rất quan tâm tương lai và bảo vệ quyền lợi của trẻ em.', 'Tết Thiếu Nhi'),
	(20, '0-23|0-6|5-5|5-5', 724, 'Ngày 5.6.1972 triệu tập cuộc họp "Hội nghị môi trường nhân loại Liên hợp quốc" tại thủ đô Stockholm-Thuỵ điển, hội nghị thông qua "Tuyên bố môi trường nhân loại", lấy ngày 5.6 hàng năm là ngày môi trường quốc tế. Tháng 10 cùng năm, đại hội thứ 27 liên hợp quốc thông qua nghị quyết đồng ý kiến nghị này. Xác lập ngày môi trường thế giới phản ánh nhận thức và thái độ của nhân loại với vấn đề môi trường, thể hiện ước mơ vươn tới môi trường hoàn mỹ của nhân loại', 'Ngày Môi Trường TG'),
	(21, '0-23|0-6|30-30|4-4', 1518, 'Tết đoan ngọ hay còn gọi là Tết Đoan Dương. Theo âm lịch thì ngày 5 tháng 5 là ngày hết Xuân sang Hạ, đây là khi thời tiết chuyển mùa nên hay có bệnh thời khí ở con người. 5/5 là ngày cực dương hoặc gần với cực dương, con người cũng như mọi vật cần dự trữ năng lượng để chống lại dương khí quá cao của trời đất. Họ cần ăn một số hoa quả hay thực phẩm giàu năng lượng như trứng luộc, cái rượu, cháo chè kê, bánh đa, uống rượu xương bồ ...', 'Tết Đoan Ngọ'),
	(23, '0-23|0-6|29-29|7-7', 197, 'Ngày Thất Tịch theo văn hóa phương Đông (Việt Nam và các nước lân cận) là ngày lễ tình yêu của phương đông được tổ chức vào ngày 7 tháng 7 Âm lịch. Lịch sử về ngày này gắn bó với câu chuyện về Ngưu Lang Chức Nữ hoặc vợ chồng Ngâu với nhiều dị bản.', 'Lễ Thất Tịch'),
	(24, '0-23|0-6|6-6|8-8', 2545, 'Còn được gọi là Lễ Vua Lan (lễ báo hiếu) được tổ chức ngày 15 tháng 7 âm lịch để tỏ hiếu với cha mẹ, ông bà và cũng để giúp đỡ những linh hồn đói khát. Bởi vậy đến ngày này mọi gia đình đều làm cỗ bàn, đốt vàng mã cúng gia tiên và đồng thời cúng những linh hồn bơ vơ không được ai chăm sóc. Người ta cũng thả chim lên trời, thả cá xuống sông, để làm điều phúc đức.', 'Tết Trung Nguyên'),
	(25, '0-23|0-6|2-2|8-8', 198, 'Với sự lãnh đạo tài tình của Hồ Chí Minh, Tổng khởi nghĩa mùa thu Tháng Tám 1945 đã giành thắng lợi vang dội, xóa bỏ ách thống trị của phong kiến, thực dân; quyền làm chủ đất nước lần đầu tiên được trao về tay nhân dân lao động. Ngày 2-9-1945, trên lễ đài lớn tại quảng trường Ba Đình lịch sử, trước cuộc mít-tinh của đông đảo nhân dân, bao gồm hàng trăm ngàn đồng bào Hà Nội và cả nước đổ về tụ hội, Chủ tịch Hồ Chí Minh thay mặt Chính phủ Lâm thời đã trang trọng đọc bản Tuyên ngôn độc lập bất hủ, tuyên bố với quốc dân đồng bào cả nước và toàn thể nhân loại trên thế giới, bắt đầu từ nay, nước Việt Nam Dân chủ Cộng hòa đã ra đời.', 'Quốc Khánh'),
	(26, '0-23|0-6|6-6|9-9', 199, 'Tết Trung Thu theo Âm lịch là ngày rằm tháng 8, vào giữa mùa thu. Đây là ngày tết của trẻ em, còn được gọi là "Tết Trông Trăng". Trẻ em được người lớn tặng đồ chơi, thường là đèn ông sao, mặt nạ, đèn kéo quân, súng phun nước... rồi bánh nướng, bánh dẻo. Vào ngày tết này, người ta làm cỗ cúng gia tiên và bày bánh trái ra sân cúng mặt trăng. Người lớn thì uống rượu, thưởng trăng, và hát trống quân; trẻ em thì rước đèn, đi xem múa lân, ca hát các bài hát Trung Thu, và vui hưởng bánh kẹo cùng các thứ trái cây do cha mẹ bày ở ngoài sân trong đêm Trung Thu dưới hình thức một mâm cỗ.', 'Tết Trung Thu'),
	(27, '0-23|0-6|29-29|9-9', 724, 'Ngày 9 tháng 9 âm lịch là Tết Trùng Dương, tết này có nguồn gốc từ Trung quốc, ra đời vào thời kỳ thịnh hành của Đạo lão. Chuyện xưa kể rằng có người tên Hoàn Cảnh muốn học phép tiên, học mãi, đến ngày cuối cùng thầy bảo hãy may mỗi người một cái túi, hái hoa cúc bỏ vào rồi lên núi ẩn náu. Quả nhiên hôm ấy mùng 9 tháng 9 mưa to ngập hết cả mặt đất, người chết đuối rất nhiều, chỉ có gia đình Hoàn Cảnh là nguyên vẹn. Thời kỳ Lý - Trần, nho sĩ Việt Nam theo tích đó cũng tổ chức leo núi, uống rượu hoa cúc gọi là thưởng Tết Trùng Dương. Bây giời ít có nơi tổ chức Tết Trùng Dương', 'Tết Trùng Dương'),
	(28, '0-23|0-6|20-20|9-9', 724, 'Ngày 20/10/1930 Hội Phụ Nữ phản đế Việt Nam đã được thành lập. Đó là tổ chức tiền thân của Hội Liên Hiệp Phụ Nữ Việt Nam. Từ khi ra đời, Hội liên hiệp Phụ nữ Việt Nam đã tập hợp rộng rãi các tầng lớp phụ nữ, đấu tranh giải phóng dân tộc, giải phóng giai cấp và giải phóng phụ nữ theo đường lối của Đảng. Ngày 20/10 hàng năm được chọn là Ngày Phụ Nữ Việt Nam, đó là sự ghi nhận của đất nước với những con người được Bác Hồ tặng 8 chữ vàng: "Cần cù, Bất khuất, Trung hậu, Đảm đang".', 'Ngày Phụ Nữ VN'),
	(29, '0-23|0-6|31-31|9-9', 2545, 'Ngày 31.10 là ngày lễ quỷ _Haloween truyền thống của phương Tây. Ngày 31.10 được gọi là đêm giao thừa của Haloween, tuy nhiên các hoạt động chúc mừng không khiến người ta thấy nổi da gà như tên gọi của nó. Ngày này, trẻ em thường sốt ruột mặc quần áo hoá trang sặc sỡ, theo ánh đèn bí ngô Jack đi đến gõ cửa từng nhà đòi quà.', 'Ngày Haloween'),
	(30, '0-23|0-6|4-4|11-11', 724, 'Tết Hạ nguyên (Tết Cơm mới) vào Rằm tháng Mười âm lịch. Ở nông thôn, Tết này được tổ chức rất lớn vì đây là dịp nấu cơm gạo mới - trước để cúng tổ tiên, sau để tự thưởng công cày cấy.', 'Tết Hạ Nguyên'),
	(31, '0-23|0-6|20-20|10-10', 1515, 'Khi Việt Nam thống nhất, ngày "Quốc tế hiến chương các nhà giáo" đã trở thành ngày truyền thống của ngành giáo dục Việt Nam. Vào ngày 28 tháng 9 năm 1982, Hội đồng Bộ trưởng (nay là Chính phủ) đã ban hành quyết định số 167-HĐBT thiết lập ngày 20 tháng 11 hằng năm là ngày lễ mang tên "Ngày nhà giáo Việt Nam"', 'Ngày Nhà Giáo VN'),
	(32, '0-23|0-6|27-27|10-10', 724, 'Lễ Tạ Ơn là ngày lễ của Mỹ và Canada, trước đây là để cảm ơn người Indian, sau đó dùng ngày ngày để cảm ơn người khác. Ở Mỹ, từ năm 1941 lễ cảm ơn là ngày thứ 5 cuối cùng trong tháng 11, toàn quốc nghỉ 2 ngày. Có hàng nghìn người dù bận trăm công nghìn việc vẫn về đoàn tụ với gia đình vào ngày này. Lễ Tạ Ơn là ngày lễ lâu đời của nhân dân Mỹ, cũng là ngày sum vầy tụ họp của cả gia đình, vì thế người Mỹ khi nhắc đến ngày này vô cùng xúc động.', 'Ngày Lễ Tạ Ơn'),
	(33, '0-23|0-6|22-22|11-11', 724, 'Quân đội Nhân dân Việt Nam, tiền thân là đội Việt Nam Tuyên truyền Giải phóng quân, là lực lượng quân đội chính quy của chính phủ Việt Nam Dân chủ Cộng hòa, sau này là của Cộng hòa Xã hội Chủ nghĩa Việt Nam. Ngày truyền thống là ngày 22 tháng 12 năm 1944. Tên gọi "Quân đội Nhân dân" là do Chủ tịch Hồ Chí Minh đặt với ý nghĩa "từ nhân dân mà ra, vì nhân dân mà chiến đấu, vì nhân dân phục vụ".', 'Ngày Thành Lập QĐNDVN'),
	(35, '0-23|0-6|25-25|11-11', 200, 'Ngày 25.12 hàng năm là ngày kỷ niệm chúa Jesus đạo thiên chúa giáng sinh, còn gọi là lễ giáng sinh. Trong thời gian lễ hội các giáo đồ thiên chúa tại các nước tổ chức kỷ niệm rất long trọng. Lễ giáng sinh vốn chỉ là ngày lễ của tín đồ đạo thiên chúa, nhưng do người dân hết sức coi trọng nên dần trở thành ngày lễ có tính toàn dân.', 'Lễ Giáng Sinh'),
	(18, '0-23|0-6|31-31|4-4', 1037, 'Bắt nguồn từ thập kỷ 50 của thế kỷ 20, các nghiên cứu bệnh truyền nhiễm toàn cầu đã chứng minh hút thuốc là nhân tố nguy hiểm hàng đầu gây ra ung thư. Nhằm thu hút sự chú ý của xã hội quốc tế về ảnh hưởng của thuốc lá với sức khoẻ nhân loại, tháng 11.1987 tổ chức y tế thế giới đề nghị lấy ngày 7.4 hàng năm là ngày "quốc tế không hút thuốc lá", bắt đầu thực hiện từ 1988. Từ 1988 ngày quốc tế không hút thuốc lá chuyển thành ngày 31.5', 'Ngày Không Hút Thuốc'),
	(14, '0-23|0-6|11-11|4-4', 724, 'Ngày chủ nhật thứ hai của tháng 5 là ngày Lễ các bà mẹ, có rất nhiều người muốn bày tỏ tấm lòng của mình đối với mẹ. Họ hy vọng những món quà nhỏ bé sẽ phần nào vợ đi những nhọc nhằn trong cuộc sống của mẹ. Hầu hết mọi người đều dành cho mẹ tình cảm tốt đẹp nhất.', 'Ngày Của Mẹ'),
	(22, '0-23|0-6|15-15|5-5', 724, 'Ngày chủ nhật thứ 3 trong tháng 6 là ngày lễ các ông bố, so với lễ bà mẹ, ngày lễ các ông bố tương đối xa lạ, do quý bà Dodd ở thành phố Spokane bang Washington (mỹ) đưa ra. Trong ngày này khi suy nghĩ nên tặng quà gì cho các ông bố, chúng ta nên tự hỏi bản thân mình có yêu quý cha mình như ông đã yêu quý, hy sinh vô tư cho chúng ta hay không.', 'Ngày Của Cha');


--
-- PostgreSQL database dump complete
--

-- \unrestrict RnRttAkET0Gk6Q0okOJBJZnuKmpLR9AzwBPQlAkRPvsHUeIEXYCizQed8s7hUnf


SET session_replication_role = origin;
