// Open-sourced by BaoLT

// Battle command processing and turn submission handlers.
package combat

import (
	"context"
	"fmt"
	"strconv"

	combatdomain "mcgame-server/internal/domain/combat"
	"mcgame-server/internal/infrastructure/rtmp"
	pkgerrors "mcgame-server/pkg/errors"

	amf0 "github.com/yutopp/go-amf0"
	"go.uber.org/zap"
)

type skillOwnershipChecker interface {
	HasSkill(ctx context.Context, charID int64, skillID int) (bool, error)
}

func parseOwnerCharID(actorID string, characterID int64) (int64, bool) {
	parsed, err := strconv.ParseInt(actorID, 10, 64)
	if err != nil || parsed != characterID {
		return 0, false
	}
	return parsed, true
}

func (h *Handler) BattleUpdateCmd(ctx *rtmp.RPCContext, args []interface{}) (interface{}, error) {
	characterID, err := strconv.ParseInt(ctx.CharacterID, 10, 64)
	if err != nil {
		return nil, pkgerrors.ErrUnauthorized
	}

	battle, err := h.combatService.GetPlayerBattle(characterID)
	if err != nil {
		return rtmp.ErrorToResponse(err), nil
	}

	if !battle.IsActive() {
		return map[string]interface{}{
			"success": false,
			"error":   "Battle is not active",
		}, nil
	}

	cmdArray, hasCommandPayload, err := extractBattleUpdateCmdArray(args)
	if err != nil {
		if len(args) > 0 {
			h.logger.Warn("BattleUpdateCmd received unexpected argument type",
				zap.String("type", fmt.Sprintf("%T", args[0])),
				zap.Any("value", args[0]))
		}
		return nil, err
	}

	h.logger.Info("BattleUpdateCmd entry",
		zap.String("battle_id", battle.ID),
		zap.Int64("character_id", characterID),
		zap.Int("round", battle.CurrentRound),
		zap.Bool("has_payload", hasCommandPayload),
		zap.Bool("has_pending", battle.HasPendingCommands()),
		zap.Int("arg_count", len(args)),
		zap.Any("raw_args", args))

	for _, p := range battle.Participants {
		if p.EntityType == combatdomain.ParticipantTypePet {
			h.logger.Info("BattleUpdateCmd pet participant detail",
				zap.String("participant_id", p.ID),
				zap.Int64("entity_id", p.EntityID),
				zap.Int("entity_type", int(p.EntityType)),
				zap.Int("position", p.Position),
				zap.Bool("is_alive", p.IsAlive),
				zap.Int64("owner_id", p.OwnerID))
		}
	}

	var commands []*combatdomain.BattleCommand

	if !hasCommandPayload {
		switch {
		case battle.HasPendingCommands():
			h.logger.Info("BattleUpdateCmd received empty ping, processing with pending commands",
				zap.String("battle_id", battle.ID),
				zap.Int64("character_id", characterID),
				zap.Int("round", battle.CurrentRound))
		case shouldAutoDefendEmptyPing(battle):
			commands = autoGenerateDefendCommands(battle)
			battle.BootstrapAutoDefendFired = true
			h.logger.Info("BattleUpdateCmd null-payload auto-action",
				zap.String("battle_id", battle.ID),
				zap.Int("round", battle.CurrentRound),
				zap.Int("command_count", len(commands)))
		default:
			h.logger.Warn("BattleUpdateCmd ignoring stale empty ping",
				zap.String("battle_id", battle.ID),
				zap.Int64("character_id", characterID),
				zap.Int("round", battle.CurrentRound),
				zap.Bool("bootstrap_fired", battle.BootstrapAutoDefendFired),
				zap.String("reason", "stale_empty_ping"))
			return waitingBattleUpdateResponse(battle, battle.MissingPlayerCommandActors(battle.GetPendingCommands())), nil
		}
	} else {
		commands = h.parseCommands(ctx.Context, cmdArray, characterID, battle)
	}

	participantIDs := make([]string, len(battle.Participants))
	for index, participant := range battle.Participants {
		participantIDs[index] = participant.ID
	}

	if len(commands) > 0 {
		h.logger.Info("BattleUpdateCmd participants",
			zap.String("battle_id", battle.ID),
			zap.Strings("participant_ids", participantIDs),
			zap.Int("command_count", len(commands)))
	} else {
		h.logger.Info("BattleUpdateCmd payload produced no parsed commands",
			zap.String("battle_id", battle.ID),
			zap.Bool("has_pending_commands", battle.HasPendingCommands()),
			zap.Int("arg_count", len(args)))
	}

	pendingCommands := mergeBattleCommands(battle.GetPendingCommands(), commands)
	if len(pendingCommands) > 0 {
		for _, command := range pendingCommands {
			h.logger.Info("BattleUpdateCmd command",
				zap.String("actor_id", command.ActorID),
				zap.String("target_id", command.TargetID),
				zap.Int("action_type", command.ActionType))
		}
	}

	battle.SetPendingCommands(pendingCommands)

	missingActorIDs := battle.MissingPlayerCommandActors(pendingCommands)
	if len(missingActorIDs) > 0 {
		h.logger.Info("BattleUpdateCmd waiting for remaining player commands",
			zap.String("battle_id", battle.ID),
			zap.Strings("missing_actor_ids", missingActorIDs),
			zap.Int("pending_command_count", len(pendingCommands)))
		return waitingBattleUpdateResponse(battle, missingActorIDs), nil
	}

	if h.battleService != nil {
		h.battleService.ClearBattleDeadlines(battle.ID)
	}

	processor := combatdomain.NewTurnProcessor(battle, h.skillAdapter)
	if h.itemService != nil {
		processor.SetItemHandler(newBattleItemHandler(ctx.Context, characterID, h.itemService, h.gameData, h.logger))
	}
	if h.combatService != nil {
		if catchHandler := h.combatService.GetCatchHandler(); catchHandler != nil {
			processor.SetCatchHandler(catchHandler)
		}
	}
	pendingCmds := battle.GetPendingCommands()
	for _, command := range pendingCmds {
		processor.SetCommand(command)
	}

	battle.ClearPendingCommands()

	result := processor.ProcessRound()
	if len(result.PetStateOwners) > 0 && h.combatService != nil {
		stateChanges, err := h.combatService.SyncBattlePetStates(ctx.Context, battle, result.PetStateOwners)
		if err != nil {
			h.logger.Error("Failed to sync battle pet states",
				zap.String("battle_id", battle.ID),
				zap.Int64s("owner_ids", result.PetStateOwners),
				zap.Error(err))
		} else {
			for _, ownerID := range result.PetStateOwners {
				if h.rtmpServer == nil {
					break
				}
				ownerKey := strconv.FormatInt(ownerID, 10)
				conn := h.rtmpServer.GetConnectionByCharacterID(ownerKey)
				sendBattlePetStateCallbacks(conn, ownerKey, stateChanges, h.logger)
			}
		}
	}

	playbackRounds := combatdomain.BuildPlaybackRounds(result.Actions)
	actionDTOs := combatdomain.FlattenPlaybackRounds(playbackRounds)

	if result.BattleEnded {
		if battle.Result == nil {
			h.combatService.EndBattle(ctx.Context, battle, result.Winner)
		}
		battleResult := 0
		if result.PlayerFled {
			battleResult = 2
		} else if result.Winner == combatdomain.SidePlayer {
			battleResult = 1
		}
		endAction := map[string]interface{}{
			"end":    true,
			"type":   0,
			"result": battleResult,
		}
		actionDTOs = append(actionDTOs, endAction)
		playbackRounds = append(playbackRounds, []map[string]interface{}{endAction})
		h.logger.Info("Battle ended, added end marker", zap.Int("winner", int(result.Winner)), zap.Bool("player_fled", result.PlayerFled), zap.Int("result", battleResult))
		battle.SetRoundComplete()
		h.sendBattleEndCallbacks(battle)
	}

	cList := make(map[string]interface{}, len(battle.Participants))
	for _, participant := range battle.Participants {
		cList[fmt.Sprintf("%d", participant.Position)] = participant.ToDTO()
	}

	response := map[string]interface{}{
		"success":  true,
		"battleId": battle.ID,
		"round":    result.Round,
		"actions":  actionDTOs,
		"cList":    cList,
	}

	if result.BattleEnded {
		response["battleEnded"] = true
	}

	if result.MoreTurns && !result.BattleEnded {
		response["moreTurns"] = true
		h.logger.Info("More turns remaining in round", zap.Int("round", result.Round))
	}

	for index, actionDTO := range actionDTOs {
		h.logger.Info("Action DTO",
			zap.Int("index", index),
			zap.Any("sid", actionDTO["sid"]),
			zap.Any("tid", actionDTO["tid"]),
			zap.Any("bid", actionDTO["bid"]),
			zap.Any("sSObj", actionDTO["sSObj"]),
			zap.Any("tSObj", actionDTO["tSObj"]),
			zap.Any("delay", actionDTO["delay"]),
			zap.Any("end", actionDTO["end"]))
	}

	nestedActions := make([]interface{}, 0, len(playbackRounds))
	for _, round := range playbackRounds {
		nestedActions = append(nestedActions, round)
	}
	h.logger.Info("Action sequence created", zap.Int("total_actions", len(nestedActions)))

	if !result.BattleEnded {
		h.sendCmdReadyToParticipants(battle)
	}
	battle.BroadcastToWatchers("onBattlePlayList", nestedActions)
	h.logger.Info("Sent onBattlePlayList callback", zap.Int("steps", len(actionDTOs)))

	if !result.BattleEnded && !result.MoreTurns && h.battleService != nil {
		h.setBattleRoundDeadlines(battle)
		h.battleService.OnRoundProcessed()
	}

	h.logger.Debug("Battle round processed",
		zap.String("battle_id", battle.ID),
		zap.Int64("character_id", characterID),
		zap.Int("round", result.Round),
		zap.Int("actions", len(result.Actions)),
		zap.Bool("more_turns", result.MoreTurns))

	return response, nil
}

func (h *Handler) parseCommands(ctx context.Context, cmdArray []interface{}, characterID int64, battle *combatdomain.Battle) []*combatdomain.BattleCommand {
	commands := make([]*combatdomain.BattleCommand, 0, len(cmdArray))

	var petActorID string
	for _, p := range battle.Participants {
		if p.EntityType == combatdomain.ParticipantTypePet && p.OwnerID == characterID {
			petActorID = p.ID
			break
		}
	}

	for index, item := range cmdArray {
		var cmdMap map[string]interface{}
		switch v := item.(type) {
		case map[string]interface{}:
			cmdMap = v
		case amf0.ECMAArray:
			cmdMap = map[string]interface{}(v)
		default:
			h.logger.Debug("parseCommands skipping non-map item", zap.Int("index", index), zap.String("type", fmt.Sprintf("%T", item)))
			continue
		}

		command := &combatdomain.BattleCommand{}
		if index == 0 {
			command.ActorID = fmt.Sprintf("%d", characterID)
		} else {
			command.ActorID = petActorID
		}

		if tid, ok := cmdMap["tid"]; ok {
			command.TargetID = h.parseTargetID(tid)
		}

		if action, ok := cmdMap["action"]; ok {
			switch v := action.(type) {
			case float64:
				command.ActionType = int(v)
			case int:
				command.ActionType = v
			}
		}

		if id, ok := cmdMap["id"]; ok {
			switch v := id.(type) {
			case float64:
				command.SkillID = int(v)
				command.ItemSlot = int(v)
				command.SelectedPetID = int64(v)
			case int:
				command.SkillID = v
				command.ItemSlot = v
				command.SelectedPetID = int64(v)
			}
		}

		if level, ok := cmdMap["level"]; ok {
			switch v := level.(type) {
			case float64:
				command.SkillLevel = int(v)
			case int:
				command.SkillLevel = v
			}
		}

		h.logger.Debug("Parsed battle command",
			zap.String("actor_id", command.ActorID),
			zap.String("target_id", command.TargetID),
			zap.Int("action_type", command.ActionType),
			zap.Int("skill_id", command.SkillID),
			zap.Int("skill_level", command.SkillLevel))

		if command.ActionType == combatdomain.ClientActionPet && command.SelectedPetID > 0 && h.combatService != nil {
			petPosition := 15
			if currentPet := battle.GetOwnerPet(characterID); currentPet != nil {
				petPosition = currentPet.Position
			} else if actor := battle.GetParticipant(command.ActorID); actor != nil && actor.Position >= 10 && actor.Position <= 14 {
				petPosition = actor.Position + 5
			}
			replacementPet, resolveErr := h.combatService.ResolveBattlePetSelection(ctx, characterID, command.SelectedPetID, petPosition)
			if resolveErr != nil {
				h.logger.Warn("Rejected pet switch command",
					zap.Int64("character_id", characterID),
					zap.Int64("pet_id", command.SelectedPetID),
					zap.Error(resolveErr))
			} else {
				command.ReplacementPet = replacementPet
			}
		}

		if command.ActionType == combatdomain.ClientActionSkill && command.SkillID > 0 && h.skillOwnership != nil {
			if actorID, ok := parseOwnerCharID(command.ActorID, characterID); ok {
				hasSkill, err := h.skillOwnership.HasSkill(ctx, actorID, command.SkillID)
				if err != nil {
					h.logger.Warn("HasSkill ownership check failed",
						zap.Int64("character_id", actorID),
						zap.Int("skill_id", command.SkillID),
						zap.Error(err))
					continue
				}
				if !hasSkill {
					h.logger.Warn("Rejected skill command: player does not know skill",
						zap.Int64("character_id", actorID),
						zap.Int("skill_id", command.SkillID))
					continue
				}
			}
		}

		commands = append(commands, command)
	}

	return commands
}

func extractBattleUpdateCmdArray(args []interface{}) ([]interface{}, bool, error) {
	if len(args) < 1 {
		return nil, false, nil
	}

	switch v := args[0].(type) {
	case []interface{}:
		return v, len(v) > 0, nil
	case amf0.ECMAArray:
		return indexedBattleUpdateCmdArray(map[string]interface{}(v)), len(v) > 0, nil
	case map[string]interface{}:
		return indexedBattleUpdateCmdArray(v), len(v) > 0, nil
	case nil:
		return nil, false, nil
	default:
		return nil, false, pkgerrors.ErrInvalidArgs
	}
}

func indexedBattleUpdateCmdArray(values map[string]interface{}) []interface{} {
	maxIdx := 0
	for key := range values {
		if idx, err := strconv.Atoi(key); err == nil && idx >= maxIdx {
			maxIdx = idx + 1
		}
	}

	cmdArray := make([]interface{}, maxIdx)
	for key, val := range values {
		if idx, err := strconv.Atoi(key); err == nil && idx >= 0 && idx < len(cmdArray) {
			cmdArray[idx] = val
		}
	}

	return cmdArray
}

func waitingBattleUpdateResponse(battle *combatdomain.Battle, missingActorIDs []string) map[string]interface{} {
	response := map[string]interface{}{
		"success":            true,
		"battleId":           battle.ID,
		"round":              battle.CurrentRound,
		"waitingForCommands": true,
	}

	if len(missingActorIDs) > 0 {
		response["missingActorIds"] = missingActorIDs
	}

	return response
}

func mergeBattleCommands(existing map[string]*combatdomain.BattleCommand, incoming []*combatdomain.BattleCommand) map[string]*combatdomain.BattleCommand {
	merged := make(map[string]*combatdomain.BattleCommand, len(existing)+len(incoming))
	for actorID, command := range existing {
		merged[actorID] = command
	}

	for _, command := range incoming {
		merged[command.ActorID] = command
	}

	return merged
}

func shouldAutoDefendEmptyPing(battle *combatdomain.Battle) bool {
	if battle == nil {
		return false
	}
	if battle.CurrentRound == 1 && !battle.BootstrapAutoDefendFired {
		return true
	}
	if battle.HasPendingCommands() {
		return false
	}
	for _, p := range battle.Participants {
		if p.Side == combatdomain.SidePlayer && p.IsAlive {
			return true
		}
	}
	return false
}

func autoGenerateDefendCommands(battle *combatdomain.Battle) []*combatdomain.BattleCommand {
	target := combatdomain.SelectFrontlineTarget(battle, combatdomain.SideEnemy)
	if target == nil {
		target = combatdomain.SelectRandomTarget(battle, combatdomain.SideEnemy)
	}

	if target == nil {
		for _, p := range battle.Participants {
			if p.Side == combatdomain.SideEnemy && p.IsAlive {
				target = p
				break
			}
		}
	}

	commands := make([]*combatdomain.BattleCommand, 0)
	for _, p := range battle.Participants {
		if p.Side != combatdomain.SidePlayer || !p.IsAlive {
			continue
		}
		if target != nil {
			commands = append(commands, &combatdomain.BattleCommand{
				ActorID:    p.ID,
				TargetID:   target.ID,
				ActionType: combatdomain.ClientActionAttack,
			})
			continue
		}
		commands = append(commands, &combatdomain.BattleCommand{
			ActorID:    p.ID,
			ActionType: combatdomain.ClientActionDefend,
		})
	}
	return commands
}

func (h *Handler) parseTargetID(tid interface{}) string {
	switch v := tid.(type) {
	case string:
		return v
	case float64:
		return fmt.Sprintf("%d", int(v))
	case int:
		return fmt.Sprintf("%d", v)
	default:
		return ""
	}
}
