// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: api/proto/lineserver/v1/lineserver.proto

package lineserverv1

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// LineServerServiceClient is the client API for LineServerService service.
type LineServerServiceClient interface {
	// Register registers a new line server with the main server.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Deregister removes a line server from the registry.
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error)
	// Heartbeat sends periodic status updates using bidirectional streaming.
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (LineServerService_HeartbeatClient, error)
	// GetRegistry returns all registered line servers.
	GetRegistry(ctx context.Context, in *GetRegistryRequest, opts ...grpc.CallOption) (*GetRegistryResponse, error)
}

type lineServerServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewLineServerServiceClient creates a new LineServerServiceClient.
func NewLineServerServiceClient(cc grpc.ClientConnInterface) LineServerServiceClient {
	return &lineServerServiceClient{cc}
}

func (c *lineServerServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/lineserver.v1.LineServerService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lineServerServiceClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*DeregisterResponse, error) {
	out := new(DeregisterResponse)
	err := c.cc.Invoke(ctx, "/lineserver.v1.LineServerService/Deregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lineServerServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (LineServerService_HeartbeatClient, error) {
	stream, err := c.cc.NewStream(ctx, &LineServerService_ServiceDesc.Streams[0], "/lineserver.v1.LineServerService/Heartbeat", opts...)
	if err != nil {
		return nil, err
	}
	x := &lineServerServiceHeartbeatClient{stream}
	return x, nil
}

// LineServerService_HeartbeatClient is the client streaming interface.
type LineServerService_HeartbeatClient interface {
	Send(*HeartbeatRequest) error
	Recv() (*HeartbeatResponse, error)
	grpc.ClientStream
}

type lineServerServiceHeartbeatClient struct {
	grpc.ClientStream
}

func (x *lineServerServiceHeartbeatClient) Send(m *HeartbeatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *lineServerServiceHeartbeatClient) Recv() (*HeartbeatResponse, error) {
	m := new(HeartbeatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lineServerServiceClient) GetRegistry(ctx context.Context, in *GetRegistryRequest, opts ...grpc.CallOption) (*GetRegistryResponse, error) {
	out := new(GetRegistryResponse)
	err := c.cc.Invoke(ctx, "/lineserver.v1.LineServerService/GetRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LineServerServiceServer is the server API for LineServerService service.
type LineServerServiceServer interface {
	// Register registers a new line server with the main server.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Deregister removes a line server from the registry.
	Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error)
	// Heartbeat sends periodic status updates using bidirectional streaming.
	Heartbeat(LineServerService_HeartbeatServer) error
	// GetRegistry returns all registered line servers.
	GetRegistry(context.Context, *GetRegistryRequest) (*GetRegistryResponse, error)
	mustEmbedUnimplementedLineServerServiceServer()
}

// UnimplementedLineServerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLineServerServiceServer struct{}

func (UnimplementedLineServerServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func (UnimplementedLineServerServiceServer) Deregister(context.Context, *DeregisterRequest) (*DeregisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deregister not implemented")
}

func (UnimplementedLineServerServiceServer) Heartbeat(LineServerService_HeartbeatServer) error {
	return status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}

func (UnimplementedLineServerServiceServer) GetRegistry(context.Context, *GetRegistryRequest) (*GetRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegistry not implemented")
}

func (UnimplementedLineServerServiceServer) mustEmbedUnimplementedLineServerServiceServer() {}

// UnsafeLineServerServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeLineServerServiceServer interface {
	mustEmbedUnimplementedLineServerServiceServer()
}

// LineServerService_HeartbeatServer is the server streaming interface.
type LineServerService_HeartbeatServer interface {
	Send(*HeartbeatResponse) error
	Recv() (*HeartbeatRequest, error)
	grpc.ServerStream
}

type lineServerServiceHeartbeatServer struct {
	grpc.ServerStream
}

func (x *lineServerServiceHeartbeatServer) Send(m *HeartbeatResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *lineServerServiceHeartbeatServer) Recv() (*HeartbeatRequest, error) {
	m := new(HeartbeatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RegisterLineServerServiceServer registers a LineServerServiceServer.
func RegisterLineServerServiceServer(s grpc.ServiceRegistrar, srv LineServerServiceServer) {
	s.RegisterService(&LineServerService_ServiceDesc, srv)
}

func _LineServerService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LineServerServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lineserver.v1.LineServerService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LineServerServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LineServerService_Deregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LineServerServiceServer).Deregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lineserver.v1.LineServerService/Deregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LineServerServiceServer).Deregister(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LineServerService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LineServerServiceServer).Heartbeat(&lineServerServiceHeartbeatServer{stream})
}

func _LineServerService_GetRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LineServerServiceServer).GetRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lineserver.v1.LineServerService/GetRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LineServerServiceServer).GetRegistry(ctx, req.(*GetRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LineServerService_ServiceDesc is the grpc.ServiceDesc for LineServerService service.
var LineServerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lineserver.v1.LineServerService",
	HandlerType: (*LineServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _LineServerService_Register_Handler,
		},
		{
			MethodName: "Deregister",
			Handler:    _LineServerService_Deregister_Handler,
		},
		{
			MethodName: "GetRegistry",
			Handler:    _LineServerService_GetRegistry_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _LineServerService_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/lineserver/v1/lineserver.proto",
}
