// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/lineserver/v1/lineserver.proto

package lineserverv1

import (
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

// ServerStatus represents line server availability.
type ServerStatus int32

const (
	ServerStatus_SERVER_STATUS_UNSPECIFIED ServerStatus = 0
	ServerStatus_SERVER_STATUS_ONLINE      ServerStatus = 10
	ServerStatus_SERVER_STATUS_OFFLINE     ServerStatus = 20
	ServerStatus_SERVER_STATUS_FULL        ServerStatus = 30
	ServerStatus_SERVER_STATUS_UNKNOWN     ServerStatus = 40
)

// RegisterRequest contains line server registration information.
type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId       string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName     string `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	PublicUrl      string `protobuf:"bytes,3,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	InternalAddr   string `protobuf:"bytes,4,opt,name=internal_addr,json=internalAddr,proto3" json:"internal_addr,omitempty"`
	MaxClients     int32  `protobuf:"varint,5,opt,name=max_clients,json=maxClients,proto3" json:"max_clients,omitempty"`
	AuctionEnabled bool   `protobuf:"varint,6,opt,name=auction_enabled,json=auctionEnabled,proto3" json:"auction_enabled,omitempty"`
	GuildEnabled   bool   `protobuf:"varint,7,opt,name=guild_enabled,json=guildEnabled,proto3" json:"guild_enabled,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *RegisterRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RegisterRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *RegisterRequest) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *RegisterRequest) GetInternalAddr() string {
	if x != nil {
		return x.InternalAddr
	}
	return ""
}

func (x *RegisterRequest) GetMaxClients() int32 {
	if x != nil {
		return x.MaxClients
	}
	return 0
}

func (x *RegisterRequest) GetAuctionEnabled() bool {
	if x != nil {
		return x.AuctionEnabled
	}
	return false
}

func (x *RegisterRequest) GetGuildEnabled() bool {
	if x != nil {
		return x.GuildEnabled
	}
	return false
}

// RegisterResponse contains the registration result.
type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success             bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message             string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HeartbeatIntervalMs int64  `protobuf:"varint,3,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

// DeregisterRequest contains the server ID to remove.
type DeregisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *DeregisterRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// DeregisterResponse contains the deregistration result.
type DeregisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *DeregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// HeartbeatRequest contains periodic status update from line server.
type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId    string       `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	CurrentLoad int32        `protobuf:"varint,2,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"`
	Status      ServerStatus `protobuf:"varint,3,opt,name=status,proto3,enum=lineserver.v1.ServerStatus" json:"status,omitempty"`
	Timestamp   int64        `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *HeartbeatRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentLoad() int32 {
	if x != nil {
		return x.CurrentLoad
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() ServerStatus {
	if x != nil {
		return x.Status
	}
	return ServerStatus_SERVER_STATUS_UNSPECIFIED
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HeartbeatResponse contains acknowledgment from main server.
type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acknowledged bool  `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ServerTime   int64 `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// GetRegistryRequest is empty - returns all servers.
type GetRegistryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRegistryRequest) Reset() {
	*x = GetRegistryRequest{}
}

func (x *GetRegistryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistryRequest) ProtoMessage() {}

func (x *GetRegistryRequest) ProtoReflect() protoreflect.Message {
	return nil
}

// GetRegistryResponse contains the list of registered line servers.
type GetRegistryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servers []*LineServerInfo `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
}

func (x *GetRegistryResponse) Reset() {
	*x = GetRegistryResponse{}
}

func (x *GetRegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistryResponse) ProtoMessage() {}

func (x *GetRegistryResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *GetRegistryResponse) GetServers() []*LineServerInfo {
	if x != nil {
		return x.Servers
	}
	return nil
}

// LineServerInfo contains information about a registered line server.
type LineServerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId       string       `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerName     string       `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	PublicUrl      string       `protobuf:"bytes,3,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	CurrentLoad    int32        `protobuf:"varint,4,opt,name=current_load,json=currentLoad,proto3" json:"current_load,omitempty"`
	MaxClients     int32        `protobuf:"varint,5,opt,name=max_clients,json=maxClients,proto3" json:"max_clients,omitempty"`
	Status         ServerStatus `protobuf:"varint,6,opt,name=status,proto3,enum=lineserver.v1.ServerStatus" json:"status,omitempty"`
	AuctionEnabled bool         `protobuf:"varint,7,opt,name=auction_enabled,json=auctionEnabled,proto3" json:"auction_enabled,omitempty"`
	GuildEnabled   bool         `protobuf:"varint,8,opt,name=guild_enabled,json=guildEnabled,proto3" json:"guild_enabled,omitempty"`
}

func (x *LineServerInfo) Reset() {
	*x = LineServerInfo{}
}

func (x *LineServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineServerInfo) ProtoMessage() {}

func (x *LineServerInfo) ProtoReflect() protoreflect.Message {
	return nil
}

func (x *LineServerInfo) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *LineServerInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *LineServerInfo) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *LineServerInfo) GetCurrentLoad() int32 {
	if x != nil {
		return x.CurrentLoad
	}
	return 0
}

func (x *LineServerInfo) GetMaxClients() int32 {
	if x != nil {
		return x.MaxClients
	}
	return 0
}

func (x *LineServerInfo) GetStatus() ServerStatus {
	if x != nil {
		return x.Status
	}
	return ServerStatus_SERVER_STATUS_UNSPECIFIED
}

func (x *LineServerInfo) GetAuctionEnabled() bool {
	if x != nil {
		return x.AuctionEnabled
	}
	return false
}

func (x *LineServerInfo) GetGuildEnabled() bool {
	if x != nil {
		return x.GuildEnabled
	}
	return false
}
