// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// AchievementRequireTemplate represents TBL_ACHIEVEMENT_REQUIRE (table_id=75)
type AchievementRequireTemplate struct {
	ID int64 `json:"id" db:"id"`
	Aid float64 `json:"aid" db:"aid"`
	Name string `json:"name" db:"name"`
	Num float64 `json:"num" db:"num"`
	ShowType float64 `json:"show_type" db:"show_type"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *AchievementRequireTemplate) TableName() string {
	return "TBL_ACHIEVEMENT_REQUIRE"
}

// TableID returns the table ID for this template
func (t *AchievementRequireTemplate) TableID() int {
	return 75
}

// GetID returns the record ID as int
func (t *AchievementRequireTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *AchievementRequireTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_ACHIEVEMENT_REQUIRE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *AchievementRequireTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"aid": t.Aid,
		"name": t.Name,
		"num": t.Num,
		"show_type": t.ShowType,
		"type": t.Type,
	}
}

