// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// AchievementTemplate represents TBL_ACHIEVEMENT (table_id=74)
type AchievementTemplate struct {
	ID          int64   `json:"id" db:"id"`
	Award       float64 `json:"award" db:"award"`
	Check       float64 `json:"check" db:"check"`
	Color       float64 `json:"color" db:"color"`
	Desc        string  `json:"desc" db:"desc"`
	Description string  `json:"description" db:"description"`
	Detail      string  `json:"detail" db:"detail"`
	Enable      float64 `json:"enable" db:"enable"`
	IsAward     float64 `json:"is_award" db:"is_award"`
	Kind        float64 `json:"kind" db:"kind"`
	Name        string  `json:"name" db:"name"`
	Position    float64 `json:"position" db:"position"`
	RepeatType  float64 `json:"repeat_type" db:"repeat_type"`
	Type        float64 `json:"type" db:"type"`
	RewardType  *int    `json:"reward_type,omitempty" db:"reward_type"`
	RewardID    *int    `json:"reward_id,omitempty" db:"reward_id"`
	RewardQty   *int    `json:"reward_qty,omitempty" db:"reward_qty"`
}

// TableName returns the table name for this template
func (t *AchievementTemplate) TableName() string {
	return "TBL_ACHIEVEMENT"
}

// TableID returns the table ID for this template
func (t *AchievementTemplate) TableID() int {
	return 74
}

// GetID returns the record ID as int
func (t *AchievementTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *AchievementTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_ACHIEVEMENT ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *AchievementTemplate) ToDTO() map[string]interface{} {
	dto := map[string]interface{}{
		"id":          t.ID,
		"award":       t.Award,
		"check":       t.Check,
		"color":       t.Color,
		"desc":        t.Desc,
		"description": t.Description,
		"detail":      t.Detail,
		"enable":      t.Enable,
		"is_award":    t.IsAward,
		"kind":        t.Kind,
		"name":        t.Name,
		"position":    t.Position,
		"repeat_type": t.RepeatType,
		"type":        t.Type,
	}
	if t.RewardType != nil {
		dto["reward_type"] = *t.RewardType
	}
	if t.RewardID != nil {
		dto["reward_id"] = *t.RewardID
	}
	if t.RewardQty != nil {
		dto["reward_qty"] = *t.RewardQty
	}
	return dto
}

