// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// AnswerTemplate represents TBL_ANSWER (table_id=61)
type AnswerTemplate struct {
	ID int64 `json:"id" db:"id"`
	A string `json:"a" db:"a"`
	B string `json:"b" db:"b"`
	C string `json:"c" db:"c"`
	D string `json:"d" db:"d"`
	R string `json:"r" db:"r"`
	T string `json:"t" db:"t"`
}

// TableName returns the table name for this template
func (t *AnswerTemplate) TableName() string {
	return "TBL_ANSWER"
}

// TableID returns the table ID for this template
func (t *AnswerTemplate) TableID() int {
	return 61
}

// GetID returns the record ID as int
func (t *AnswerTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *AnswerTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_ANSWER ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *AnswerTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"a": t.A,
		"b": t.B,
		"c": t.C,
		"d": t.D,
		"r": t.R,
		"t": t.T,
	}
}

