// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// ArtifactTemplate represents TBL_ARTIFACT (table_id=102)
type ArtifactTemplate struct {
	ID int64 `json:"id" db:"id"`
	ItemNum float64 `json:"item_num" db:"item_num"`
	Level float64 `json:"level" db:"level"`
	PropNum1 float64 `json:"prop_num1" db:"prop_num1"`
	PropNum2 float64 `json:"prop_num2" db:"prop_num2"`
	Rate float64 `json:"rate" db:"rate"`
	SpiritNum float64 `json:"spirit_num" db:"spirit_num"`
	Tid float64 `json:"tid" db:"tid"`
}

// TableName returns the table name for this template
func (t *ArtifactTemplate) TableName() string {
	return "TBL_ARTIFACT"
}

// TableID returns the table ID for this template
func (t *ArtifactTemplate) TableID() int {
	return 102
}

// GetID returns the record ID as int
func (t *ArtifactTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *ArtifactTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_ARTIFACT ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *ArtifactTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"item_num": t.ItemNum,
		"level": t.Level,
		"prop_num1": t.PropNum1,
		"prop_num2": t.PropNum2,
		"rate": t.Rate,
		"spirit_num": t.SpiritNum,
		"tid": t.Tid,
	}
}

