// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
	"strconv"
	"strings"
)

// AwakeningSkillTemplate represents TBL_AWAKENING_SKILL (table_id=114)
type AwakeningSkillTemplate struct {
	ID int64 `json:"id" db:"id"`
	CostPoints float64 `json:"cost_points" db:"cost_points"`
	Description string `json:"description" db:"description"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	MaxLevel float64 `json:"max_level" db:"max_level"`
	Name string `json:"name" db:"name"`
	Position float64 `json:"position" db:"position"`
	ReqClass float64 `json:"req_class" db:"req_class"`
	ReqPoints float64 `json:"req_points" db:"req_points"`
	SkillCodeName string `json:"skill_code_name" db:"skill_code_name"`
}

// TableName returns the table name for this template
func (t *AwakeningSkillTemplate) TableName() string {
	return "TBL_AWAKENING_SKILL"
}

// TableID returns the table ID for this template
func (t *AwakeningSkillTemplate) TableID() int {
	return 114
}

// GetID returns the record ID as int
func (t *AwakeningSkillTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *AwakeningSkillTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_AWAKENING_SKILL ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *AwakeningSkillTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"cost_points": t.CostPoints,
		"description": t.Description,
		"icon_code": t.IconCode,
		"max_level": t.MaxLevel,
		"name": t.Name,
		"position": t.Position,
		"req_class": t.ReqClass,
		"req_points": t.ReqPoints,
		"skill_code_name": t.SkillCodeName,
	}
}

// ParsePipeDelimitedInts parses a pipe-delimited string like "|1|2|3|" into []int
func (t *AwakeningSkillTemplate) ParsePipeDelimitedInts(s string) []int {
	if s == "" || s == "|" {
		return nil
	}
	s = strings.Trim(s, "|")
	parts := strings.Split(s, "|")
	result := make([]int, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue
		}
		if n, err := strconv.Atoi(p); err == nil {
			result = append(result, n)
		}
	}
	return result
}
