// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// AwakeningTemplate represents TBL_AWAKENING (table_id=113)
type AwakeningTemplate struct {
	ID int64 `json:"id" db:"id"`
	ItemNum float64 `json:"item_num" db:"item_num"`
	Money float64 `json:"money" db:"money"`
	Name string `json:"name" db:"name"`
	Points float64 `json:"points" db:"points"`
	Prop1 float64 `json:"prop1" db:"prop1"`
	Prop2 float64 `json:"prop2" db:"prop2"`
	PropNum1 float64 `json:"prop_num1" db:"prop_num1"`
	PropNum2 float64 `json:"prop_num2" db:"prop_num2"`
	Rate float64 `json:"rate" db:"rate"`
	ReqLevel float64 `json:"req_level" db:"req_level"`
}

// TableName returns the table name for this template
func (t *AwakeningTemplate) TableName() string {
	return "TBL_AWAKENING"
}

// TableID returns the table ID for this template
func (t *AwakeningTemplate) TableID() int {
	return 113
}

// GetID returns the record ID as int
func (t *AwakeningTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *AwakeningTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_AWAKENING ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *AwakeningTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"item_num": t.ItemNum,
		"money": t.Money,
		"name": t.Name,
		"points": t.Points,
		"prop1": t.Prop1,
		"prop2": t.Prop2,
		"prop_num1": t.PropNum1,
		"prop_num2": t.PropNum2,
		"rate": t.Rate,
		"req_level": t.ReqLevel,
	}
}

