// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// BuffTemplate represents TBL_BUFF (table_id=66)
type BuffTemplate struct {
	ID int64 `json:"id" db:"id"`
	Buff float64 `json:"buff" db:"buff"`
	CodeName string `json:"code_name" db:"code_name"`
	Description string `json:"description" db:"description"`
	EffectNum float64 `json:"effect_num" db:"effect_num"`
	EffectTime float64 `json:"effect_time" db:"effect_time"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	Kind float64 `json:"kind" db:"kind"`
	Level float64 `json:"level" db:"level"`
	Name string `json:"name" db:"name"`
	PercentFlag float64 `json:"percent_flag" db:"percent_flag"`
	Prop1 float64 `json:"prop1" db:"prop1"`
	Prop2 float64 `json:"prop2" db:"prop2"`
	Prop3 float64 `json:"prop3" db:"prop3"`
	Prop4 float64 `json:"prop4" db:"prop4"`
	Prop5 float64 `json:"prop5" db:"prop5"`
	Prop6 float64 `json:"prop6" db:"prop6"`
	PropNum1 float64 `json:"prop_num1" db:"prop_num1"`
	PropNum2 float64 `json:"prop_num2" db:"prop_num2"`
	PropNum3 float64 `json:"prop_num3" db:"prop_num3"`
	PropNum4 float64 `json:"prop_num4" db:"prop_num4"`
	PropNum5 float64 `json:"prop_num5" db:"prop_num5"`
	PropNum6 float64 `json:"prop_num6" db:"prop_num6"`
	State float64 `json:"state" db:"state"`
	TargetType float64 `json:"target_type" db:"target_type"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *BuffTemplate) TableName() string {
	return "TBL_BUFF"
}

// TableID returns the table ID for this template
func (t *BuffTemplate) TableID() int {
	return 66
}

// GetID returns the record ID as int
func (t *BuffTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *BuffTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_BUFF ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *BuffTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"buff": t.Buff,
		"code_name": t.CodeName,
		"description": t.Description,
		"effect_num": t.EffectNum,
		"effect_time": t.EffectTime,
		"icon_code": t.IconCode,
		"kind": t.Kind,
		"level": t.Level,
		"name": t.Name,
		"percent_flag": t.PercentFlag,
		"prop1": t.Prop1,
		"prop2": t.Prop2,
		"prop3": t.Prop3,
		"prop4": t.Prop4,
		"prop5": t.Prop5,
		"prop6": t.Prop6,
		"prop_num1": t.PropNum1,
		"prop_num2": t.PropNum2,
		"prop_num3": t.PropNum3,
		"prop_num4": t.PropNum4,
		"prop_num5": t.PropNum5,
		"prop_num6": t.PropNum6,
		"state": t.State,
		"target_type": t.TargetType,
		"type": t.Type,
	}
}

