// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// BuildingTemplate represents TBL_BUILDING (table_id=70)
type BuildingTemplate struct {
	ID int64 `json:"id" db:"id"`
	CodeName string `json:"code_name" db:"code_name"`
	Description string `json:"description" db:"description"`
	ExpCost float64 `json:"exp_cost" db:"exp_cost"`
	FuncScript string `json:"func_script" db:"func_script"`
	GenMCost float64 `json:"gen_m_cost" db:"gen_m_cost"`
	GoldCost float64 `json:"gold_cost" db:"gold_cost"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	IconCodeSmall float64 `json:"icon_code_small" db:"icon_code_small"`
	Level float64 `json:"level" db:"level"`
	MaintainCost float64 `json:"maintain_cost" db:"maintain_cost"`
	MoneyCost float64 `json:"money_cost" db:"money_cost"`
	Name string `json:"name" db:"name"`
	NumLimit float64 `json:"num_limit" db:"num_limit"`
	PercentFlag float64 `json:"percent_flag" db:"percent_flag"`
	PostBuilding float64 `json:"post_building" db:"post_building"`
	PreBuilding string `json:"pre_building" db:"pre_building"`
	Prop1 float64 `json:"prop1" db:"prop1"`
	Prop1Value float64 `json:"prop1_value" db:"prop1_value"`
	Prop2 float64 `json:"prop2" db:"prop2"`
	Prop2Value float64 `json:"prop2_value" db:"prop2_value"`
	Prop3 float64 `json:"prop3" db:"prop3"`
	Prop3Value float64 `json:"prop3_value" db:"prop3_value"`
	Prop4 float64 `json:"prop4" db:"prop4"`
	Prop4Value float64 `json:"prop4_value" db:"prop4_value"`
	RareMCost float64 `json:"rare_m_cost" db:"rare_m_cost"`
	RequireScript float64 `json:"require_script" db:"require_script"`
	ResCode float64 `json:"res_code" db:"res_code"`
	SPMCost float64 `json:"sp_m_cost" db:"sp_m_cost"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *BuildingTemplate) TableName() string {
	return "TBL_BUILDING"
}

// TableID returns the table ID for this template
func (t *BuildingTemplate) TableID() int {
	return 70
}

// GetID returns the record ID as int
func (t *BuildingTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *BuildingTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_BUILDING ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *BuildingTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"code_name": t.CodeName,
		"description": t.Description,
		"exp_cost": t.ExpCost,
		"func_script": t.FuncScript,
		"gen_m_cost": t.GenMCost,
		"gold_cost": t.GoldCost,
		"icon_code": t.IconCode,
		"icon_code_small": t.IconCodeSmall,
		"level": t.Level,
		"maintain_cost": t.MaintainCost,
		"money_cost": t.MoneyCost,
		"name": t.Name,
		"num_limit": t.NumLimit,
		"percent_flag": t.PercentFlag,
		"post_building": t.PostBuilding,
		"pre_building": t.PreBuilding,
		"prop1": t.Prop1,
		"prop1_value": t.Prop1Value,
		"prop2": t.Prop2,
		"prop2_value": t.Prop2Value,
		"prop3": t.Prop3,
		"prop3_value": t.Prop3Value,
		"prop4": t.Prop4,
		"prop4_value": t.Prop4Value,
		"rare_m_cost": t.RareMCost,
		"require_script": t.RequireScript,
		"res_code": t.ResCode,
		"sp_m_cost": t.SPMCost,
		"type": t.Type,
	}
}

