// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// CarveTemplate represents TBL_CARVE (table_id=138)
type CarveTemplate struct {
	ID int64 `json:"id" db:"id"`
	Costkp float64 `json:"costkp" db:"costkp"`
	Icon float64 `json:"icon" db:"icon"`
	Lev float64 `json:"lev" db:"lev"`
	P float64 `json:"p" db:"p"`
	Part float64 `json:"part" db:"part"`
	Pv float64 `json:"pv" db:"pv"`
}

// TableName returns the table name for this template
func (t *CarveTemplate) TableName() string {
	return "TBL_CARVE"
}

// TableID returns the table ID for this template
func (t *CarveTemplate) TableID() int {
	return 138
}

// GetID returns the record ID as int
func (t *CarveTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *CarveTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_CARVE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *CarveTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"costkp": t.Costkp,
		"icon": t.Icon,
		"lev": t.Lev,
		"p": t.P,
		"part": t.Part,
		"pv": t.Pv,
	}
}

