// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// CarveMasterTemplate represents TBL_CARVE_MASTER (table_id=140)
type CarveMasterTemplate struct {
	ID int64 `json:"id" db:"id"`
	P1 float64 `json:"p1" db:"p1"`
	P2 float64 `json:"p2" db:"p2"`
	P3 float64 `json:"p3" db:"p3"`
	P4 float64 `json:"p4" db:"p4"`
	P5 float64 `json:"p5" db:"p5"`
	Pv1 float64 `json:"pv1" db:"pv1"`
	Pv2 float64 `json:"pv2" db:"pv2"`
	Pv3 float64 `json:"pv3" db:"pv3"`
	Pv4 float64 `json:"pv4" db:"pv4"`
	Pv5 float64 `json:"pv5" db:"pv5"`
}

// TableName returns the table name for this template
func (t *CarveMasterTemplate) TableName() string {
	return "TBL_CARVE_MASTER"
}

// TableID returns the table ID for this template
func (t *CarveMasterTemplate) TableID() int {
	return 140
}

// GetID returns the record ID as int
func (t *CarveMasterTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *CarveMasterTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_CARVE_MASTER ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *CarveMasterTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"p1": t.P1,
		"p2": t.P2,
		"p3": t.P3,
		"p4": t.P4,
		"p5": t.P5,
		"pv1": t.Pv1,
		"pv2": t.Pv2,
		"pv3": t.Pv3,
		"pv4": t.Pv4,
		"pv5": t.Pv5,
	}
}

