// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// CarveAwardTemplate represents TBL_CARVE_AWARD (table_id=139)
type CarveAwardTemplate struct {
	ID int64 `json:"id" db:"id"`
	Award float64 `json:"award" db:"award"`
	FreeExchagne float64 `json:"free_exchagne" db:"free_exchagne"`
	ItemID float64 `json:"item_id" db:"item_id"`
	Lev float64 `json:"lev" db:"lev"`
	PayExchangeTime float64 `json:"pay_exchange_time" db:"pay_exchange_time"`
}

// TableName returns the table name for this template
func (t *CarveAwardTemplate) TableName() string {
	return "TBL_CARVE_AWARD"
}

// TableID returns the table ID for this template
func (t *CarveAwardTemplate) TableID() int {
	return 139
}

// GetID returns the record ID as int
func (t *CarveAwardTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *CarveAwardTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_CARVE_AWARD ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *CarveAwardTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"award": t.Award,
		"free_exchagne": t.FreeExchagne,
		"item_id": t.ItemID,
		"lev": t.Lev,
		"pay_exchange_time": t.PayExchangeTime,
	}
}

