// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
	"strconv"
	"strings"
)

// ClassTemplate represents TBL_CLASS (table_id=11)
type ClassTemplate struct {
	ID int64 `json:"id" db:"id"`
	AptAgility float64 `json:"apt_agility" db:"apt_agility"`
	AptEnergy float64 `json:"apt_energy" db:"apt_energy"`
	AptIntelligence float64 `json:"apt_intelligence" db:"apt_intelligence"`
	AptStamina float64 `json:"apt_stamina" db:"apt_stamina"`
	AptStrength float64 `json:"apt_strength" db:"apt_strength"`
	AttAgility float64 `json:"att_agility" db:"att_agility"`
	AttEnergy float64 `json:"att_energy" db:"att_energy"`
	AttIntelligence float64 `json:"att_intelligence" db:"att_intelligence"`
	AttStamina float64 `json:"att_stamina" db:"att_stamina"`
	AttStrength float64 `json:"att_strength" db:"att_strength"`
	BrightCode float64 `json:"bright_code" db:"bright_code"`
	ClassDescription string `json:"class_description" db:"class_description"`
	ColorCodeFemale1 float64 `json:"color_code_female1" db:"color_code_female1"`
	ColorCodeFemale2 float64 `json:"color_code_female2" db:"color_code_female2"`
	ColorCodeFemale3 float64 `json:"color_code_female3" db:"color_code_female3"`
	ColorCodeMale1 float64 `json:"color_code_male1" db:"color_code_male1"`
	ColorCodeMale2 float64 `json:"color_code_male2" db:"color_code_male2"`
	ColorCodeMale3 float64 `json:"color_code_male3" db:"color_code_male3"`
	DescriptionFemale string `json:"description_female" db:"description_female"`
	DescriptionMale string `json:"description_male" db:"description_male"`
	IconCodeFemale float64 `json:"icon_code_female" db:"icon_code_female"`
	IconCodeMale float64 `json:"icon_code_male" db:"icon_code_male"`
	ImgCodeFemale float64 `json:"img_code_female" db:"img_code_female"`
	ImgCodeMale float64 `json:"img_code_male" db:"img_code_male"`
	LargeImgFemale float64 `json:"large_img_female" db:"large_img_female"`
	LargeImgMale float64 `json:"large_img_male" db:"large_img_male"`
	Name string `json:"name" db:"name"`
	ResCodeFemale float64 `json:"res_code_female" db:"res_code_female"`
	ResCodeFemale2 float64 `json:"res_code_female2" db:"res_code_female2"`
	ResCodeMale float64 `json:"res_code_male" db:"res_code_male"`
	ResCodeMale2 float64 `json:"res_code_male2" db:"res_code_male2"`
	SchoolDescription string `json:"school_description" db:"school_description"`
	StartItem float64 `json:"start_item" db:"start_item"`
	StartSkill string `json:"start_skill" db:"start_skill"`
}

// TableName returns the table name for this template
func (t *ClassTemplate) TableName() string {
	return "TBL_CLASS"
}

// TableID returns the table ID for this template
func (t *ClassTemplate) TableID() int {
	return 11
}

// GetID returns the record ID as int
func (t *ClassTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *ClassTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_CLASS ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *ClassTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"apt_agility": t.AptAgility,
		"apt_energy": t.AptEnergy,
		"apt_intelligence": t.AptIntelligence,
		"apt_stamina": t.AptStamina,
		"apt_strength": t.AptStrength,
		"att_agility": t.AttAgility,
		"att_energy": t.AttEnergy,
		"att_intelligence": t.AttIntelligence,
		"att_stamina": t.AttStamina,
		"att_strength": t.AttStrength,
		"bright_code": t.BrightCode,
		"class_description": t.ClassDescription,
		"color_code_female1": t.ColorCodeFemale1,
		"color_code_female2": t.ColorCodeFemale2,
		"color_code_female3": t.ColorCodeFemale3,
		"color_code_male1": t.ColorCodeMale1,
		"color_code_male2": t.ColorCodeMale2,
		"color_code_male3": t.ColorCodeMale3,
		"description_female": t.DescriptionFemale,
		"description_male": t.DescriptionMale,
		"icon_code_female": t.IconCodeFemale,
		"icon_code_male": t.IconCodeMale,
		"img_code_female": t.ImgCodeFemale,
		"img_code_male": t.ImgCodeMale,
		"large_img_female": t.LargeImgFemale,
		"large_img_male": t.LargeImgMale,
		"name": t.Name,
		"res_code_female": t.ResCodeFemale,
		"res_code_female2": t.ResCodeFemale2,
		"res_code_male": t.ResCodeMale,
		"res_code_male2": t.ResCodeMale2,
		"school_description": t.SchoolDescription,
		"start_item": t.StartItem,
		"start_skill": t.StartSkill,
	}
}

// ParsePipeDelimitedInts parses a pipe-delimited string like "|1|2|3|" into []int
func (t *ClassTemplate) ParsePipeDelimitedInts(s string) []int {
	if s == "" || s == "|" {
		return nil
	}
	s = strings.Trim(s, "|")
	parts := strings.Split(s, "|")
	result := make([]int, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue
		}
		if n, err := strconv.Atoi(p); err == nil {
			result = append(result, n)
		}
	}
	return result
}
