// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// CreatureSkillTemplate represents TBL_CREATURE_SKILL (table_id=14)
type CreatureSkillTemplate struct {
	ID int64 `json:"id" db:"id"`
	Cid float64 `json:"cid" db:"cid"`
	Position float64 `json:"position" db:"position"`
	Sid float64 `json:"sid" db:"sid"`
}

// TableName returns the table name for this template
func (t *CreatureSkillTemplate) TableName() string {
	return "TBL_CREATURE_SKILL"
}

// TableID returns the table ID for this template
func (t *CreatureSkillTemplate) TableID() int {
	return 14
}

// GetID returns the record ID as int
func (t *CreatureSkillTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *CreatureSkillTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_CREATURE_SKILL ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *CreatureSkillTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"cid": t.Cid,
		"position": t.Position,
		"sid": t.Sid,
	}
}

