// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// CreaturehContainTemplate represents TBL_CREATUREH_CONTAIN (table_id=133)
type CreaturehContainTemplate struct {
	ID int64 `json:"id" db:"id"`
	Exp float64 `json:"exp" db:"exp"`
	GoldNum float64 `json:"gold_num" db:"gold_num"`
	Line string `json:"line" db:"line"`
	Name string `json:"name" db:"name"`
	Num float64 `json:"num" db:"num"`
}

// TableName returns the table name for this template
func (t *CreaturehContainTemplate) TableName() string {
	return "TBL_CREATUREH_CONTAIN"
}

// TableID returns the table ID for this template
func (t *CreaturehContainTemplate) TableID() int {
	return 133
}

// GetID returns the record ID as int
func (t *CreaturehContainTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *CreaturehContainTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_CREATUREH_CONTAIN ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *CreaturehContainTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"exp": t.Exp,
		"gold_num": t.GoldNum,
		"line": t.Line,
		"name": t.Name,
		"num": t.Num,
	}
}

