// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// CreatureHandbookTemplate represents TBL_CREATURE_HANDBOOK (table_id=100)
type CreatureHandbookTemplate struct {
	ID int64 `json:"id" db:"id"`
	ActiveNum1 float64 `json:"active_num1" db:"active_num1"`
	ActiveNum2 float64 `json:"active_num2" db:"active_num2"`
	ActiveNum3 float64 `json:"active_num3" db:"active_num3"`
	ActiveNum4 float64 `json:"active_num4" db:"active_num4"`
	ClassID float64 `json:"class_id" db:"class_id"`
	Discription string `json:"discription" db:"discription"`
	EvolutionID float64 `json:"evolution_id" db:"evolution_id"`
	Mid float64 `json:"mid" db:"mid"`
	Name string `json:"name" db:"name"`
	PercentFlag float64 `json:"percent_flag" db:"percent_flag"`
	PropNum float64 `json:"prop_num" db:"prop_num"`
	PropType float64 `json:"prop_type" db:"prop_type"`
	RelateID float64 `json:"relate_id" db:"relate_id"`
	SkillId1 float64 `json:"skill_id1" db:"skill_id1"`
	SkillId2 float64 `json:"skill_id2" db:"skill_id2"`
	SkillId3 float64 `json:"skill_id3" db:"skill_id3"`
	SkillId4 float64 `json:"skill_id4" db:"skill_id4"`
}

// TableName returns the table name for this template
func (t *CreatureHandbookTemplate) TableName() string {
	return "TBL_CREATURE_HANDBOOK"
}

// TableID returns the table ID for this template
func (t *CreatureHandbookTemplate) TableID() int {
	return 100
}

// GetID returns the record ID as int
func (t *CreatureHandbookTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *CreatureHandbookTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_CREATURE_HANDBOOK ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *CreatureHandbookTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"active_num1": t.ActiveNum1,
		"active_num2": t.ActiveNum2,
		"active_num3": t.ActiveNum3,
		"active_num4": t.ActiveNum4,
		"class_id": t.ClassID,
		"discription": t.Discription,
		"evolution_id": t.EvolutionID,
		"mid": t.Mid,
		"name": t.Name,
		"percent_flag": t.PercentFlag,
		"prop_num": t.PropNum,
		"prop_type": t.PropType,
		"relate_id": t.RelateID,
		"skill_id1": t.SkillId1,
		"skill_id2": t.SkillId2,
		"skill_id3": t.SkillId3,
		"skill_id4": t.SkillId4,
	}
}

