// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// CreaturehHeartTemplate represents TBL_CREATUREH_HEART (table_id=131)
type CreaturehHeartTemplate struct {
	ID int64 `json:"id" db:"id"`
	Color float64 `json:"color" db:"color"`
	Desc string `json:"desc" db:"desc"`
	Exp float64 `json:"exp" db:"exp"`
	HeartTalent float64 `json:"heart_talent" db:"heart_talent"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	Name string `json:"name" db:"name"`
	PropType float64 `json:"prop_type" db:"prop_type"`
	Propnum float64 `json:"propnum" db:"propnum"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *CreaturehHeartTemplate) TableName() string {
	return "TBL_CREATUREH_HEART"
}

// TableID returns the table ID for this template
func (t *CreaturehHeartTemplate) TableID() int {
	return 131
}

// GetID returns the record ID as int
func (t *CreaturehHeartTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *CreaturehHeartTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_CREATUREH_HEART ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *CreaturehHeartTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"color": t.Color,
		"desc": t.Desc,
		"exp": t.Exp,
		"heart_talent": t.HeartTalent,
		"icon_code": t.IconCode,
		"name": t.Name,
		"prop_type": t.PropType,
		"propnum": t.Propnum,
		"type": t.Type,
	}
}

