// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
	"strconv"
	"strings"
)

// CreatureTemplate represents TBL_CREATURE (table_id=12)
type CreatureTemplate struct {
	ID int64 `json:"id" db:"id"`
	Aiid float64 `json:"aiid" db:"aiid"`
	AptAgility float64 `json:"apt_agility" db:"apt_agility"`
	AptEnergy float64 `json:"apt_energy" db:"apt_energy"`
	AptIntelligence float64 `json:"apt_intelligence" db:"apt_intelligence"`
	AptStamina float64 `json:"apt_stamina" db:"apt_stamina"`
	AptStrength float64 `json:"apt_strength" db:"apt_strength"`
	AttAgility float64 `json:"att_agility" db:"att_agility"`
	AttEnergy float64 `json:"att_energy" db:"att_energy"`
	AttIntelligence float64 `json:"att_intelligence" db:"att_intelligence"`
	AttLuck float64 `json:"att_luck" db:"att_luck"`
	AttStamina float64 `json:"att_stamina" db:"att_stamina"`
	AttStrength float64 `json:"att_strength" db:"att_strength"`
	BrightCode float64 `json:"bright_code" db:"bright_code"`
	Catchable float64 `json:"catchable" db:"catchable"`
	ClassID float64 `json:"class_id" db:"class_id"`
	ClassIds float64 `json:"class_ids" db:"class_ids"`
	ColorCode float64 `json:"color_code" db:"color_code"`
	Element float64 `json:"element" db:"element"`
	GrowBase float64 `json:"grow_base" db:"grow_base"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	IsBind float64 `json:"is_bind" db:"is_bind"`
	Life float64 `json:"life" db:"life"`
	Msg string `json:"msg" db:"msg"`
	Name string `json:"name" db:"name"`
	PropCombo float64 `json:"prop_combo" db:"prop_combo"`
	PropCounter float64 `json:"prop_counter" db:"prop_counter"`
	PropCritical float64 `json:"prop_critical" db:"prop_critical"`
	PropDefy float64 `json:"prop_defy" db:"prop_defy"`
	PropDodge float64 `json:"prop_dodge" db:"prop_dodge"`
	PropHit float64 `json:"prop_hit" db:"prop_hit"`
	PropReborn float64 `json:"prop_reborn" db:"prop_reborn"`
	PropSpeed float64 `json:"prop_speed" db:"prop_speed"`
	QLevel float64 `json:"q_level" db:"q_level"`
	ResCode float64 `json:"res_code" db:"res_code"`
	ResiDefy float64 `json:"resi_defy" db:"resi_defy"`
	ShowAble float64 `json:"show_able" db:"show_able"`
	Skill string `json:"skill" db:"skill"`
	UseLv float64 `json:"use_lv" db:"use_lv"`
}

// TableName returns the table name for this template
func (t *CreatureTemplate) TableName() string {
	return "TBL_CREATURE"
}

// TableID returns the table ID for this template
func (t *CreatureTemplate) TableID() int {
	return 12
}

// GetID returns the record ID as int
func (t *CreatureTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *CreatureTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_CREATURE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *CreatureTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"aiid": t.Aiid,
		"apt_agility": t.AptAgility,
		"apt_energy": t.AptEnergy,
		"apt_intelligence": t.AptIntelligence,
		"apt_stamina": t.AptStamina,
		"apt_strength": t.AptStrength,
		"att_agility": t.AttAgility,
		"att_energy": t.AttEnergy,
		"att_intelligence": t.AttIntelligence,
		"att_luck": t.AttLuck,
		"att_stamina": t.AttStamina,
		"att_strength": t.AttStrength,
		"bright_code": t.BrightCode,
		"catchable": t.Catchable,
		"class_id": t.ClassID,
		"class_ids": t.ClassIds,
		"color_code": t.ColorCode,
		"element": t.Element,
		"grow_base": t.GrowBase,
		"icon_code": t.IconCode,
		"is_bind": t.IsBind,
		"life": t.Life,
		"msg": t.Msg,
		"name": t.Name,
		"prop_combo": t.PropCombo,
		"prop_counter": t.PropCounter,
		"prop_critical": t.PropCritical,
		"prop_defy": t.PropDefy,
		"prop_dodge": t.PropDodge,
		"prop_hit": t.PropHit,
		"prop_reborn": t.PropReborn,
		"prop_speed": t.PropSpeed,
		"q_level": t.QLevel,
		"res_code": t.ResCode,
		"resi_defy": t.ResiDefy,
		"show_able": t.ShowAble,
		"skill": t.Skill,
		"use_lv": t.UseLv,
	}
}

// ParsePipeDelimitedInts parses a pipe-delimited string like "|1|2|3|" into []int
func (t *CreatureTemplate) ParsePipeDelimitedInts(s string) []int {
	if s == "" || s == "|" {
		return nil
	}
	s = strings.Trim(s, "|")
	parts := strings.Split(s, "|")
	result := make([]int, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue
		}
		if n, err := strconv.Atoi(p); err == nil {
			result = append(result, n)
		}
	}
	return result
}
