// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// CreaturehPointTemplate represents TBL_CREATUREH_POINT (table_id=134)
type CreaturehPointTemplate struct {
	ID int64 `json:"id" db:"id"`
	Combine string `json:"combine" db:"combine"`
	Goldnum float64 `json:"goldnum" db:"goldnum"`
	ItemID float64 `json:"item_id" db:"item_id"`
	LinkLine string `json:"link_line" db:"link_line"`
	Num float64 `json:"num" db:"num"`
	Quality float64 `json:"quality" db:"quality"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *CreaturehPointTemplate) TableName() string {
	return "TBL_CREATUREH_POINT"
}

// TableID returns the table ID for this template
func (t *CreaturehPointTemplate) TableID() int {
	return 134
}

// GetID returns the record ID as int
func (t *CreaturehPointTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *CreaturehPointTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_CREATUREH_POINT ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *CreaturehPointTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"combine": t.Combine,
		"goldnum": t.Goldnum,
		"item_id": t.ItemID,
		"link_line": t.LinkLine,
		"num": t.Num,
		"quality": t.Quality,
		"type": t.Type,
	}
}

