// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// CreatureLootTemplate represents TBL_CREATURE_LOOT (table_id=13)
type CreatureLootTemplate struct {
	ID int64 `json:"id" db:"id"`
	B float64 `json:"b" db:"b"`
	Cid float64 `json:"cid" db:"cid"`
	ItemID float64 `json:"item_id" db:"item_id"`
	Qid float64 `json:"qid" db:"qid"`
	Quality float64 `json:"quality" db:"quality"`
	Rate float64 `json:"rate" db:"rate"`
	Type float64 `json:"type" db:"type"`
	QtyMin float64 `json:"qty_min" db:"qty_min"`
	QtyMax float64 `json:"qty_max" db:"qty_max"`
}

// TableName returns the table name for this template
func (t *CreatureLootTemplate) TableName() string {
	return "TBL_CREATURE_LOOT"
}

// TableID returns the table ID for this template
func (t *CreatureLootTemplate) TableID() int {
	return 13
}

// GetID returns the record ID as int
func (t *CreatureLootTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *CreatureLootTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_CREATURE_LOOT ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *CreatureLootTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"b": t.B,
		"cid": t.Cid,
		"item_id": t.ItemID,
		"qid": t.Qid,
		"quality": t.Quality,
		"rate": t.Rate,
		"type": t.Type,
		"qty_min": t.QtyMin,
		"qty_max": t.QtyMax,
	}
}

