// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// CreaturehCombineTemplate represents TBL_CREATUREH_COMBINE (table_id=132)
type CreaturehCombineTemplate struct {
	ID int64 `json:"id" db:"id"`
	DisPlay float64 `json:"dis_play" db:"dis_play"`
	LineCombine string `json:"line_combine" db:"line_combine"`
	MaxNum float64 `json:"max_num" db:"max_num"`
	Name string `json:"name" db:"name"`
	PNum1 float64 `json:"p_num1" db:"p_num1"`
	PNum2 float64 `json:"p_num2" db:"p_num2"`
	PNum3 float64 `json:"p_num3" db:"p_num3"`
	PidCombine string `json:"pid_combine" db:"pid_combine"`
	PropType1 float64 `json:"prop_type1" db:"prop_type1"`
	PropType2 float64 `json:"prop_type2" db:"prop_type2"`
	PropType3 float64 `json:"prop_type3" db:"prop_type3"`
	TypeCombine string `json:"type_combine" db:"type_combine"`
}

// TableName returns the table name for this template
func (t *CreaturehCombineTemplate) TableName() string {
	return "TBL_CREATUREH_COMBINE"
}

// TableID returns the table ID for this template
func (t *CreaturehCombineTemplate) TableID() int {
	return 132
}

// GetID returns the record ID as int
func (t *CreaturehCombineTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *CreaturehCombineTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_CREATUREH_COMBINE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *CreaturehCombineTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"dis_play": t.DisPlay,
		"line_combine": t.LineCombine,
		"max_num": t.MaxNum,
		"name": t.Name,
		"p_num1": t.PNum1,
		"p_num2": t.PNum2,
		"p_num3": t.PNum3,
		"pid_combine": t.PidCombine,
		"prop_type1": t.PropType1,
		"prop_type2": t.PropType2,
		"prop_type3": t.PropType3,
		"type_combine": t.TypeCombine,
	}
}

