// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// CreditTemplate represents TBL_CREDIT (table_id=107)
type CreditTemplate struct {
	ID int64 `json:"id" db:"id"`
	Bind float64 `json:"bind" db:"bind"`
	CNum1 float64 `json:"c_num1" db:"c_num1"`
	CNum2 float64 `json:"c_num2" db:"c_num2"`
	CType1 float64 `json:"c_type1" db:"c_type1"`
	CType2 float64 `json:"c_type2" db:"c_type2"`
	IsSell float64 `json:"is_sell" db:"is_sell"`
	ItemID float64 `json:"item_id" db:"item_id"`
	LimitNum float64 `json:"limit_num" db:"limit_num"`
	LimitType float64 `json:"limit_type" db:"limit_type"`
	Position float64 `json:"position" db:"position"`
	Quality float64 `json:"quality" db:"quality"`
	ShopID float64 `json:"shop_id" db:"shop_id"`
	Tab float64 `json:"tab" db:"tab"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *CreditTemplate) TableName() string {
	return "TBL_CREDIT"
}

// TableID returns the table ID for this template
func (t *CreditTemplate) TableID() int {
	return 107
}

// GetID returns the record ID as int
func (t *CreditTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *CreditTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_CREDIT ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *CreditTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"bind": t.Bind,
		"c_num1": t.CNum1,
		"c_num2": t.CNum2,
		"c_type1": t.CType1,
		"c_type2": t.CType2,
		"is_sell": t.IsSell,
		"item_id": t.ItemID,
		"limit_num": t.LimitNum,
		"limit_type": t.LimitType,
		"position": t.Position,
		"quality": t.Quality,
		"shop_id": t.ShopID,
		"tab": t.Tab,
		"type": t.Type,
	}
}

