// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// DecoRuneTemplate represents TBL_DECO_RUNE (table_id=119)
type DecoRuneTemplate struct {
	ID int64 `json:"id" db:"id"`
	CanExchange float64 `json:"can_exchange" db:"can_exchange"`
	ChipID float64 `json:"chip_id" db:"chip_id"`
	Exp float64 `json:"exp" db:"exp"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	Kind float64 `json:"kind" db:"kind"`
	Level float64 `json:"level" db:"level"`
	Name string `json:"name" db:"name"`
	NextID float64 `json:"next_id" db:"next_id"`
	Per float64 `json:"per" db:"per"`
	PropNum float64 `json:"prop_num" db:"prop_num"`
	PropType float64 `json:"prop_type" db:"prop_type"`
	Qulity float64 `json:"qulity" db:"qulity"`
	Type float64 `json:"type" db:"type"`
	UpExp float64 `json:"up_exp" db:"up_exp"`
}

// TableName returns the table name for this template
func (t *DecoRuneTemplate) TableName() string {
	return "TBL_DECO_RUNE"
}

// TableID returns the table ID for this template
func (t *DecoRuneTemplate) TableID() int {
	return 119
}

// GetID returns the record ID as int
func (t *DecoRuneTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *DecoRuneTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_DECO_RUNE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *DecoRuneTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"can_exchange": t.CanExchange,
		"chip_id": t.ChipID,
		"exp": t.Exp,
		"icon_code": t.IconCode,
		"kind": t.Kind,
		"level": t.Level,
		"name": t.Name,
		"next_id": t.NextID,
		"per": t.Per,
		"prop_num": t.PropNum,
		"prop_type": t.PropType,
		"qulity": t.Qulity,
		"type": t.Type,
		"up_exp": t.UpExp,
	}
}

