// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// DecoHoleTemplate represents TBL_DECO_HOLE (table_id=118)
type DecoHoleTemplate struct {
	ID int64 `json:"id" db:"id"`
	CostNum float64 `json:"cost_num" db:"cost_num"`
	CostSil float64 `json:"cost_sil" db:"cost_sil"`
	Level float64 `json:"level" db:"level"`
	NextID float64 `json:"next_id" db:"next_id"`
	Num float64 `json:"num" db:"num"`
	Per float64 `json:"per" db:"per"`
	Position float64 `json:"position" db:"position"`
	PropNum1 float64 `json:"prop_num1" db:"prop_num1"`
	PropNum2 float64 `json:"prop_num2" db:"prop_num2"`
	PropNum3 float64 `json:"prop_num3" db:"prop_num3"`
	PropNum4 float64 `json:"prop_num4" db:"prop_num4"`
	PropType1 float64 `json:"prop_type1" db:"prop_type1"`
	PropType2 float64 `json:"prop_type2" db:"prop_type2"`
	PropType3 float64 `json:"prop_type3" db:"prop_type3"`
	PropType4 float64 `json:"prop_type4" db:"prop_type4"`
	Rate float64 `json:"rate" db:"rate"`
	TargetType float64 `json:"target_type" db:"target_type"`
}

// TableName returns the table name for this template
func (t *DecoHoleTemplate) TableName() string {
	return "TBL_DECO_HOLE"
}

// TableID returns the table ID for this template
func (t *DecoHoleTemplate) TableID() int {
	return 118
}

// GetID returns the record ID as int
func (t *DecoHoleTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *DecoHoleTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_DECO_HOLE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *DecoHoleTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"cost_num": t.CostNum,
		"cost_sil": t.CostSil,
		"level": t.Level,
		"next_id": t.NextID,
		"num": t.Num,
		"per": t.Per,
		"position": t.Position,
		"prop_num1": t.PropNum1,
		"prop_num2": t.PropNum2,
		"prop_num3": t.PropNum3,
		"prop_num4": t.PropNum4,
		"prop_type1": t.PropType1,
		"prop_type2": t.PropType2,
		"prop_type3": t.PropType3,
		"prop_type4": t.PropType4,
		"rate": t.Rate,
		"target_type": t.TargetType,
	}
}

