// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// DecoShowTemplate represents TBL_DECO_SHOW (table_id=120)
type DecoShowTemplate struct {
	ID int64 `json:"id" db:"id"`
	ActiveGold float64 `json:"active_gold" db:"active_gold"`
	Description string `json:"description" db:"description"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	LinkID float64 `json:"link_id" db:"link_id"`
	LinkSuitID float64 `json:"link_suit_id" db:"link_suit_id"`
	Name string `json:"name" db:"name"`
	Per float64 `json:"per" db:"per"`
	Position float64 `json:"position" db:"position"`
	PropNum1 float64 `json:"prop_num1" db:"prop_num1"`
	PropNum2 float64 `json:"prop_num2" db:"prop_num2"`
	PropNum3 float64 `json:"prop_num3" db:"prop_num3"`
	PropNum4 float64 `json:"prop_num4" db:"prop_num4"`
	PropType1 float64 `json:"prop_type1" db:"prop_type1"`
	PropType2 float64 `json:"prop_type2" db:"prop_type2"`
	PropType3 float64 `json:"prop_type3" db:"prop_type3"`
	PropType4 float64 `json:"prop_type4" db:"prop_type4"`
	ResCode1 float64 `json:"res_code1" db:"res_code1"`
	ResCode2 float64 `json:"res_code2" db:"res_code2"`
	ResCode3 float64 `json:"res_code3" db:"res_code3"`
	ResCode4 float64 `json:"res_code4" db:"res_code4"`
	ResCode5 float64 `json:"res_code5" db:"res_code5"`
	ResCode6 float64 `json:"res_code6" db:"res_code6"`
	SuitID float64 `json:"suit_id" db:"suit_id"`
	T float64 `json:"t" db:"t"`
	TargetType float64 `json:"target_type" db:"target_type"`
}

// TableName returns the table name for this template
func (t *DecoShowTemplate) TableName() string {
	return "TBL_DECO_SHOW"
}

// TableID returns the table ID for this template
func (t *DecoShowTemplate) TableID() int {
	return 120
}

// GetID returns the record ID as int
func (t *DecoShowTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *DecoShowTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_DECO_SHOW ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *DecoShowTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"active_gold": t.ActiveGold,
		"description": t.Description,
		"icon_code": t.IconCode,
		"link_id": t.LinkID,
		"link_suit_id": t.LinkSuitID,
		"name": t.Name,
		"per": t.Per,
		"position": t.Position,
		"prop_num1": t.PropNum1,
		"prop_num2": t.PropNum2,
		"prop_num3": t.PropNum3,
		"prop_num4": t.PropNum4,
		"prop_type1": t.PropType1,
		"prop_type2": t.PropType2,
		"prop_type3": t.PropType3,
		"prop_type4": t.PropType4,
		"res_code1": t.ResCode1,
		"res_code2": t.ResCode2,
		"res_code3": t.ResCode3,
		"res_code4": t.ResCode4,
		"res_code5": t.ResCode5,
		"res_code6": t.ResCode6,
		"suit_id": t.SuitID,
		"t": t.T,
		"target_type": t.TargetType,
	}
}

