// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// DiaryTemplate represents TBL_DIARY (table_id=85)
type DiaryTemplate struct {
	ID int64 `json:"id" db:"id"`
	Act float64 `json:"act" db:"act"`
	Info string `json:"info" db:"info"`
	LinkType float64 `json:"link_type" db:"link_type"`
	Max float64 `json:"max" db:"max"`
	Name string `json:"name" db:"name"`
	Nid float64 `json:"nid" db:"nid"`
	Pos float64 `json:"pos" db:"pos"`
}

// TableName returns the table name for this template
func (t *DiaryTemplate) TableName() string {
	return "TBL_DIARY"
}

// TableID returns the table ID for this template
func (t *DiaryTemplate) TableID() int {
	return 85
}

// GetID returns the record ID as int
func (t *DiaryTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *DiaryTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_DIARY ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *DiaryTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"act": t.Act,
		"info": t.Info,
		"link_type": t.LinkType,
		"max": t.Max,
		"name": t.Name,
		"nid": t.Nid,
		"pos": t.Pos,
	}
}

