// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// DressTemplate represents TBL_DRESS (table_id=104)
type DressTemplate struct {
	ID int64 `json:"id" db:"id"`
	Color float64 `json:"color" db:"color"`
	EquiptID float64 `json:"equipt_id" db:"equipt_id"`
	IsOpen float64 `json:"is_open" db:"is_open"`
	Name string `json:"name" db:"name"`
	Num1 float64 `json:"num1" db:"num1"`
	Num2 float64 `json:"num2" db:"num2"`
	Position float64 `json:"position" db:"position"`
	Prop1 float64 `json:"prop1" db:"prop1"`
	Prop2 float64 `json:"prop2" db:"prop2"`
	Prop3 float64 `json:"prop3" db:"prop3"`
	Prop4 float64 `json:"prop4" db:"prop4"`
	PropNum1 float64 `json:"prop_num1" db:"prop_num1"`
	PropNum2 float64 `json:"prop_num2" db:"prop_num2"`
	PropNum3 float64 `json:"prop_num3" db:"prop_num3"`
	PropNum4 float64 `json:"prop_num4" db:"prop_num4"`
	RecipeID float64 `json:"recipe_id" db:"recipe_id"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *DressTemplate) TableName() string {
	return "TBL_DRESS"
}

// TableID returns the table ID for this template
func (t *DressTemplate) TableID() int {
	return 104
}

// GetID returns the record ID as int
func (t *DressTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *DressTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_DRESS ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *DressTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"color": t.Color,
		"equipt_id": t.EquiptID,
		"is_open": t.IsOpen,
		"name": t.Name,
		"num1": t.Num1,
		"num2": t.Num2,
		"position": t.Position,
		"prop1": t.Prop1,
		"prop2": t.Prop2,
		"prop3": t.Prop3,
		"prop4": t.Prop4,
		"prop_num1": t.PropNum1,
		"prop_num2": t.PropNum2,
		"prop_num3": t.PropNum3,
		"prop_num4": t.PropNum4,
		"recipe_id": t.RecipeID,
		"type": t.Type,
	}
}

