// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
	"strconv"
	"strings"
)

// EquiptTemplateTemplate represents TBL_EQUIPT_TEMPLATE (table_id=19)
type EquiptTemplateTemplate struct {
	ID             int64   `json:"id" db:"id"`
	ActiveEquipID  float64 `json:"activeEquipId" db:"active_equip_id"`
	ActivePropNum  float64 `json:"activePropNum" db:"active_prop_num"`
	ActivePropType float64 `json:"activePropType" db:"active_prop_type"`
	ArtifactSkill  string  `json:"artifactSkill" db:"artifact_skill"`
	BindPropNum    float64 `json:"bindPropNum" db:"bind_prop_num"`
	BindType       float64 `json:"bindType" db:"bind_type"`
	BrightCode     float64 `json:"brightCode" db:"bright_code"`
	Color          float64 `json:"color" db:"color"`
	ColorCode      float64 `json:"colorCode" db:"color_code"`
	Description    string  `json:"description" db:"description"`
	EndureMax      float64 `json:"endureMax" db:"endure_max"`
	Gold           float64 `json:"gold" db:"gold"`
	HoleNum        float64 `json:"holeNum" db:"hole_num"`
	Honor          float64 `json:"honor" db:"honor"`
	IconCode       float64 `json:"iconCode" db:"icon_code"`
	Info           string  `json:"info" db:"info"`
	IsTest         float64 `json:"isTest" db:"is_test"`
	ItemLevel      float64 `json:"itemLevel" db:"item_level"`
	Kind           float64 `json:"kind" db:"kind"`
	MainProp1      float64 `json:"mainProp1" db:"main_prop1"`
	MainProp2      float64 `json:"mainProp2" db:"main_prop2"`
	MainPropNum1   float64 `json:"mainPropNum1" db:"main_prop_num1"`
	MainPropNum2   float64 `json:"mainPropNum2" db:"main_prop_num2"`
	Makable        float64 `json:"makable" db:"makable"`
	Name           string  `json:"name" db:"name"`
	NextEquTid     float64 `json:"nextEquTid" db:"next_equ_tid"`
	Position       float64 `json:"position" db:"position"`
	Price          float64 `json:"price" db:"price"`
	ProTime        float64 `json:"proTime" db:"pro_time"`
	Prop1          float64 `json:"prop1" db:"prop1"`
	Prop2          float64 `json:"prop2" db:"prop2"`
	PropNum1       float64 `json:"propNum1" db:"prop_num1"`
	PropNum2       float64 `json:"propNum2" db:"prop_num2"`
	Repairable     float64 `json:"repairable" db:"repairable"`
	ReqClass       string  `json:"reqClass" db:"req_class"`
	ReqClassID     string  `json:"reqClassId" db:"req_class_id"`
	ReqLevel       float64 `json:"reqLevel" db:"req_level"`
	RequireItem1   float64 `json:"requireItem1" db:"require_item1"`
	RequireItem2   float64 `json:"requireItem2" db:"require_item2"`
	RequireItem3   float64 `json:"requireItem3" db:"require_item3"`
	RequireNum1    float64 `json:"requireNum1" db:"require_num1"`
	RequireNum2    float64 `json:"requireNum2" db:"require_num2"`
	RequireNum3    float64 `json:"requireNum3" db:"require_num3"`
	ResCode        float64 `json:"resCode" db:"res_code"`
	ResCodeFemale  float64 `json:"resCodeFemale" db:"res_code_female"`
	ResCodeFemale2 float64 `json:"resCodeFemale2" db:"res_code_female2"`
	ResCodeMale    float64 `json:"resCodeMale" db:"res_code_male"`
	ResCodeMale2   float64 `json:"resCodeMale2" db:"res_code_male2"`
	SingleFlag     float64 `json:"singleFlag" db:"single_flag"`
	StackMax       float64 `json:"stackMax" db:"stack_max"`
	SuccRate       float64 `json:"succRate" db:"succ_rate"`
	SuitID         float64 `json:"suitId" db:"suit_id"`
	T              float64 `json:"t" db:"t"`
	Tradable       float64 `json:"tradable" db:"tradable"`
	Type           float64 `json:"type" db:"type"`
	UseType        float64 `json:"useType" db:"use_type"`
	WavCode        float64 `json:"wavCode" db:"wav_code"`
}

// TableName returns the table name for this template
func (t *EquiptTemplateTemplate) TableName() string {
	return "TBL_EQUIPT_TEMPLATE"
}

// TableID returns the table ID for this template
func (t *EquiptTemplateTemplate) TableID() int {
	return 19
}

// GetID returns the record ID as int
func (t *EquiptTemplateTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *EquiptTemplateTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_EQUIPT_TEMPLATE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *EquiptTemplateTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id":               t.ID,
		"active_equip_id":  t.ActiveEquipID,
		"active_prop_num":  t.ActivePropNum,
		"active_prop_type": t.ActivePropType,
		"artifact_skill":   t.ArtifactSkill,
		"bind_prop_num":    t.BindPropNum,
		"bind_type":        t.BindType,
		"bright_code":      t.BrightCode,
		"color":            t.Color,
		"color_code":       t.ColorCode,
		"description":      t.Description,
		"endure_max":       t.EndureMax,
		"gold":             t.Gold,
		"hole_num":         t.HoleNum,
		"honor":            t.Honor,
		"icon_code":        t.IconCode,
		"info":             t.Info,
		"is_test":          t.IsTest,
		"item_level":       t.ItemLevel,
		"kind":             t.Kind,
		"main_prop1":       t.MainProp1,
		"main_prop2":       t.MainProp2,
		"main_prop_num1":   t.MainPropNum1,
		"main_prop_num2":   t.MainPropNum2,
		"makable":          t.Makable,
		"name":             t.Name,
		"next_equ_tid":     t.NextEquTid,
		"position":         t.Position,
		"price":            t.Price,
		"pro_time":         t.ProTime,
		"prop1":            t.Prop1,
		"prop2":            t.Prop2,
		"prop_num1":        t.PropNum1,
		"prop_num2":        t.PropNum2,
		"repairable":       t.Repairable,
		"req_class":        t.ReqClass,
		"req_class_id":     t.ReqClassID,
		"req_level":        t.ReqLevel,
		"require_item1":    t.RequireItem1,
		"require_item2":    t.RequireItem2,
		"require_item3":    t.RequireItem3,
		"require_num1":     t.RequireNum1,
		"require_num2":     t.RequireNum2,
		"require_num3":     t.RequireNum3,
		"res_code":         t.ResCode,
		"res_code_female":  t.ResCodeFemale,
		"res_code_female2": t.ResCodeFemale2,
		"res_code_male":    t.ResCodeMale,
		"res_code_male2":   t.ResCodeMale2,
		"single_flag":      t.SingleFlag,
		"stack_max":        t.StackMax,
		"succ_rate":        t.SuccRate,
		"suit_id":          t.SuitID,
		"t":                t.T,
		"tradable":         t.Tradable,
		"type":             t.Type,
		"use_type":         t.UseType,
		"wav_code":         t.WavCode,
	}
}

// ParsePipeDelimitedInts parses a pipe-delimited string like "|1|2|3|" into []int
func (t *EquiptTemplateTemplate) ParsePipeDelimitedInts(s string) []int {
	if s == "" || s == "|" {
		return nil
	}
	s = strings.Trim(s, "|")
	parts := strings.Split(s, "|")
	result := make([]int, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue
		}
		if n, err := strconv.Atoi(p); err == nil {
			result = append(result, n)
		}
	}
	return result
}
