// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
	"strconv"
	"strings"
)

// EquiptSuitTemplate represents TBL_EQUIPT_SUIT (table_id=73)
type EquiptSuitTemplate struct {
	ID int64 `json:"id" db:"id"`
	Name string `json:"name" db:"name"`
	SiCodeName string `json:"si_code_name" db:"si_code_name"`
	SkillDescription string `json:"skill_description" db:"skill_description"`
	SuitProp1 float64 `json:"suit_prop1" db:"suit_prop1"`
	SuitProp2 float64 `json:"suit_prop2" db:"suit_prop2"`
	SuitProp3 float64 `json:"suit_prop3" db:"suit_prop3"`
	SuitProp4 float64 `json:"suit_prop4" db:"suit_prop4"`
	SuitProp5 float64 `json:"suit_prop5" db:"suit_prop5"`
	SuitPropNum1 float64 `json:"suit_prop_num1" db:"suit_prop_num1"`
	SuitPropNum2 float64 `json:"suit_prop_num2" db:"suit_prop_num2"`
	SuitPropNum3 float64 `json:"suit_prop_num3" db:"suit_prop_num3"`
	SuitPropNum4 float64 `json:"suit_prop_num4" db:"suit_prop_num4"`
	SuitPropNum5 float64 `json:"suit_prop_num5" db:"suit_prop_num5"`
}

// TableName returns the table name for this template
func (t *EquiptSuitTemplate) TableName() string {
	return "TBL_EQUIPT_SUIT"
}

// TableID returns the table ID for this template
func (t *EquiptSuitTemplate) TableID() int {
	return 73
}

// GetID returns the record ID as int
func (t *EquiptSuitTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *EquiptSuitTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_EQUIPT_SUIT ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *EquiptSuitTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"name": t.Name,
		"si_code_name": t.SiCodeName,
		"skill_description": t.SkillDescription,
		"suit_prop1": t.SuitProp1,
		"suit_prop2": t.SuitProp2,
		"suit_prop3": t.SuitProp3,
		"suit_prop4": t.SuitProp4,
		"suit_prop5": t.SuitProp5,
		"suit_prop_num1": t.SuitPropNum1,
		"suit_prop_num2": t.SuitPropNum2,
		"suit_prop_num3": t.SuitPropNum3,
		"suit_prop_num4": t.SuitPropNum4,
		"suit_prop_num5": t.SuitPropNum5,
	}
}

// ParsePipeDelimitedInts parses a pipe-delimited string like "|1|2|3|" into []int
func (t *EquiptSuitTemplate) ParsePipeDelimitedInts(s string) []int {
	if s == "" || s == "|" {
		return nil
	}
	s = strings.Trim(s, "|")
	parts := strings.Split(s, "|")
	result := make([]int, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue
		}
		if n, err := strconv.Atoi(p); err == nil {
			result = append(result, n)
		}
	}
	return result
}
