// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// ExplorerMedalTemplate represents TBL_EXPLORER_MEDAL (table_id=137)
type ExplorerMedalTemplate struct {
	ID int64 `json:"id" db:"id"`
	Cost float64 `json:"cost" db:"cost"`
	CostGold float64 `json:"cost_gold" db:"cost_gold"`
	Name string `json:"name" db:"name"`
	PropNum1 float64 `json:"prop_num1" db:"prop_num1"`
	PropNum2 float64 `json:"prop_num2" db:"prop_num2"`
	PropNum3 float64 `json:"prop_num3" db:"prop_num3"`
	PropNum4 float64 `json:"prop_num4" db:"prop_num4"`
	PropNum5 float64 `json:"prop_num5" db:"prop_num5"`
	PropNum6 float64 `json:"prop_num6" db:"prop_num6"`
	PropNum7 float64 `json:"prop_num7" db:"prop_num7"`
	PropNum8 float64 `json:"prop_num8" db:"prop_num8"`
	PropType1 float64 `json:"prop_type1" db:"prop_type1"`
	PropType2 float64 `json:"prop_type2" db:"prop_type2"`
	PropType3 float64 `json:"prop_type3" db:"prop_type3"`
	PropType4 float64 `json:"prop_type4" db:"prop_type4"`
	PropType5 float64 `json:"prop_type5" db:"prop_type5"`
	PropType6 float64 `json:"prop_type6" db:"prop_type6"`
	PropType7 float64 `json:"prop_type7" db:"prop_type7"`
	PropType8 float64 `json:"prop_type8" db:"prop_type8"`
}

// TableName returns the table name for this template
func (t *ExplorerMedalTemplate) TableName() string {
	return "TBL_EXPLORER_MEDAL"
}

// TableID returns the table ID for this template
func (t *ExplorerMedalTemplate) TableID() int {
	return 137
}

// GetID returns the record ID as int
func (t *ExplorerMedalTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *ExplorerMedalTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_EXPLORER_MEDAL ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *ExplorerMedalTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"cost": t.Cost,
		"cost_gold": t.CostGold,
		"name": t.Name,
		"prop_num1": t.PropNum1,
		"prop_num2": t.PropNum2,
		"prop_num3": t.PropNum3,
		"prop_num4": t.PropNum4,
		"prop_num5": t.PropNum5,
		"prop_num6": t.PropNum6,
		"prop_num7": t.PropNum7,
		"prop_num8": t.PropNum8,
		"prop_type1": t.PropType1,
		"prop_type2": t.PropType2,
		"prop_type3": t.PropType3,
		"prop_type4": t.PropType4,
		"prop_type5": t.PropType5,
		"prop_type6": t.PropType6,
		"prop_type7": t.PropType7,
		"prop_type8": t.PropType8,
	}
}

