// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// ExtendPositionTemplate represents TBL_EXTEND_POSITION (table_id=71)
type ExtendPositionTemplate struct {
	ID int64 `json:"id" db:"id"`
	BuildType float64 `json:"build_type" db:"build_type"`
	Layer float64 `json:"layer" db:"layer"`
	Mid float64 `json:"mid" db:"mid"`
	PosDir float64 `json:"pos_dir" db:"pos_dir"`
	PosX float64 `json:"pos_x" db:"pos_x"`
	PosY float64 `json:"pos_y" db:"pos_y"`
	Tid float64 `json:"tid" db:"tid"`
}

// TableName returns the table name for this template
func (t *ExtendPositionTemplate) TableName() string {
	return "TBL_EXTEND_POSITION"
}

// TableID returns the table ID for this template
func (t *ExtendPositionTemplate) TableID() int {
	return 71
}

// GetID returns the record ID as int
func (t *ExtendPositionTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *ExtendPositionTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_EXTEND_POSITION ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *ExtendPositionTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"build_type": t.BuildType,
		"layer": t.Layer,
		"mid": t.Mid,
		"pos_dir": t.PosDir,
		"pos_x": t.PosX,
		"pos_y": t.PosY,
		"tid": t.Tid,
	}
}

