// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// FairyTempalteTemplate represents TBL_FAIRY_TEMPALTE (table_id=86)
type FairyTempalteTemplate struct {
	ID int64 `json:"id" db:"id"`
	Agi float64 `json:"agi" db:"agi"`
	AgiG float64 `json:"agi_g" db:"agi_g"`
	Cc float64 `json:"cc" db:"cc"`
	Ener float64 `json:"ener" db:"ener"`
	EnerG float64 `json:"ener_g" db:"ener_g"`
	Inte float64 `json:"inte" db:"inte"`
	InteG float64 `json:"inte_g" db:"inte_g"`
	Name string `json:"name" db:"name"`
	Rc float64 `json:"rc" db:"rc"`
	Sta float64 `json:"sta" db:"sta"`
	StaG float64 `json:"sta_g" db:"sta_g"`
	Ste float64 `json:"ste" db:"ste"`
	SteG float64 `json:"ste_g" db:"ste_g"`
}

// TableName returns the table name for this template
func (t *FairyTempalteTemplate) TableName() string {
	return "TBL_FAIRY_TEMPALTE"
}

// TableID returns the table ID for this template
func (t *FairyTempalteTemplate) TableID() int {
	return 86
}

// GetID returns the record ID as int
func (t *FairyTempalteTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *FairyTempalteTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_FAIRY_TEMPALTE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *FairyTempalteTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"agi": t.Agi,
		"agi_g": t.AgiG,
		"cc": t.Cc,
		"ener": t.Ener,
		"ener_g": t.EnerG,
		"inte": t.Inte,
		"inte_g": t.InteG,
		"name": t.Name,
		"rc": t.Rc,
		"sta": t.Sta,
		"sta_g": t.StaG,
		"ste": t.Ste,
		"ste_g": t.SteG,
	}
}

