// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// FeastTemplate represents TBL_FEAST (table_id=67)
type FeastTemplate struct {
	ID int64 `json:"id" db:"id"`
	At string `json:"at" db:"at"`
	Aw float64 `json:"aw" db:"aw"`
	Inf string `json:"inf" db:"inf"`
	Na string `json:"na" db:"na"`
}

// TableName returns the table name for this template
func (t *FeastTemplate) TableName() string {
	return "TBL_FEAST"
}

// TableID returns the table ID for this template
func (t *FeastTemplate) TableID() int {
	return 67
}

// GetID returns the record ID as int
func (t *FeastTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *FeastTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_FEAST ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *FeastTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"at": t.At,
		"aw": t.Aw,
		"inf": t.Inf,
		"na": t.Na,
	}
}

