// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// GuideTemplate represents TBL_GUIDE (table_id=79)
type GuideTemplate struct {
	ID int64 `json:"id" db:"id"`
	FindNPCID float64 `json:"find_npc_id" db:"find_npc_id"`
	FinishType float64 `json:"finish_type" db:"finish_type"`
	Level float64 `json:"level" db:"level"`
	MouseX float64 `json:"mouse_x" db:"mouse_x"`
	MouseY float64 `json:"mouse_y" db:"mouse_y"`
	PromptText string `json:"prompt_text" db:"prompt_text"`
	PromptType float64 `json:"prompt_type" db:"prompt_type"`
	Reference float64 `json:"reference" db:"reference"`
	ScNpcid float64 `json:"sc_npcid" db:"sc_npcid"`
	ScOtherID float64 `json:"sc_other_id" db:"sc_other_id"`
	ScPid float64 `json:"sc_pid" db:"sc_pid"`
	ScQname string `json:"sc_qname" db:"sc_qname"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *GuideTemplate) TableName() string {
	return "TBL_GUIDE"
}

// TableID returns the table ID for this template
func (t *GuideTemplate) TableID() int {
	return 79
}

// GetID returns the record ID as int
func (t *GuideTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *GuideTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_GUIDE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *GuideTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"find_npc_id": t.FindNPCID,
		"finish_type": t.FinishType,
		"level": t.Level,
		"mouse_x": t.MouseX,
		"mouse_y": t.MouseY,
		"prompt_text": t.PromptText,
		"prompt_type": t.PromptType,
		"reference": t.Reference,
		"sc_npcid": t.ScNpcid,
		"sc_other_id": t.ScOtherID,
		"sc_pid": t.ScPid,
		"sc_qname": t.ScQname,
		"type": t.Type,
	}
}

