// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// HeiyaoshiPointTemplate represents TBL_HEIYAOSHI_POINT (table_id=145)
type HeiyaoshiPointTemplate struct {
	ID      int64 `json:"id" db:"id"`
	Figure  int   `json:"figure" db:"figure"`
	PointID int   `json:"point_id" db:"point_id"`
	Price   int   `json:"price" db:"price"`
	Gold    int   `json:"gold" db:"gold"`
}

func (t *HeiyaoshiPointTemplate) TableName() string { return "TBL_HEIYAOSHI_POINT" }
func (t *HeiyaoshiPointTemplate) TableID() int       { return 145 }
func (t *HeiyaoshiPointTemplate) GetID() int         { return int(t.ID) }
func (t *HeiyaoshiPointTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_HEIYAOSHI_POINT ID: %d", t.ID)
	}
	return nil
}
func (t *HeiyaoshiPointTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id":       t.ID,
		"figure":   t.Figure,
		"point_id": t.PointID,
		"price":    t.Price,
		"gold":     t.Gold,
	}
}
