// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// HeiyaoshiFullBuffTemplate represents TBL_HEIYAOSHI_FULL_BUFF (table_id=149)
type HeiyaoshiFullBuffTemplate struct {
	ID     int64   `json:"id" db:"id"`
	Figure int     `json:"figure" db:"figure"`
	PropID int     `json:"prop_id" db:"prop_id"`
	Value  float64 `json:"value" db:"value"`
}

func (t *HeiyaoshiFullBuffTemplate) TableName() string { return "TBL_HEIYAOSHI_FULL_BUFF" }
func (t *HeiyaoshiFullBuffTemplate) TableID() int       { return 149 }
func (t *HeiyaoshiFullBuffTemplate) GetID() int         { return int(t.ID) }
func (t *HeiyaoshiFullBuffTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_HEIYAOSHI_FULL_BUFF ID: %d", t.ID)
	}
	return nil
}
func (t *HeiyaoshiFullBuffTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id":      t.ID,
		"figure":  t.Figure,
		"prop_id": t.PropID,
		"value":   t.Value,
	}
}
