// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// HeiyaoshiAreaAttributeTemplate represents TBL_HEIYAOSHI_AREA_ATTRIBUTE (table_id=148)
type HeiyaoshiAreaAttributeTemplate struct {
	ID     int64   `json:"id" db:"id"`
	Figure int     `json:"figure" db:"figure"`
	AreaID int     `json:"area_id" db:"area_id"`
	PropID int     `json:"prop_id" db:"prop_id"`
	Value  float64 `json:"value" db:"value"`
}

func (t *HeiyaoshiAreaAttributeTemplate) TableName() string { return "TBL_HEIYAOSHI_AREA_ATTRIBUTE" }
func (t *HeiyaoshiAreaAttributeTemplate) TableID() int       { return 148 }
func (t *HeiyaoshiAreaAttributeTemplate) GetID() int         { return int(t.ID) }
func (t *HeiyaoshiAreaAttributeTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_HEIYAOSHI_AREA_ATTRIBUTE ID: %d", t.ID)
	}
	return nil
}
func (t *HeiyaoshiAreaAttributeTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id":      t.ID,
		"figure":  t.Figure,
		"area_id": t.AreaID,
		"prop_id": t.PropID,
		"value":   t.Value,
	}
}
