// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// HeiyaoshiPointLinkTemplate represents TBL_HEIYAOSHI_POINT_LINK (table_id=146)
type HeiyaoshiPointLinkTemplate struct {
	ID         int64  `json:"id" db:"id"`
	Figure     int    `json:"figure" db:"figure"`
	PointID    int    `json:"point_id" db:"point_id"`
	LinkType   string `json:"link_type" db:"link_type"`
	Ord        int    `json:"ord" db:"ord"`
	NeighborID int    `json:"neighbor_id" db:"neighbor_id"`
}

func (t *HeiyaoshiPointLinkTemplate) TableName() string { return "TBL_HEIYAOSHI_POINT_LINK" }
func (t *HeiyaoshiPointLinkTemplate) TableID() int       { return 146 }
func (t *HeiyaoshiPointLinkTemplate) GetID() int         { return int(t.ID) }
func (t *HeiyaoshiPointLinkTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_HEIYAOSHI_POINT_LINK ID: %d", t.ID)
	}
	return nil
}
func (t *HeiyaoshiPointLinkTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id":          t.ID,
		"figure":      t.Figure,
		"point_id":    t.PointID,
		"link_type":   t.LinkType,
		"ord":         t.Ord,
		"neighbor_id": t.NeighborID,
	}
}
