// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// HeiyaoshiAreaTemplate represents TBL_HEIYAOSHI_AREA (table_id=147)
type HeiyaoshiAreaTemplate struct {
	ID      int64 `json:"id" db:"id"`
	Figure  int   `json:"figure" db:"figure"`
	AreaID  int   `json:"area_id" db:"area_id"`
	LResNum int64 `json:"l_res_num" db:"l_res_num"`
	AResNum int64 `json:"a_res_num" db:"a_res_num"`
}

func (t *HeiyaoshiAreaTemplate) TableName() string { return "TBL_HEIYAOSHI_AREA" }
func (t *HeiyaoshiAreaTemplate) TableID() int       { return 147 }
func (t *HeiyaoshiAreaTemplate) GetID() int         { return int(t.ID) }
func (t *HeiyaoshiAreaTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_HEIYAOSHI_AREA ID: %d", t.ID)
	}
	return nil
}
func (t *HeiyaoshiAreaTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id":        t.ID,
		"figure":    t.Figure,
		"area_id":   t.AreaID,
		"l_res_num": t.LResNum,
		"a_res_num": t.AResNum,
	}
}
