// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
	"strconv"
	"strings"
)

// ItemTemplateTemplate represents TBL_ITEM_TEMPLATE (table_id=29)
type ItemTemplateTemplate struct {
	ID           int64   `json:"id" db:"id"`
	BindType     float64 `json:"bindType" db:"bind_type"`
	Color        float64 `json:"color" db:"color"`
	ColorCode    float64 `json:"colorCode" db:"color_code"`
	Description  string  `json:"description" db:"description"`
	Gold         float64 `json:"gold" db:"gold"`
	Honor        float64 `json:"honor" db:"honor"`
	I1           float64 `json:"i1" db:"i1"`
	I2           float64 `json:"i2" db:"i2"`
	I3           float64 `json:"i3" db:"i3"`
	IconCode     float64 `json:"iconCode" db:"icon_code"`
	Info         string  `json:"info" db:"info"`
	IsTest       float64 `json:"isTest" db:"is_test"`
	ItemLevel    float64 `json:"itemLevel" db:"item_level"`
	Kind         float64 `json:"kind" db:"kind"`
	Level        float64 `json:"level" db:"level"`
	Makable      float64 `json:"makable" db:"makable"`
	N1           float64 `json:"n1" db:"n1"`
	N2           float64 `json:"n2" db:"n2"`
	N3           float64 `json:"n3" db:"n3"`
	Name         string  `json:"name" db:"name"`
	NextJewelTid float64 `json:"nextJewelTid" db:"next_jewel_tid"`
	Price        float64 `json:"price" db:"price"`
	PropType     float64 `json:"propType" db:"prop_type"`
	ProplNum     float64 `json:"proplNum" db:"propl_num"`
	ReqClass     string  `json:"reqClass" db:"req_class"`
	ReqLevel     float64 `json:"reqLevel" db:"req_level"`
	ResCode      float64 `json:"resCode" db:"res_code"`
	SingleFlag   float64 `json:"singleFlag" db:"single_flag"`
	SkillID      float64 `json:"skillId" db:"skill_id"`
	StackMax     float64 `json:"stackMax" db:"stack_max"`
	T            float64 `json:"t" db:"t"`
	Tradable     float64 `json:"tradable" db:"tradable"`
	Type         float64 `json:"type" db:"type"`
	UseType      float64 `json:"useType" db:"use_type"`
}

// TableName returns the table name for this template
func (t *ItemTemplateTemplate) TableName() string {
	return "TBL_ITEM_TEMPLATE"
}

// TableID returns the table ID for this template
func (t *ItemTemplateTemplate) TableID() int {
	return 29
}

// GetID returns the record ID as int
func (t *ItemTemplateTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *ItemTemplateTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_ITEM_TEMPLATE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *ItemTemplateTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"bind_type": t.BindType,
		"color": t.Color,
		"color_code": t.ColorCode,
		"description": t.Description,
		"gold": t.Gold,
		"honor": t.Honor,
		"i1": t.I1,
		"i2": t.I2,
		"i3": t.I3,
		"icon_code": t.IconCode,
		"info": t.Info,
		"is_test": t.IsTest,
		"item_level": t.ItemLevel,
		"kind": t.Kind,
		"level": t.Level,
		"makable": t.Makable,
		"n1": t.N1,
		"n2": t.N2,
		"n3": t.N3,
		"name": t.Name,
		"next_jewel_tid": t.NextJewelTid,
		"price": t.Price,
		"prop_type": t.PropType,
		"propl_num": t.ProplNum,
		"req_class": t.ReqClass,
		"req_level": t.ReqLevel,
		"res_code": t.ResCode,
		"single_flag": t.SingleFlag,
		"skill_id": t.SkillID,
		"stack_max": t.StackMax,
		"t": t.T,
		"tradable": t.Tradable,
		"type": t.Type,
		"use_type": t.UseType,
	}
}

// ParsePipeDelimitedInts parses a pipe-delimited string like "|1|2|3|" into []int
func (t *ItemTemplateTemplate) ParsePipeDelimitedInts(s string) []int {
	if s == "" || s == "|" {
		return nil
	}
	s = strings.Trim(s, "|")
	parts := strings.Split(s, "|")
	result := make([]int, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue
		}
		if n, err := strconv.Atoi(p); err == nil {
			result = append(result, n)
		}
	}
	return result
}
