// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MapTemplate represents TBL_MAP (table_id=33)
type MapTemplate struct {
	ID int64 `json:"id" db:"id"`
	AirSafe float64 `json:"air_safe" db:"air_safe"`
	BasicBattleRate float64 `json:"basic_battle_rate" db:"basic_battle_rate"`
	BasicMaxNum float64 `json:"basic_max_num" db:"basic_max_num"`
	BasicMinNum float64 `json:"basic_min_num" db:"basic_min_num"`
	BrightCode float64 `json:"bright_code" db:"bright_code"`
	Cl string `json:"cl" db:"cl"`
	ColorCode float64 `json:"color_code" db:"color_code"`
	CopyFlag float64 `json:"copy_flag" db:"copy_flag"`
	Dead float64 `json:"dead" db:"dead"`
	ExpMulti float64 `json:"exp_multi" db:"exp_multi"`
	Flyable float64 `json:"flyable" db:"flyable"`
	G float64 `json:"g" db:"g"`
	Height float64 `json:"height" db:"height"`
	Info string `json:"info" db:"info"`
	Land float64 `json:"land" db:"land"`
	LastEditTime float64 `json:"last_edit_time" db:"last_edit_time"`
	Level float64 `json:"level" db:"level"`
	Lv float64 `json:"lv" db:"lv"`
	M float64 `json:"m" db:"m"`
	MMap float64 `json:"m_map" db:"m_map"`
	Name string `json:"name" db:"name"`
	Pk float64 `json:"pk" db:"pk"`
	PlBattle string `json:"pl_battle" db:"pl_battle"`
	PlProduct string `json:"pl_product" db:"pl_product"`
	ResCode float64 `json:"res_code" db:"res_code"`
	SArea string `json:"s_area" db:"s_area"`
	SMap float64 `json:"s_map" db:"s_map"`
	SafeFlag float64 `json:"safe_flag" db:"safe_flag"`
	SafeX float64 `json:"safe_x" db:"safe_x"`
	SafeY float64 `json:"safe_y" db:"safe_y"`
	T float64 `json:"t" db:"t"`
	Type float64 `json:"type" db:"type"`
	Width float64 `json:"width" db:"width"`
}

// TableName returns the table name for this template
func (t *MapTemplate) TableName() string {
	return "TBL_MAP"
}

// TableID returns the table ID for this template
func (t *MapTemplate) TableID() int {
	return 33
}

// GetID returns the record ID as int
func (t *MapTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MapTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MAP ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MapTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"air_safe": t.AirSafe,
		"basic_battle_rate": t.BasicBattleRate,
		"basic_max_num": t.BasicMaxNum,
		"basic_min_num": t.BasicMinNum,
		"bright_code": t.BrightCode,
		"cl": t.Cl,
		"color_code": t.ColorCode,
		"copy_flag": t.CopyFlag,
		"dead": t.Dead,
		"exp_multi": t.ExpMulti,
		"flyable": t.Flyable,
		"g": t.G,
		"height": t.Height,
		"info": t.Info,
		"land": t.Land,
		"last_edit_time": t.LastEditTime,
		"level": t.Level,
		"lv": t.Lv,
		"m": t.M,
		"m_map": t.MMap,
		"name": t.Name,
		"pk": t.Pk,
		"pl_battle": t.PlBattle,
		"pl_product": t.PlProduct,
		"res_code": t.ResCode,
		"s_area": t.SArea,
		"s_map": t.SMap,
		"safe_flag": t.SafeFlag,
		"safe_x": t.SafeX,
		"safe_y": t.SafeY,
		"t": t.T,
		"type": t.Type,
		"width": t.Width,
	}
}

