// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MapCellTemplate represents TBL_MAP_CELL (table_id=60)
type MapCellTemplate struct {
	ID int64 `json:"id" db:"id"`
	Mid float64 `json:"mid" db:"mid"`
	PosX float64 `json:"pos_x" db:"pos_x"`
	PosY float64 `json:"pos_y" db:"pos_y"`
	ResCode float64 `json:"res_code" db:"res_code"`
}

// TableName returns the table name for this template
func (t *MapCellTemplate) TableName() string {
	return "TBL_MAP_CELL"
}

// TableID returns the table ID for this template
func (t *MapCellTemplate) TableID() int {
	return 60
}

// GetID returns the record ID as int
func (t *MapCellTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MapCellTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MAP_CELL ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MapCellTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"mid": t.Mid,
		"pos_x": t.PosX,
		"pos_y": t.PosY,
		"res_code": t.ResCode,
	}
}

