// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MapCreatureTemplate represents TBL_MAP_CREATURE (table_id=34)
type MapCreatureTemplate struct {
	ID int64 `json:"id" db:"id"`
	BattleMode float64 `json:"battle_mode" db:"battle_mode"`
	BossFlag float64 `json:"boss_flag" db:"boss_flag"`
	Cid float64 `json:"cid" db:"cid"`
	EndRate float64 `json:"end_rate" db:"end_rate"`
	Exp float64 `json:"exp" db:"exp"`
	ExpMulti float64 `json:"exp_multi" db:"exp_multi"`
	ExpSet float64 `json:"exp_set" db:"exp_set"`
	Level float64 `json:"level" db:"level"`
	Mid float64 `json:"mid" db:"mid"`
	QLevel float64 `json:"q_level" db:"q_level"`
	StartRate float64 `json:"start_rate" db:"start_rate"`
	UniqueFlag float64 `json:"unique_flag" db:"unique_flag"`
	WithCloud float64 `json:"with_cloud" db:"with_cloud"`
}

// TableName returns the table name for this template
func (t *MapCreatureTemplate) TableName() string {
	return "TBL_MAP_CREATURE"
}

// TableID returns the table ID for this template
func (t *MapCreatureTemplate) TableID() int {
	return 34
}

// GetID returns the record ID as int
func (t *MapCreatureTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MapCreatureTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MAP_CREATURE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MapCreatureTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"battle_mode": t.BattleMode,
		"boss_flag": t.BossFlag,
		"cid": t.Cid,
		"end_rate": t.EndRate,
		"exp": t.Exp,
		"exp_multi": t.ExpMulti,
		"exp_set": t.ExpSet,
		"level": t.Level,
		"mid": t.Mid,
		"q_level": t.QLevel,
		"start_rate": t.StartRate,
		"unique_flag": t.UniqueFlag,
		"with_cloud": t.WithCloud,
	}
}

