// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MazeTemplate represents TBL_MAZE (table_id=99)
type MazeTemplate struct {
	ID int64 `json:"id" db:"id"`
	Description string `json:"description" db:"description"`
	Max float64 `json:"max" db:"max"`
	Min float64 `json:"min" db:"min"`
	Name string `json:"name" db:"name"`
	Rate float64 `json:"rate" db:"rate"`
	ResultScript string `json:"result_script" db:"result_script"`
}

// TableName returns the table name for this template
func (t *MazeTemplate) TableName() string {
	return "TBL_MAZE"
}

// TableID returns the table ID for this template
func (t *MazeTemplate) TableID() int {
	return 99
}

// GetID returns the record ID as int
func (t *MazeTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MazeTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MAZE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MazeTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"description": t.Description,
		"max": t.Max,
		"min": t.Min,
		"name": t.Name,
		"rate": t.Rate,
		"result_script": t.ResultScript,
	}
}

