// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MedalTemplate represents TBL_MEDAL (table_id=98)
type MedalTemplate struct {
	ID int64 `json:"id" db:"id"`
	BasicTid float64 `json:"basic_tid" db:"basic_tid"`
	Clevel float64 `json:"clevel" db:"clevel"`
	Desc string `json:"desc" db:"desc"`
	Exp float64 `json:"exp" db:"exp"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	JoinTid string `json:"join_tid" db:"join_tid"`
	Level float64 `json:"level" db:"level"`
	Name string `json:"name" db:"name"`
	Preflag float64 `json:"preflag" db:"preflag"`
	PropType float64 `json:"prop_type" db:"prop_type"`
	PropVal float64 `json:"prop_val" db:"prop_val"`
	Q float64 `json:"q" db:"q"`
	Sid float64 `json:"sid" db:"sid"`
	UpExp float64 `json:"up_exp" db:"up_exp"`
}

// TableName returns the table name for this template
func (t *MedalTemplate) TableName() string {
	return "TBL_MEDAL"
}

// TableID returns the table ID for this template
func (t *MedalTemplate) TableID() int {
	return 98
}

// GetID returns the record ID as int
func (t *MedalTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MedalTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MEDAL ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MedalTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"basic_tid": t.BasicTid,
		"clevel": t.Clevel,
		"desc": t.Desc,
		"exp": t.Exp,
		"icon_code": t.IconCode,
		"join_tid": t.JoinTid,
		"level": t.Level,
		"name": t.Name,
		"preflag": t.Preflag,
		"prop_type": t.PropType,
		"prop_val": t.PropVal,
		"q": t.Q,
		"sid": t.Sid,
		"up_exp": t.UpExp,
	}
}

