// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MeventMapTemplate represents TBL_MEVENT_MAP (table_id=128)
type MeventMapTemplate struct {
	ID int64 `json:"id" db:"id"`
	MeventID float64 `json:"mevent_id" db:"mevent_id"`
	Pos string `json:"pos" db:"pos"`
}

// TableName returns the table name for this template
func (t *MeventMapTemplate) TableName() string {
	return "TBL_MEVENT_MAP"
}

// TableID returns the table ID for this template
func (t *MeventMapTemplate) TableID() int {
	return 128
}

// GetID returns the record ID as int
func (t *MeventMapTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MeventMapTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MEVENT_MAP ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MeventMapTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"mevent_id": t.MeventID,
		"pos": t.Pos,
	}
}

