// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MeventTypeTemplate represents TBL_MEVENT_TYPE (table_id=129)
type MeventTypeTemplate struct {
	ID int64 `json:"id" db:"id"`
	Name string `json:"name" db:"name"`
	NPCID float64 `json:"npc_id" db:"npc_id"`
	Tip string `json:"tip" db:"tip"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *MeventTypeTemplate) TableName() string {
	return "TBL_MEVENT_TYPE"
}

// TableID returns the table ID for this template
func (t *MeventTypeTemplate) TableID() int {
	return 129
}

// GetID returns the record ID as int
func (t *MeventTypeTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MeventTypeTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MEVENT_TYPE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MeventTypeTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"name": t.Name,
		"npc_id": t.NPCID,
		"tip": t.Tip,
		"type": t.Type,
	}
}

