// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MineralTemplateTemplate represents TBL_MINERAL_TEMPLATE (table_id=83)
type MineralTemplateTemplate struct {
	ID int64 `json:"id" db:"id"`
	ActPnt float64 `json:"act_pnt" db:"act_pnt"`
	ColorCode float64 `json:"color_code" db:"color_code"`
	Description string `json:"description" db:"description"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	Money float64 `json:"money" db:"money"`
	Name string `json:"name" db:"name"`
	Num float64 `json:"num" db:"num"`
	ResCode1 float64 `json:"res_code1" db:"res_code1"`
	ResCode2 float64 `json:"res_code2" db:"res_code2"`
	Tid float64 `json:"tid" db:"tid"`
	Time float64 `json:"time" db:"time"`
}

// TableName returns the table name for this template
func (t *MineralTemplateTemplate) TableName() string {
	return "TBL_MINERAL_TEMPLATE"
}

// TableID returns the table ID for this template
func (t *MineralTemplateTemplate) TableID() int {
	return 83
}

// GetID returns the record ID as int
func (t *MineralTemplateTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MineralTemplateTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MINERAL_TEMPLATE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MineralTemplateTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"act_pnt": t.ActPnt,
		"color_code": t.ColorCode,
		"description": t.Description,
		"icon_code": t.IconCode,
		"money": t.Money,
		"name": t.Name,
		"num": t.Num,
		"res_code1": t.ResCode1,
		"res_code2": t.ResCode2,
		"tid": t.Tid,
		"time": t.Time,
	}
}

