// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MountTemplate represents TBL_MOUNT (table_id=96)
type MountTemplate struct {
	ID int64 `json:"id" db:"id"`
	AddRate float64 `json:"add_rate" db:"add_rate"`
	DebuffBasic float64 `json:"debuff_basic" db:"debuff_basic"`
	DebuffPer float64 `json:"debuff_per" db:"debuff_per"`
	DressID float64 `json:"dress_id" db:"dress_id"`
	Exp float64 `json:"exp" db:"exp"`
	ItemNum float64 `json:"item_num" db:"item_num"`
	Level float64 `json:"level" db:"level"`
	LifeBasic float64 `json:"life_basic" db:"life_basic"`
	LifePer float64 `json:"life_per" db:"life_per"`
	MagAttackBasic float64 `json:"mag_attack_basic" db:"mag_attack_basic"`
	MagAttackPer float64 `json:"mag_attack_per" db:"mag_attack_per"`
	MagDefenseBasic float64 `json:"mag_defense_basic" db:"mag_defense_basic"`
	MagDefensePer float64 `json:"mag_defense_per" db:"mag_defense_per"`
	MountLevLimit float64 `json:"mount_lev_limit" db:"mount_lev_limit"`
	PhyAttackBasic float64 `json:"phy_attack_basic" db:"phy_attack_basic"`
	PhyAttackPer float64 `json:"phy_attack_per" db:"phy_attack_per"`
	PhyDefenseBasic float64 `json:"phy_defense_basic" db:"phy_defense_basic"`
	PhyDefensePer float64 `json:"phy_defense_per" db:"phy_defense_per"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *MountTemplate) TableName() string {
	return "TBL_MOUNT"
}

// TableID returns the table ID for this template
func (t *MountTemplate) TableID() int {
	return 96
}

// GetID returns the record ID as int
func (t *MountTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MountTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MOUNT ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MountTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"add_rate": t.AddRate,
		"debuff_basic": t.DebuffBasic,
		"debuff_per": t.DebuffPer,
		"dress_id": t.DressID,
		"exp": t.Exp,
		"item_num": t.ItemNum,
		"level": t.Level,
		"life_basic": t.LifeBasic,
		"life_per": t.LifePer,
		"mag_attack_basic": t.MagAttackBasic,
		"mag_attack_per": t.MagAttackPer,
		"mag_defense_basic": t.MagDefenseBasic,
		"mag_defense_per": t.MagDefensePer,
		"mount_lev_limit": t.MountLevLimit,
		"phy_attack_basic": t.PhyAttackBasic,
		"phy_attack_per": t.PhyAttackPer,
		"phy_defense_basic": t.PhyDefenseBasic,
		"phy_defense_per": t.PhyDefensePer,
		"type": t.Type,
	}
}

