// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MountDressTemplate represents TBL_MOUNT_DRESS (table_id=97)
type MountDressTemplate struct {
	ID int64 `json:"id" db:"id"`
	DebuffBasic float64 `json:"debuff_basic" db:"debuff_basic"`
	DebuffPer float64 `json:"debuff_per" db:"debuff_per"`
	Description float64 `json:"description" db:"description"`
	EffectiveTime float64 `json:"effective_time" db:"effective_time"`
	Gold float64 `json:"gold" db:"gold"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	LifeBasic float64 `json:"life_basic" db:"life_basic"`
	LifePer float64 `json:"life_per" db:"life_per"`
	MagAttackBasic float64 `json:"mag_attack_basic" db:"mag_attack_basic"`
	MagAttackPer float64 `json:"mag_attack_per" db:"mag_attack_per"`
	MagDefenseBasic float64 `json:"mag_defense_basic" db:"mag_defense_basic"`
	MagDefensePer float64 `json:"mag_defense_per" db:"mag_defense_per"`
	Name string `json:"name" db:"name"`
	PhyAttackBasic float64 `json:"phy_attack_basic" db:"phy_attack_basic"`
	PhyAttackPer float64 `json:"phy_attack_per" db:"phy_attack_per"`
	PhyDefenseBasic float64 `json:"phy_defense_basic" db:"phy_defense_basic"`
	PhyDefensePer float64 `json:"phy_defense_per" db:"phy_defense_per"`
	ResCode float64 `json:"res_code" db:"res_code"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *MountDressTemplate) TableName() string {
	return "TBL_MOUNT_DRESS"
}

// TableID returns the table ID for this template
func (t *MountDressTemplate) TableID() int {
	return 97
}

// GetID returns the record ID as int
func (t *MountDressTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MountDressTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MOUNT_DRESS ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MountDressTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"debuff_basic": t.DebuffBasic,
		"debuff_per": t.DebuffPer,
		"description": t.Description,
		"effective_time": t.EffectiveTime,
		"gold": t.Gold,
		"icon_code": t.IconCode,
		"life_basic": t.LifeBasic,
		"life_per": t.LifePer,
		"mag_attack_basic": t.MagAttackBasic,
		"mag_attack_per": t.MagAttackPer,
		"mag_defense_basic": t.MagDefenseBasic,
		"mag_defense_per": t.MagDefensePer,
		"name": t.Name,
		"phy_attack_basic": t.PhyAttackBasic,
		"phy_attack_per": t.PhyAttackPer,
		"phy_defense_basic": t.PhyDefenseBasic,
		"phy_defense_per": t.PhyDefensePer,
		"res_code": t.ResCode,
		"type": t.Type,
	}
}

