// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MystreRecipeTemplate represents TBL_MYSTRE_RECIPE (table_id=122)
type MystreRecipeTemplate struct {
	ID int64 `json:"id" db:"id"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	Level float64 `json:"level" db:"level"`
	N1 float64 `json:"n1" db:"n1"`
	N2 float64 `json:"n2" db:"n2"`
	N3 float64 `json:"n3" db:"n3"`
	N4 float64 `json:"n4" db:"n4"`
	N5 float64 `json:"n5" db:"n5"`
	N6 float64 `json:"n6" db:"n6"`
	Name string `json:"name" db:"name"`
	Q1 float64 `json:"q1" db:"q1"`
	Q2 float64 `json:"q2" db:"q2"`
	Q3 float64 `json:"q3" db:"q3"`
	Q4 float64 `json:"q4" db:"q4"`
	Q5 float64 `json:"q5" db:"q5"`
	Q6 float64 `json:"q6" db:"q6"`
	St string `json:"st" db:"st"`
	T1 float64 `json:"t1" db:"t1"`
	T2 float64 `json:"t2" db:"t2"`
	T3 float64 `json:"t3" db:"t3"`
	T4 float64 `json:"t4" db:"t4"`
	T5 float64 `json:"t5" db:"t5"`
	T6 float64 `json:"t6" db:"t6"`
}

// TableName returns the table name for this template
func (t *MystreRecipeTemplate) TableName() string {
	return "TBL_MYSTRE_RECIPE"
}

// TableID returns the table ID for this template
func (t *MystreRecipeTemplate) TableID() int {
	return 122
}

// GetID returns the record ID as int
func (t *MystreRecipeTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MystreRecipeTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MYSTRE_RECIPE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MystreRecipeTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"icon_code": t.IconCode,
		"level": t.Level,
		"n1": t.N1,
		"n2": t.N2,
		"n3": t.N3,
		"n4": t.N4,
		"n5": t.N5,
		"n6": t.N6,
		"name": t.Name,
		"q1": t.Q1,
		"q2": t.Q2,
		"q3": t.Q3,
		"q4": t.Q4,
		"q5": t.Q5,
		"q6": t.Q6,
		"st": t.St,
		"t1": t.T1,
		"t2": t.T2,
		"t3": t.T3,
		"t4": t.T4,
		"t5": t.T5,
		"t6": t.T6,
	}
}

