// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MystreTemplate represents TBL_MYSTRE (table_id=123)
type MystreTemplate struct {
	ID int64 `json:"id" db:"id"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	Kind float64 `json:"kind" db:"kind"`
	Level float64 `json:"level" db:"level"`
	MysSil float64 `json:"mys_sil" db:"mys_sil"`
	Name string `json:"name" db:"name"`
	Per float64 `json:"per" db:"per"`
	PropNum float64 `json:"prop_num" db:"prop_num"`
	PropType float64 `json:"prop_type" db:"prop_type"`
	Star float64 `json:"star" db:"star"`
}

// TableName returns the table name for this template
func (t *MystreTemplate) TableName() string {
	return "TBL_MYSTRE"
}

// TableID returns the table ID for this template
func (t *MystreTemplate) TableID() int {
	return 123
}

// GetID returns the record ID as int
func (t *MystreTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MystreTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MYSTRE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MystreTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"icon_code": t.IconCode,
		"kind": t.Kind,
		"level": t.Level,
		"mys_sil": t.MysSil,
		"name": t.Name,
		"per": t.Per,
		"prop_num": t.PropNum,
		"prop_type": t.PropType,
		"star": t.Star,
	}
}

