// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MytcDetailTemplate represents TBL_MYTC_DETAIL (table_id=143)
type MytcDetailTemplate struct {
	ID int64 `json:"id" db:"id"`
	C1 string `json:"c1" db:"c1"`
	C2 string `json:"c2" db:"c2"`
	C3 string `json:"c3" db:"c3"`
	C4 string `json:"c4" db:"c4"`
	C5 string `json:"c5" db:"c5"`
	C6 string `json:"c6" db:"c6"`
	Cost float64 `json:"cost" db:"cost"`
	Lev float64 `json:"lev" db:"lev"`
	Tid float64 `json:"tid" db:"tid"`
}

// TableName returns the table name for this template
func (t *MytcDetailTemplate) TableName() string {
	return "TBL_MYTC_DETAIL"
}

// TableID returns the table ID for this template
func (t *MytcDetailTemplate) TableID() int {
	return 143
}

// GetID returns the record ID as int
func (t *MytcDetailTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MytcDetailTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MYTC_DETAIL ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MytcDetailTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"c1": t.C1,
		"c2": t.C2,
		"c3": t.C3,
		"c4": t.C4,
		"c5": t.C5,
		"c6": t.C6,
		"cost": t.Cost,
		"lev": t.Lev,
		"tid": t.Tid,
	}
}

