// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// MytcSuitTemplate represents TBL_MYTC_SUIT (table_id=142)
type MytcSuitTemplate struct {
	ID int64 `json:"id" db:"id"`
	M1 float64 `json:"m1" db:"m1"`
	M2 float64 `json:"m2" db:"m2"`
	M3 float64 `json:"m3" db:"m3"`
	Name string `json:"name" db:"name"`
}

// TableName returns the table name for this template
func (t *MytcSuitTemplate) TableName() string {
	return "TBL_MYTC_SUIT"
}

// TableID returns the table ID for this template
func (t *MytcSuitTemplate) TableID() int {
	return 142
}

// GetID returns the record ID as int
func (t *MytcSuitTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *MytcSuitTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_MYTC_SUIT ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *MytcSuitTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"m1": t.M1,
		"m2": t.M2,
		"m3": t.M3,
		"name": t.Name,
	}
}

