// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// NameLibTemplate represents TBL_NAME_LIB (table_id=80)
type NameLibTemplate struct {
	ID int64 `json:"id" db:"id"`
	Name string `json:"name" db:"name"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *NameLibTemplate) TableName() string {
	return "TBL_NAME_LIB"
}

// TableID returns the table ID for this template
func (t *NameLibTemplate) TableID() int {
	return 80
}

// GetID returns the record ID as int
func (t *NameLibTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *NameLibTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_NAME_LIB ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *NameLibTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"name": t.Name,
		"type": t.Type,
	}
}

