// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
	"strconv"
	"strings"
)

// NpcTemplate represents TBL_NPC (table_id=35)
type NpcTemplate struct {
	ID int64 `json:"id" db:"id"`
	At string `json:"at" db:"at"`
	BrightCode float64 `json:"bright_code" db:"bright_code"`
	ClassID float64 `json:"class_id" db:"class_id"`
	ColorCode float64 `json:"color_code" db:"color_code"`
	Fd float64 `json:"fd" db:"fd"`
	FuncInfo string `json:"func_info" db:"func_info"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	Item string `json:"item" db:"item"`
	Layer float64 `json:"layer" db:"layer"`
	Lk float64 `json:"lk" db:"lk"`
	Lv float64 `json:"lv" db:"lv"`
	MiniMap float64 `json:"mini_map" db:"mini_map"`
	Mirror float64 `json:"mirror" db:"mirror"`
	Name string `json:"name" db:"name"`
	NewsOff float64 `json:"news_off" db:"news_off"`
	NewsOn float64 `json:"news_on" db:"news_on"`
	Num float64 `json:"num" db:"num"`
	OnServiceText string `json:"on_service_text" db:"on_service_text"`
	PosDir float64 `json:"pos_dir" db:"pos_dir"`
	PosMapID float64 `json:"pos_map_id" db:"pos_map_id"`
	PosX float64 `json:"pos_x" db:"pos_x"`
	PosY float64 `json:"pos_y" db:"pos_y"`
	Qid string `json:"qid" db:"qid"`
	RandOff float64 `json:"rand_off" db:"rand_off"`
	ResCode float64 `json:"res_code" db:"res_code"`
	Rf float64 `json:"rf" db:"rf"`
	ScriptOff string `json:"script_off" db:"script_off"`
	ShopID float64 `json:"shop_id" db:"shop_id"`
	Skill float64 `json:"skill" db:"skill"`
	SubType string `json:"sub_type" db:"sub_type"`
	Together float64 `json:"together" db:"together"`
	Type float64 `json:"type" db:"type"`
	V float64 `json:"v" db:"v"`
}

// TableName returns the table name for this template
func (t *NpcTemplate) TableName() string {
	return "TBL_NPC"
}

// TableID returns the table ID for this template
func (t *NpcTemplate) TableID() int {
	return 35
}

// GetID returns the record ID as int
func (t *NpcTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *NpcTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_NPC ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *NpcTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"at": t.At,
		"bright_code": t.BrightCode,
		"class_id": t.ClassID,
		"color_code": t.ColorCode,
		"fd": t.Fd,
		"func_info": t.FuncInfo,
		"icon_code": t.IconCode,
		"item": t.Item,
		"layer": t.Layer,
		"lk": t.Lk,
		"lv": t.Lv,
		"mini_map": t.MiniMap,
		"mirror": t.Mirror,
		"name": t.Name,
		"news_off": t.NewsOff,
		"news_on": t.NewsOn,
		"num": t.Num,
		"on_service_text": t.OnServiceText,
		"pos_dir": t.PosDir,
		"pos_map_id": t.PosMapID,
		"pos_x": t.PosX,
		"pos_y": t.PosY,
		"qid": t.Qid,
		"rand_off": t.RandOff,
		"res_code": t.ResCode,
		"rf": t.Rf,
		"script_off": t.ScriptOff,
		"shop_id": t.ShopID,
		"skill": t.Skill,
		"sub_type": t.SubType,
		"together": t.Together,
		"type": t.Type,
		"v": t.V,
	}
}

// ParsePipeDelimitedInts parses a pipe-delimited string like "|1|2|3|" into []int
func (t *NpcTemplate) ParsePipeDelimitedInts(s string) []int {
	if s == "" || s == "|" {
		return nil
	}
	s = strings.Trim(s, "|")
	parts := strings.Split(s, "|")
	result := make([]int, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue
		}
		if n, err := strconv.Atoi(p); err == nil {
			result = append(result, n)
		}
	}
	return result
}
