// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// NpcSkillTemplate represents TBL_NPC_SKILL (table_id=38)
type NpcSkillTemplate struct {
	ID int64 `json:"id" db:"id"`
	Nid float64 `json:"nid" db:"nid"`
	Position float64 `json:"position" db:"position"`
	Sid float64 `json:"sid" db:"sid"`
}

// TableName returns the table name for this template
func (t *NpcSkillTemplate) TableName() string {
	return "TBL_NPC_SKILL"
}

// TableID returns the table ID for this template
func (t *NpcSkillTemplate) TableID() int {
	return 38
}

// GetID returns the record ID as int
func (t *NpcSkillTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *NpcSkillTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_NPC_SKILL ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *NpcSkillTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"nid": t.Nid,
		"position": t.Position,
		"sid": t.Sid,
	}
}

