// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// NpcCreatureTemplate represents TBL_NPC_CREATURE (table_id=36)
type NpcCreatureTemplate struct {
	ID int64 `json:"id" db:"id"`
	BossFlag float64 `json:"boss_flag" db:"boss_flag"`
	Cid float64 `json:"cid" db:"cid"`
	EndRate float64 `json:"end_rate" db:"end_rate"`
	Exp float64 `json:"exp" db:"exp"`
	ExpMulti float64 `json:"exp_multi" db:"exp_multi"`
	ExpSet float64 `json:"exp_set" db:"exp_set"`
	Level float64 `json:"level" db:"level"`
	Nid float64 `json:"nid" db:"nid"`
	QLevel float64 `json:"q_level" db:"q_level"`
	StartRate float64 `json:"start_rate" db:"start_rate"`
	UniqueFlag float64 `json:"unique_flag" db:"unique_flag"`
}

// TableName returns the table name for this template
func (t *NpcCreatureTemplate) TableName() string {
	return "TBL_NPC_CREATURE"
}

// TableID returns the table ID for this template
func (t *NpcCreatureTemplate) TableID() int {
	return 36
}

// GetID returns the record ID as int
func (t *NpcCreatureTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *NpcCreatureTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_NPC_CREATURE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *NpcCreatureTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"boss_flag": t.BossFlag,
		"cid": t.Cid,
		"end_rate": t.EndRate,
		"exp": t.Exp,
		"exp_multi": t.ExpMulti,
		"exp_set": t.ExpSet,
		"level": t.Level,
		"nid": t.Nid,
		"q_level": t.QLevel,
		"start_rate": t.StartRate,
		"unique_flag": t.UniqueFlag,
	}
}

