// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// PetSoulTemplate represents TBL_PET_SOUL (table_id=94)
type PetSoulTemplate struct {
	ID int64 `json:"id" db:"id"`
	Chip float64 `json:"chip" db:"chip"`
	Color float64 `json:"color" db:"color"`
	Desc string `json:"desc" db:"desc"`
	Exp float64 `json:"exp" db:"exp"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	Level float64 `json:"level" db:"level"`
	Name string `json:"name" db:"name"`
	Price float64 `json:"price" db:"price"`
	PropType float64 `json:"prop_type" db:"prop_type"`
	PropVal float64 `json:"prop_val" db:"prop_val"`
	ReqChip float64 `json:"req_chip" db:"req_chip"`
	Type float64 `json:"type" db:"type"`
	UpExp float64 `json:"up_exp" db:"up_exp"`
}

// TableName returns the table name for this template
func (t *PetSoulTemplate) TableName() string {
	return "TBL_PET_SOUL"
}

// TableID returns the table ID for this template
func (t *PetSoulTemplate) TableID() int {
	return 94
}

// GetID returns the record ID as int
func (t *PetSoulTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *PetSoulTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_PET_SOUL ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *PetSoulTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"chip": t.Chip,
		"color": t.Color,
		"desc": t.Desc,
		"exp": t.Exp,
		"icon_code": t.IconCode,
		"level": t.Level,
		"name": t.Name,
		"price": t.Price,
		"prop_type": t.PropType,
		"prop_val": t.PropVal,
		"req_chip": t.ReqChip,
		"type": t.Type,
		"up_exp": t.UpExp,
	}
}

