// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// PetTalentTemplate represents TBL_PET_TALENT (table_id=101)
type PetTalentTemplate struct {
	ID int64 `json:"id" db:"id"`
	BasicTid float64 `json:"basic_tid" db:"basic_tid"`
	Desc string `json:"desc" db:"desc"`
	Exp float64 `json:"exp" db:"exp"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	Lv float64 `json:"lv" db:"lv"`
	Name string `json:"name" db:"name"`
	P float64 `json:"p" db:"p"`
	Preflag float64 `json:"preflag" db:"preflag"`
	PropType float64 `json:"prop_type" db:"prop_type"`
	PropVal float64 `json:"prop_val" db:"prop_val"`
	Rlv float64 `json:"rlv" db:"rlv"`
	Sid float64 `json:"sid" db:"sid"`
	UpExp float64 `json:"up_exp" db:"up_exp"`
}

// TableName returns the table name for this template
func (t *PetTalentTemplate) TableName() string {
	return "TBL_PET_TALENT"
}

// TableID returns the table ID for this template
func (t *PetTalentTemplate) TableID() int {
	return 101
}

// GetID returns the record ID as int
func (t *PetTalentTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *PetTalentTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_PET_TALENT ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *PetTalentTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"basic_tid": t.BasicTid,
		"desc": t.Desc,
		"exp": t.Exp,
		"icon_code": t.IconCode,
		"lv": t.Lv,
		"name": t.Name,
		"p": t.P,
		"preflag": t.Preflag,
		"prop_type": t.PropType,
		"prop_val": t.PropVal,
		"rlv": t.Rlv,
		"sid": t.Sid,
		"up_exp": t.UpExp,
	}
}

