// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// PetContractTemplate represents TBL_PET_CONTRACT (table_id=117)
type PetContractTemplate struct {
	ID int64 `json:"id" db:"id"`
	ExtraNum1 float64 `json:"extra_num1" db:"extra_num1"`
	ExtraNum2 float64 `json:"extra_num2" db:"extra_num2"`
	ExtraNum3 float64 `json:"extra_num3" db:"extra_num3"`
	ExtraNum4 float64 `json:"extra_num4" db:"extra_num4"`
	Prop1 float64 `json:"prop1" db:"prop1"`
	Prop2 float64 `json:"prop2" db:"prop2"`
	Prop3 float64 `json:"prop3" db:"prop3"`
	Prop4 float64 `json:"prop4" db:"prop4"`
	PropNum1 float64 `json:"prop_num1" db:"prop_num1"`
	PropNum2 float64 `json:"prop_num2" db:"prop_num2"`
	PropNum3 float64 `json:"prop_num3" db:"prop_num3"`
	PropNum4 float64 `json:"prop_num4" db:"prop_num4"`
	ReqExp float64 `json:"req_exp" db:"req_exp"`
	ReqNum float64 `json:"req_num" db:"req_num"`
}

// TableName returns the table name for this template
func (t *PetContractTemplate) TableName() string {
	return "TBL_PET_CONTRACT"
}

// TableID returns the table ID for this template
func (t *PetContractTemplate) TableID() int {
	return 117
}

// GetID returns the record ID as int
func (t *PetContractTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *PetContractTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_PET_CONTRACT ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *PetContractTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"extra_num1": t.ExtraNum1,
		"extra_num2": t.ExtraNum2,
		"extra_num3": t.ExtraNum3,
		"extra_num4": t.ExtraNum4,
		"prop1": t.Prop1,
		"prop2": t.Prop2,
		"prop3": t.Prop3,
		"prop4": t.Prop4,
		"prop_num1": t.PropNum1,
		"prop_num2": t.PropNum2,
		"prop_num3": t.PropNum3,
		"prop_num4": t.PropNum4,
		"req_exp": t.ReqExp,
		"req_num": t.ReqNum,
	}
}

