// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// PetStoneTemplate represents TBL_PET_STONE (table_id=136)
type PetStoneTemplate struct {
	ID int64 `json:"id" db:"id"`
	CostSil float64 `json:"cost_sil" db:"cost_sil"`
	EnergyFlag float64 `json:"energy_flag" db:"energy_flag"`
	EnergyID float64 `json:"energy_id" db:"energy_id"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	Level float64 `json:"level" db:"level"`
	Name string `json:"name" db:"name"`
	NextID float64 `json:"next_id" db:"next_id"`
	PropNum float64 `json:"prop_num" db:"prop_num"`
	PropType float64 `json:"prop_type" db:"prop_type"`
	ResolveNum float64 `json:"resolve_num" db:"resolve_num"`
}

// TableName returns the table name for this template
func (t *PetStoneTemplate) TableName() string {
	return "TBL_PET_STONE"
}

// TableID returns the table ID for this template
func (t *PetStoneTemplate) TableID() int {
	return 136
}

// GetID returns the record ID as int
func (t *PetStoneTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *PetStoneTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_PET_STONE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *PetStoneTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"cost_sil": t.CostSil,
		"energy_flag": t.EnergyFlag,
		"energy_id": t.EnergyID,
		"icon_code": t.IconCode,
		"level": t.Level,
		"name": t.Name,
		"next_id": t.NextID,
		"prop_num": t.PropNum,
		"prop_type": t.PropType,
		"resolve_num": t.ResolveNum,
	}
}

