// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// PetGuardTemplate represents TBL_PET_GUARD (table_id=135)
type PetGuardTemplate struct {
	ID int64 `json:"id" db:"id"`
	CostType float64 `json:"cost_type" db:"cost_type"`
	Desc float64 `json:"desc" db:"desc"`
	Gold float64 `json:"gold" db:"gold"`
	Lev float64 `json:"lev" db:"lev"`
	Num float64 `json:"num" db:"num"`
	Prop1 float64 `json:"prop1" db:"prop1"`
	Prop2 float64 `json:"prop2" db:"prop2"`
	Prop3 float64 `json:"prop3" db:"prop3"`
	Prop4 float64 `json:"prop4" db:"prop4"`
	PropVal1 float64 `json:"prop_val1" db:"prop_val1"`
	PropVal2 float64 `json:"prop_val2" db:"prop_val2"`
	PropVal3 float64 `json:"prop_val3" db:"prop_val3"`
	PropVal4 float64 `json:"prop_val4" db:"prop_val4"`
	Sid float64 `json:"sid" db:"sid"`
}

// TableName returns the table name for this template
func (t *PetGuardTemplate) TableName() string {
	return "TBL_PET_GUARD"
}

// TableID returns the table ID for this template
func (t *PetGuardTemplate) TableID() int {
	return 135
}

// GetID returns the record ID as int
func (t *PetGuardTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *PetGuardTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_PET_GUARD ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *PetGuardTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"cost_type": t.CostType,
		"desc": t.Desc,
		"gold": t.Gold,
		"lev": t.Lev,
		"num": t.Num,
		"prop1": t.Prop1,
		"prop2": t.Prop2,
		"prop3": t.Prop3,
		"prop4": t.Prop4,
		"prop_val1": t.PropVal1,
		"prop_val2": t.PropVal2,
		"prop_val3": t.PropVal3,
		"prop_val4": t.PropVal4,
		"sid": t.Sid,
	}
}

