// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// PlanTemplate represents TBL_PLAN (table_id=42)
type PlanTemplate struct {
	ID int64 `json:"id" db:"id"`
	B float64 `json:"b" db:"b"`
	Ii float64 `json:"ii" db:"ii"`
	N float64 `json:"n" db:"n"`
	P float64 `json:"p" db:"p"`
	Q float64 `json:"q" db:"q"`
	Qid float64 `json:"qid" db:"qid"`
	R float64 `json:"r" db:"r"`
	St string `json:"st" db:"st"`
	T float64 `json:"t" db:"t"`
	Ti float64 `json:"ti" db:"ti"`
}

// TableName returns the table name for this template
func (t *PlanTemplate) TableName() string {
	return "TBL_PLAN"
}

// TableID returns the table ID for this template
func (t *PlanTemplate) TableID() int {
	return 42
}

// GetID returns the record ID as int
func (t *PlanTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *PlanTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_PLAN ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *PlanTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"b": t.B,
		"ii": t.Ii,
		"n": t.N,
		"p": t.P,
		"q": t.Q,
		"qid": t.Qid,
		"r": t.R,
		"st": t.St,
		"t": t.T,
		"ti": t.Ti,
	}
}

