// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// PmRightTemplate represents TBL_PM_RIGHT (table_id=95)
type PmRightTemplate struct {
	ID int64 `json:"id" db:"id"`
	CountConfig string `json:"count_config" db:"count_config"`
	Desc string `json:"desc" db:"desc"`
	Desc2 string `json:"desc2" db:"desc2"`
	SortIndex float64 `json:"sort_index" db:"sort_index"`
	Type float64 `json:"type" db:"type"`
	Value1 float64 `json:"value1" db:"value1"`
	Value2 float64 `json:"value2" db:"value2"`
	Value3 float64 `json:"value3" db:"value3"`
	Value4 float64 `json:"value4" db:"value4"`
	Value5 float64 `json:"value5" db:"value5"`
	Value6 float64 `json:"value6" db:"value6"`
	Value7 float64 `json:"value7" db:"value7"`
	Value8 float64 `json:"value8" db:"value8"`
	Value9 float64 `json:"value9" db:"value9"`
	Vip1 float64 `json:"vip1" db:"vip1"`
	Vip2 float64 `json:"vip2" db:"vip2"`
	Vip3 float64 `json:"vip3" db:"vip3"`
	Vip4 float64 `json:"vip4" db:"vip4"`
	Vip5 float64 `json:"vip5" db:"vip5"`
	Vip6 float64 `json:"vip6" db:"vip6"`
	Vip7 float64 `json:"vip7" db:"vip7"`
	Vip8 float64 `json:"vip8" db:"vip8"`
	Vip9 float64 `json:"vip9" db:"vip9"`
}

// TableName returns the table name for this template
func (t *PmRightTemplate) TableName() string {
	return "TBL_PM_RIGHT"
}

// TableID returns the table ID for this template
func (t *PmRightTemplate) TableID() int {
	return 95
}

// GetID returns the record ID as int
func (t *PmRightTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *PmRightTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_PM_RIGHT ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *PmRightTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"count_config": t.CountConfig,
		"desc": t.Desc,
		"desc2": t.Desc2,
		"sort_index": t.SortIndex,
		"type": t.Type,
		"value1": t.Value1,
		"value2": t.Value2,
		"value3": t.Value3,
		"value4": t.Value4,
		"value5": t.Value5,
		"value6": t.Value6,
		"value7": t.Value7,
		"value8": t.Value8,
		"value9": t.Value9,
		"vip1": t.Vip1,
		"vip2": t.Vip2,
		"vip3": t.Vip3,
		"vip4": t.Vip4,
		"vip5": t.Vip5,
		"vip6": t.Vip6,
		"vip7": t.Vip7,
		"vip8": t.Vip8,
		"vip9": t.Vip9,
	}
}

