// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// PrsTreeTemplate represents TBL_PRS_TREE (table_id=125)
type PrsTreeTemplate struct {
	ID int64 `json:"id" db:"id"`
	CostStone float64 `json:"cost_stone" db:"cost_stone"`
	Level float64 `json:"level" db:"level"`
	NextID float64 `json:"next_id" db:"next_id"`
	PN1 float64 `json:"p_n1" db:"p_n1"`
	PN2 float64 `json:"p_n2" db:"p_n2"`
	PN3 float64 `json:"p_n3" db:"p_n3"`
	PN4 float64 `json:"p_n4" db:"p_n4"`
	PN5 float64 `json:"p_n5" db:"p_n5"`
	PN6 float64 `json:"p_n6" db:"p_n6"`
	PN7 float64 `json:"p_n7" db:"p_n7"`
	PN8 float64 `json:"p_n8" db:"p_n8"`
	PT1 float64 `json:"p_t1" db:"p_t1"`
	PT2 float64 `json:"p_t2" db:"p_t2"`
	PT3 float64 `json:"p_t3" db:"p_t3"`
	PT4 float64 `json:"p_t4" db:"p_t4"`
	PT5 float64 `json:"p_t5" db:"p_t5"`
	PT6 float64 `json:"p_t6" db:"p_t6"`
	PT7 float64 `json:"p_t7" db:"p_t7"`
	PT8 float64 `json:"p_t8" db:"p_t8"`
}

// TableName returns the table name for this template
func (t *PrsTreeTemplate) TableName() string {
	return "TBL_PRS_TREE"
}

// TableID returns the table ID for this template
func (t *PrsTreeTemplate) TableID() int {
	return 125
}

// GetID returns the record ID as int
func (t *PrsTreeTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *PrsTreeTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_PRS_TREE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *PrsTreeTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"cost_stone": t.CostStone,
		"level": t.Level,
		"next_id": t.NextID,
		"p_n1": t.PN1,
		"p_n2": t.PN2,
		"p_n3": t.PN3,
		"p_n4": t.PN4,
		"p_n5": t.PN5,
		"p_n6": t.PN6,
		"p_n7": t.PN7,
		"p_n8": t.PN8,
		"p_t1": t.PT1,
		"p_t2": t.PT2,
		"p_t3": t.PT3,
		"p_t4": t.PT4,
		"p_t5": t.PT5,
		"p_t6": t.PT6,
		"p_t7": t.PT7,
		"p_t8": t.PT8,
	}
}

