// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// PrsShowTemplate represents TBL_PRS_SHOW (table_id=126)
type PrsShowTemplate struct {
	ID int64 `json:"id" db:"id"`
	LimitTime float64 `json:"limit_time" db:"limit_time"`
	LimitType float64 `json:"limit_type" db:"limit_type"`
	Name string `json:"name" db:"name"`
	NeedChipID float64 `json:"need_chip_id" db:"need_chip_id"`
	NeedNum float64 `json:"need_num" db:"need_num"`
	PN1 float64 `json:"p_n1" db:"p_n1"`
	PN2 float64 `json:"p_n2" db:"p_n2"`
	PN3 float64 `json:"p_n3" db:"p_n3"`
	PN4 float64 `json:"p_n4" db:"p_n4"`
	PN5 float64 `json:"p_n5" db:"p_n5"`
	PN6 float64 `json:"p_n6" db:"p_n6"`
	PN7 float64 `json:"p_n7" db:"p_n7"`
	PN8 float64 `json:"p_n8" db:"p_n8"`
	PT1 float64 `json:"p_t1" db:"p_t1"`
	PT2 float64 `json:"p_t2" db:"p_t2"`
	PT3 float64 `json:"p_t3" db:"p_t3"`
	PT4 float64 `json:"p_t4" db:"p_t4"`
	PT5 float64 `json:"p_t5" db:"p_t5"`
	PT6 float64 `json:"p_t6" db:"p_t6"`
	PT7 float64 `json:"p_t7" db:"p_t7"`
	PT8 float64 `json:"p_t8" db:"p_t8"`
	Position float64 `json:"position" db:"position"`
	ResCode float64 `json:"res_code" db:"res_code"`
	Tab float64 `json:"tab" db:"tab"`
}

// TableName returns the table name for this template
func (t *PrsShowTemplate) TableName() string {
	return "TBL_PRS_SHOW"
}

// TableID returns the table ID for this template
func (t *PrsShowTemplate) TableID() int {
	return 126
}

// GetID returns the record ID as int
func (t *PrsShowTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *PrsShowTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_PRS_SHOW ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *PrsShowTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"limit_time": t.LimitTime,
		"limit_type": t.LimitType,
		"name": t.Name,
		"need_chip_id": t.NeedChipID,
		"need_num": t.NeedNum,
		"p_n1": t.PN1,
		"p_n2": t.PN2,
		"p_n3": t.PN3,
		"p_n4": t.PN4,
		"p_n5": t.PN5,
		"p_n6": t.PN6,
		"p_n7": t.PN7,
		"p_n8": t.PN8,
		"p_t1": t.PT1,
		"p_t2": t.PT2,
		"p_t3": t.PT3,
		"p_t4": t.PT4,
		"p_t5": t.PT5,
		"p_t6": t.PT6,
		"p_t7": t.PT7,
		"p_t8": t.PT8,
		"position": t.Position,
		"res_code": t.ResCode,
		"tab": t.Tab,
	}
}

