// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// PrsChipTemplate represents TBL_PRS_CHIP (table_id=127)
type PrsChipTemplate struct {
	ID int64 `json:"id" db:"id"`
	CostCrystal float64 `json:"cost_crystal" db:"cost_crystal"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	Name string `json:"name" db:"name"`
	Position float64 `json:"position" db:"position"`
	ShowID float64 `json:"show_id" db:"show_id"`
}

// TableName returns the table name for this template
func (t *PrsChipTemplate) TableName() string {
	return "TBL_PRS_CHIP"
}

// TableID returns the table ID for this template
func (t *PrsChipTemplate) TableID() int {
	return 127
}

// GetID returns the record ID as int
func (t *PrsChipTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *PrsChipTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_PRS_CHIP ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *PrsChipTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"cost_crystal": t.CostCrystal,
		"icon_code": t.IconCode,
		"name": t.Name,
		"position": t.Position,
		"show_id": t.ShowID,
	}
}

