// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// QuestAwardTemplate represents TBL_QUEST_AWARD (table_id=46)
type QuestAwardTemplate struct {
	ID int64 `json:"id" db:"id"`
	B float64 `json:"b" db:"b"`
	ItemID float64 `json:"item_id" db:"item_id"`
	Kind float64 `json:"kind" db:"kind"`
	Num float64 `json:"num" db:"num"`
	Q float64 `json:"q" db:"q"`
	Qid float64 `json:"qid" db:"qid"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *QuestAwardTemplate) TableName() string {
	return "TBL_QUEST_AWARD"
}

// TableID returns the table ID for this template
func (t *QuestAwardTemplate) TableID() int {
	return 46
}

// GetID returns the record ID as int
func (t *QuestAwardTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *QuestAwardTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_QUEST_AWARD ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *QuestAwardTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"b": t.B,
		"item_id": t.ItemID,
		"kind": t.Kind,
		"num": t.Num,
		"q": t.Q,
		"qid": t.Qid,
		"type": t.Type,
	}
}

