// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// QuestLoopTemplate represents TBL_QUEST_LOOP (table_id=58)
type QuestLoopTemplate struct {
	ID int64 `json:"id" db:"id"`
	Info string `json:"info" db:"info"`
	MaxLevel float64 `json:"max_level" db:"max_level"`
	MinLevel float64 `json:"min_level" db:"min_level"`
	Name string `json:"name" db:"name"`
	Nid float64 `json:"nid" db:"nid"`
	Num float64 `json:"num" db:"num"`
	Refresh float64 `json:"refresh" db:"refresh"`
	ScriptGet string `json:"script_get" db:"script_get"`
	ScriptGiveUp string `json:"script_give_up" db:"script_give_up"`
	Team float64 `json:"team" db:"team"`
}

// TableName returns the table name for this template
func (t *QuestLoopTemplate) TableName() string {
	return "TBL_QUEST_LOOP"
}

// TableID returns the table ID for this template
func (t *QuestLoopTemplate) TableID() int {
	return 58
}

// GetID returns the record ID as int
func (t *QuestLoopTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *QuestLoopTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_QUEST_LOOP ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *QuestLoopTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"info": t.Info,
		"max_level": t.MaxLevel,
		"min_level": t.MinLevel,
		"name": t.Name,
		"nid": t.Nid,
		"num": t.Num,
		"refresh": t.Refresh,
		"script_get": t.ScriptGet,
		"script_give_up": t.ScriptGiveUp,
		"team": t.Team,
	}
}

