// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// QuestRequireTemplate represents TBL_QUEST_REQUIRE (table_id=47)
type QuestRequireTemplate struct {
	ID int64 `json:"id" db:"id"`
	ItemID float64 `json:"item_id" db:"item_id"`
	Kind float64 `json:"kind" db:"kind"`
	Num float64 `json:"num" db:"num"`
	Q float64 `json:"q" db:"q"`
	Qid float64 `json:"qid" db:"qid"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *QuestRequireTemplate) TableName() string {
	return "TBL_QUEST_REQUIRE"
}

// TableID returns the table ID for this template
func (t *QuestRequireTemplate) TableID() int {
	return 47
}

// GetID returns the record ID as int
func (t *QuestRequireTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *QuestRequireTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_QUEST_REQUIRE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *QuestRequireTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"item_id": t.ItemID,
		"kind": t.Kind,
		"num": t.Num,
		"q": t.Q,
		"qid": t.Qid,
		"type": t.Type,
	}
}

