// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
	"strconv"
	"strings"
)

// QuestTemplate represents TBL_QUEST (table_id=45)
type QuestTemplate struct {
	ID int64 `json:"id" db:"id"`
	AScriptText string `json:"a_script_text" db:"a_script_text"`
	At float64 `json:"at" db:"at"`
	AwardExpRe float64 `json:"award_exp_re" db:"award_exp_re"`
	Color float64 `json:"color" db:"color"`
	CompleteText string `json:"complete_text" db:"complete_text"`
	FinishNPC float64 `json:"finish_npc" db:"finish_npc"`
	Gender float64 `json:"gender" db:"gender"`
	Info string `json:"info" db:"info"`
	IsRebirth float64 `json:"is_rebirth" db:"is_rebirth"`
	Lm float64 `json:"lm" db:"lm"`
	MaxLevel float64 `json:"max_level" db:"max_level"`
	MinLevel float64 `json:"min_level" db:"min_level"`
	MoneyNum float64 `json:"money_num" db:"money_num"`
	MoneyType float64 `json:"money_type" db:"money_type"`
	Name string `json:"name" db:"name"`
	PreQuestType float64 `json:"pre_quest_type" db:"pre_quest_type"`
	Qtest string `json:"qtest" db:"qtest"`
	ReqClass string `json:"req_class" db:"req_class"`
	Rn float64 `json:"rn" db:"rn"`
	Rt float64 `json:"rt" db:"rt"`
	ScriptGiveUp string `json:"script_give_up" db:"script_give_up"`
	StartNPC float64 `json:"start_npc" db:"start_npc"`
	StartText string `json:"start_text" db:"start_text"`
	SubType string `json:"sub_type" db:"sub_type"`
	Type float64 `json:"type" db:"type"`
	StartGrantItem *int `json:"start_grant_item,omitempty" db:"start_grant_item"`
	StartGrantQty  *int `json:"start_grant_qty,omitempty" db:"start_grant_qty"`
}

// TableName returns the table name for this template
func (t *QuestTemplate) TableName() string {
	return "TBL_QUEST"
}

// TableID returns the table ID for this template
func (t *QuestTemplate) TableID() int {
	return 45
}

// GetID returns the record ID as int
func (t *QuestTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *QuestTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_QUEST ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *QuestTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"a_script_text": t.AScriptText,
		"at": t.At,
		"award_exp_re": t.AwardExpRe,
		"color": t.Color,
		"complete_text": t.CompleteText,
		"finish_npc": t.FinishNPC,
		"gender": t.Gender,
		"info": t.Info,
		"is_rebirth": t.IsRebirth,
		"lm": t.Lm,
		"max_level": t.MaxLevel,
		"min_level": t.MinLevel,
		"money_num": t.MoneyNum,
		"money_type": t.MoneyType,
		"name": t.Name,
		"pre_quest_type": t.PreQuestType,
		"qtest": t.Qtest,
		"req_class": t.ReqClass,
		"rn": t.Rn,
		"rt": t.Rt,
		"script_give_up": t.ScriptGiveUp,
		"start_npc": t.StartNPC,
		"start_text": t.StartText,
		"sub_type": t.SubType,
		"type": t.Type,
	}
}

// ParsePipeDelimitedInts parses a pipe-delimited string like "|1|2|3|" into []int
func (t *QuestTemplate) ParsePipeDelimitedInts(s string) []int {
	if s == "" || s == "|" {
		return nil
	}
	s = strings.Trim(s, "|")
	parts := strings.Split(s, "|")
	result := make([]int, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue
		}
		if n, err := strconv.Atoi(p); err == nil {
			result = append(result, n)
		}
	}
	return result
}
