// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// RecipePlanTemplate represents TBL_RECIPE_PLAN (table_id=106)
type RecipePlanTemplate struct {
	ID int64 `json:"id" db:"id"`
	Num float64 `json:"num" db:"num"`
	P float64 `json:"p" db:"p"`
	Rate float64 `json:"rate" db:"rate"`
	RecipeID float64 `json:"recipe_id" db:"recipe_id"`
	St float64 `json:"st" db:"st"`
}

// TableName returns the table name for this template
func (t *RecipePlanTemplate) TableName() string {
	return "TBL_RECIPE_PLAN"
}

// TableID returns the table ID for this template
func (t *RecipePlanTemplate) TableID() int {
	return 106
}

// GetID returns the record ID as int
func (t *RecipePlanTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *RecipePlanTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_RECIPE_PLAN ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *RecipePlanTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"num": t.Num,
		"p": t.P,
		"rate": t.Rate,
		"recipe_id": t.RecipeID,
		"st": t.St,
	}
}

