// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// RecipeTemplate represents TBL_RECIPE (table_id=105)
type RecipeTemplate struct {
	ID int64 `json:"id" db:"id"`
	Color float64 `json:"color" db:"color"`
	Desc string `json:"desc" db:"desc"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	IsOpen float64 `json:"is_open" db:"is_open"`
	Kind float64 `json:"kind" db:"kind"`
	Money float64 `json:"money" db:"money"`
	Name string `json:"name" db:"name"`
	Num float64 `json:"num" db:"num"`
	Position float64 `json:"position" db:"position"`
	Product float64 `json:"product" db:"product"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *RecipeTemplate) TableName() string {
	return "TBL_RECIPE"
}

// TableID returns the table ID for this template
func (t *RecipeTemplate) TableID() int {
	return 105
}

// GetID returns the record ID as int
func (t *RecipeTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *RecipeTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_RECIPE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *RecipeTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"color": t.Color,
		"desc": t.Desc,
		"icon_code": t.IconCode,
		"is_open": t.IsOpen,
		"kind": t.Kind,
		"money": t.Money,
		"name": t.Name,
		"num": t.Num,
		"position": t.Position,
		"product": t.Product,
		"type": t.Type,
	}
}

