// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// RecyclingTemplate represents TBL_RECYCLING (table_id=115)
type RecyclingTemplate struct {
	ID int64 `json:"id" db:"id"`
	Color float64 `json:"color" db:"color"`
	ItemID float64 `json:"item_id" db:"item_id"`
	Type float64 `json:"type" db:"type"`
	Value float64 `json:"value" db:"value"`
}

// TableName returns the table name for this template
func (t *RecyclingTemplate) TableName() string {
	return "TBL_RECYCLING"
}

// TableID returns the table ID for this template
func (t *RecyclingTemplate) TableID() int {
	return 115
}

// GetID returns the record ID as int
func (t *RecyclingTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *RecyclingTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_RECYCLING ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *RecyclingTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"color": t.Color,
		"item_id": t.ItemID,
		"type": t.Type,
		"value": t.Value,
	}
}

