// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

// Table name constants
const (
	TableClass              = "TBL_CLASS"
	TableCreature           = "TBL_CREATURE"
	TableCreatureLoot       = "TBL_CREATURE_LOOT"
	TableCreatureSkill      = "TBL_CREATURE_SKILL"
	TableEquiptTemplate     = "TBL_EQUIPT_TEMPLATE"
	TableEquiptInstance     = "TBL_EQUIPT_INSTANCE"
	TableItemTemplate       = "TBL_ITEM_TEMPLATE"
	TableItemInstance       = "TBL_ITEM_INSTANCE"
	TablePet                = "TBL_PET"
	TableMap                = "TBL_MAP"
	TableMapCreature        = "TBL_MAP_CREATURE"
	TableNpc                = "TBL_NPC"
	TableNpcCreature        = "TBL_NPC_CREATURE"
	TableNpcSkill           = "TBL_NPC_SKILL"
	TablePlan               = "TBL_PLAN"
	TableQuest              = "TBL_QUEST"
	TableQuestAward         = "TBL_QUEST_AWARD"
	TableQuestRequire       = "TBL_QUEST_REQUIRE"
	TableSceneitemInstance  = "TBL_SCENEITEM_INSTANCE"
	TableSceneitemTemplate  = "TBL_SCENEITEM_TEMPLATE"
	TableShopSlot           = "TBL_SHOP_SLOT"
	TableSkill              = "TBL_SKILL"
	TableShop               = "TBL_SHOP"
	TableSkillKind          = "TBL_SKILL_KIND"
	TableSkillPool          = "TBL_SKILL_POOL"
	TableSkillType          = "TBL_SKILL_TYPE"
	TableQuestLoop          = "TBL_QUEST_LOOP"
	TableTitle              = "TBL_TITLE"
	TableMapCell            = "TBL_MAP_CELL"
	TableAnswer             = "TBL_ANSWER"
	TableQuestPre           = "TBL_QUEST_PRE"
	TableBuff               = "TBL_BUFF"
	TableFeast              = "TBL_FEAST"
	TableBuilding           = "TBL_BUILDING"
	TableExtendPosition     = "TBL_EXTEND_POSITION"
	TableEquiptSuit         = "TBL_EQUIPT_SUIT"
	TableAchievement        = "TBL_ACHIEVEMENT"
	TableAchievementRequire = "TBL_ACHIEVEMENT_REQUIRE"
	TableGuide              = "TBL_GUIDE"
	TableNameLib            = "TBL_NAME_LIB"
	TableMineralTemplate    = "TBL_MINERAL_TEMPLATE"
	TableDiary              = "TBL_DIARY"
	TableFairyTempalte      = "TBL_FAIRY_TEMPALTE"
	TableStarsTemplate      = "TBL_STARS_TEMPLATE"
	TableWarMap             = "TBL_WAR_MAP"
	TablePetSoul            = "TBL_PET_SOUL"
	TablePmRight            = "TBL_PM_RIGHT"
	TableMount              = "TBL_MOUNT"
	TableMountDress         = "TBL_MOUNT_DRESS"
	TableMedal              = "TBL_MEDAL"
	TableMaze               = "TBL_MAZE"
	TableCreatureHandbook   = "TBL_CREATURE_HANDBOOK"
	TablePetTalent          = "TBL_PET_TALENT"
	TableArtifact           = "TBL_ARTIFACT"
	TableDress              = "TBL_DRESS"
	TableRecipe             = "TBL_RECIPE"
	TableRecipePlan         = "TBL_RECIPE_PLAN"
	TableCredit             = "TBL_CREDIT"
	TableSublimation        = "TBL_SUBLIMATION"
	TableSublimationPet     = "TBL_SUBLIMATION_PET"
	TableAwakening          = "TBL_AWAKENING"
	TableAwakeningSkill     = "TBL_AWAKENING_SKILL"
	TableRecycling          = "TBL_RECYCLING"
	TableSoul               = "TBL_SOUL"
	TablePetContract        = "TBL_PET_CONTRACT"
	TableDecoHole           = "TBL_DECO_HOLE"
	TableDecoRune           = "TBL_DECO_RUNE"
	TableDecoShow           = "TBL_DECO_SHOW"
	TableMystreRecipe       = "TBL_MYSTRE_RECIPE"
	TableMystre             = "TBL_MYSTRE"
	TableRuneChip           = "TBL_RUNE_CHIP"
	TablePrsTree            = "TBL_PRS_TREE"
	TablePrsShow            = "TBL_PRS_SHOW"
	TablePrsChip            = "TBL_PRS_CHIP"
	TableMeventMap          = "TBL_MEVENT_MAP"
	TableMeventType         = "TBL_MEVENT_TYPE"
	TableWarSprite          = "TBL_WAR_SPRITE"
	TableCreaturehHeart     = "TBL_CREATUREH_HEART"
	TableCreaturehCombine   = "TBL_CREATUREH_COMBINE"
	TableCreaturehContain   = "TBL_CREATUREH_CONTAIN"
	TableCreaturehPoint     = "TBL_CREATUREH_POINT"
	TablePetGuard           = "TBL_PET_GUARD"
	TablePetStone           = "TBL_PET_STONE"
	TableExplorerMedal      = "TBL_EXPLORER_MEDAL"
	TableCarve              = "TBL_CARVE"
	TableCarveAward         = "TBL_CARVE_AWARD"
	TableCarveMaster        = "TBL_CARVE_MASTER"
	TableMytcSuit              = "TBL_MYTC_SUIT"
	TableMytcDetail            = "TBL_MYTC_DETAIL"
	TableItemAward             = "TBL_ITEM_AWARD"
	TableHeiyaoshiPoint        = "TBL_HEIYAOSHI_POINT"
	TableHeiyaoshiPointLink    = "TBL_HEIYAOSHI_POINT_LINK"
	TableHeiyaoshiArea         = "TBL_HEIYAOSHI_AREA"
	TableHeiyaoshiAreaAttr     = "TBL_HEIYAOSHI_AREA_ATTRIBUTE"
	TableHeiyaoshiFullBuff     = "TBL_HEIYAOSHI_FULL_BUFF"
)

// TableIDToName maps table IDs to table names
var TableIDToName = map[int]string{
	11:  "TBL_CLASS",
	12:  "TBL_CREATURE",
	13:  "TBL_CREATURE_LOOT",
	14:  "TBL_CREATURE_SKILL",
	18:  "TBL_EQUIPT_INSTANCE",
	19:  "TBL_EQUIPT_TEMPLATE",
	28:  "TBL_ITEM_INSTANCE",
	29:  "TBL_ITEM_TEMPLATE",
	39:  "TBL_PET",
	33:  "TBL_MAP",
	34:  "TBL_MAP_CREATURE",
	35:  "TBL_NPC",
	36:  "TBL_NPC_CREATURE",
	38:  "TBL_NPC_SKILL",
	42:  "TBL_PLAN",
	45:  "TBL_QUEST",
	46:  "TBL_QUEST_AWARD",
	47:  "TBL_QUEST_REQUIRE",
	49:  "TBL_SCENEITEM_INSTANCE",
	50:  "TBL_SCENEITEM_TEMPLATE",
	51:  "TBL_SHOP_SLOT",
	52:  "TBL_SKILL",
	53:  "TBL_SHOP",
	55:  "TBL_SKILL_KIND",
	56:  "TBL_SKILL_POOL",
	57:  "TBL_SKILL_TYPE",
	58:  "TBL_QUEST_LOOP",
	59:  "TBL_TITLE",
	60:  "TBL_MAP_CELL",
	61:  "TBL_ANSWER",
	64:  "TBL_QUEST_PRE",
	66:  "TBL_BUFF",
	67:  "TBL_FEAST",
	70:  "TBL_BUILDING",
	71:  "TBL_EXTEND_POSITION",
	73:  "TBL_EQUIPT_SUIT",
	74:  "TBL_ACHIEVEMENT",
	75:  "TBL_ACHIEVEMENT_REQUIRE",
	79:  "TBL_GUIDE",
	80:  "TBL_NAME_LIB",
	83:  "TBL_MINERAL_TEMPLATE",
	85:  "TBL_DIARY",
	86:  "TBL_FAIRY_TEMPALTE",
	88:  "TBL_STARS_TEMPLATE",
	89:  "TBL_WAR_MAP",
	94:  "TBL_PET_SOUL",
	95:  "TBL_PM_RIGHT",
	96:  "TBL_MOUNT",
	97:  "TBL_MOUNT_DRESS",
	98:  "TBL_MEDAL",
	99:  "TBL_MAZE",
	100: "TBL_CREATURE_HANDBOOK",
	101: "TBL_PET_TALENT",
	102: "TBL_ARTIFACT",
	104: "TBL_DRESS",
	105: "TBL_RECIPE",
	106: "TBL_RECIPE_PLAN",
	107: "TBL_CREDIT",
	108: "TBL_SUBLIMATION",
	112: "TBL_SUBLIMATION_PET",
	113: "TBL_AWAKENING",
	114: "TBL_AWAKENING_SKILL",
	115: "TBL_RECYCLING",
	116: "TBL_SOUL",
	117: "TBL_PET_CONTRACT",
	118: "TBL_DECO_HOLE",
	119: "TBL_DECO_RUNE",
	120: "TBL_DECO_SHOW",
	122: "TBL_MYSTRE_RECIPE",
	123: "TBL_MYSTRE",
	124: "TBL_RUNE_CHIP",
	125: "TBL_PRS_TREE",
	126: "TBL_PRS_SHOW",
	127: "TBL_PRS_CHIP",
	128: "TBL_MEVENT_MAP",
	129: "TBL_MEVENT_TYPE",
	130: "TBL_WAR_SPRITE",
	131: "TBL_CREATUREH_HEART",
	132: "TBL_CREATUREH_COMBINE",
	133: "TBL_CREATUREH_CONTAIN",
	134: "TBL_CREATUREH_POINT",
	135: "TBL_PET_GUARD",
	136: "TBL_PET_STONE",
	137: "TBL_EXPLORER_MEDAL",
	138: "TBL_CARVE",
	139: "TBL_CARVE_AWARD",
	140: "TBL_CARVE_MASTER",
	142: "TBL_MYTC_SUIT",
	143: "TBL_MYTC_DETAIL",
	144: "TBL_ITEM_AWARD",
	145: "TBL_HEIYAOSHI_POINT",
	146: "TBL_HEIYAOSHI_POINT_LINK",
	147: "TBL_HEIYAOSHI_AREA",
	148: "TBL_HEIYAOSHI_AREA_ATTRIBUTE",
	149: "TBL_HEIYAOSHI_FULL_BUFF",
}

// TableNameToID maps table names to table IDs
var TableNameToID = map[string]int{
	"TBL_CLASS":               11,
	"TBL_CREATURE":            12,
	"TBL_CREATURE_LOOT":       13,
	"TBL_CREATURE_SKILL":      14,
	"TBL_EQUIPT_INSTANCE":     18,
	"TBL_EQUIPT_TEMPLATE":     19,
	"TBL_ITEM_INSTANCE":       28,
	"TBL_ITEM_TEMPLATE":       29,
	"TBL_PET":                 39,
	"TBL_MAP":                 33,
	"TBL_MAP_CREATURE":        34,
	"TBL_NPC":                 35,
	"TBL_NPC_CREATURE":        36,
	"TBL_NPC_SKILL":           38,
	"TBL_PLAN":                42,
	"TBL_QUEST":               45,
	"TBL_QUEST_AWARD":         46,
	"TBL_QUEST_REQUIRE":       47,
	"TBL_SCENEITEM_INSTANCE":  49,
	"TBL_SCENEITEM_TEMPLATE":  50,
	"TBL_SHOP_SLOT":           51,
	"TBL_SKILL":               52,
	"TBL_SHOP":                53,
	"TBL_SKILL_KIND":          55,
	"TBL_SKILL_POOL":          56,
	"TBL_SKILL_TYPE":          57,
	"TBL_QUEST_LOOP":          58,
	"TBL_TITLE":               59,
	"TBL_MAP_CELL":            60,
	"TBL_ANSWER":              61,
	"TBL_QUEST_PRE":           64,
	"TBL_BUFF":                66,
	"TBL_FEAST":               67,
	"TBL_BUILDING":            70,
	"TBL_EXTEND_POSITION":     71,
	"TBL_EQUIPT_SUIT":         73,
	"TBL_ACHIEVEMENT":         74,
	"TBL_ACHIEVEMENT_REQUIRE": 75,
	"TBL_GUIDE":               79,
	"TBL_NAME_LIB":            80,
	"TBL_MINERAL_TEMPLATE":    83,
	"TBL_DIARY":               85,
	"TBL_FAIRY_TEMPALTE":      86,
	"TBL_STARS_TEMPLATE":      88,
	"TBL_WAR_MAP":             89,
	"TBL_PET_SOUL":            94,
	"TBL_PM_RIGHT":            95,
	"TBL_MOUNT":               96,
	"TBL_MOUNT_DRESS":         97,
	"TBL_MEDAL":               98,
	"TBL_MAZE":                99,
	"TBL_CREATURE_HANDBOOK":   100,
	"TBL_PET_TALENT":          101,
	"TBL_ARTIFACT":            102,
	"TBL_DRESS":               104,
	"TBL_RECIPE":              105,
	"TBL_RECIPE_PLAN":         106,
	"TBL_CREDIT":              107,
	"TBL_SUBLIMATION":         108,
	"TBL_SUBLIMATION_PET":     112,
	"TBL_AWAKENING":           113,
	"TBL_AWAKENING_SKILL":     114,
	"TBL_RECYCLING":           115,
	"TBL_SOUL":                116,
	"TBL_PET_CONTRACT":        117,
	"TBL_DECO_HOLE":           118,
	"TBL_DECO_RUNE":           119,
	"TBL_DECO_SHOW":           120,
	"TBL_MYSTRE_RECIPE":       122,
	"TBL_MYSTRE":              123,
	"TBL_RUNE_CHIP":           124,
	"TBL_PRS_TREE":            125,
	"TBL_PRS_SHOW":            126,
	"TBL_PRS_CHIP":            127,
	"TBL_MEVENT_MAP":          128,
	"TBL_MEVENT_TYPE":         129,
	"TBL_WAR_SPRITE":          130,
	"TBL_CREATUREH_HEART":     131,
	"TBL_CREATUREH_COMBINE":   132,
	"TBL_CREATUREH_CONTAIN":   133,
	"TBL_CREATUREH_POINT":     134,
	"TBL_PET_GUARD":           135,
	"TBL_PET_STONE":           136,
	"TBL_EXPLORER_MEDAL":      137,
	"TBL_CARVE":               138,
	"TBL_CARVE_AWARD":         139,
	"TBL_CARVE_MASTER":        140,
	"TBL_MYTC_SUIT":               142,
	"TBL_MYTC_DETAIL":             143,
	"TBL_ITEM_AWARD":              144,
	"TBL_HEIYAOSHI_POINT":         145,
	"TBL_HEIYAOSHI_POINT_LINK":    146,
	"TBL_HEIYAOSHI_AREA":          147,
	"TBL_HEIYAOSHI_AREA_ATTRIBUTE": 148,
	"TBL_HEIYAOSHI_FULL_BUFF":     149,
}

// Template is the interface implemented by all game data templates
type Template interface {
	TableName() string
	TableID() int
	GetID() int
	Validate() error
	ToDTO() map[string]interface{}
}

// NewTemplate creates a new template instance by table name
func NewTemplate(tableName string) Template {
	switch tableName {
	case "TBL_CLASS":
		return &ClassTemplate{}
	case "TBL_CREATURE":
		return &CreatureTemplate{}
	case "TBL_CREATURE_LOOT":
		return &CreatureLootTemplate{}
	case "TBL_CREATURE_SKILL":
		return &CreatureSkillTemplate{}
	case "TBL_EQUIPT_TEMPLATE":
		return &EquiptTemplateTemplate{}
	case "TBL_ITEM_TEMPLATE":
		return &ItemTemplateTemplate{}
	case "TBL_MAP":
		return &MapTemplate{}
	case "TBL_MAP_CREATURE":
		return &MapCreatureTemplate{}
	case "TBL_NPC":
		return &NpcTemplate{}
	case "TBL_NPC_CREATURE":
		return &NpcCreatureTemplate{}
	case "TBL_NPC_SKILL":
		return &NpcSkillTemplate{}
	case "TBL_PLAN":
		return &PlanTemplate{}
	case "TBL_QUEST":
		return &QuestTemplate{}
	case "TBL_QUEST_AWARD":
		return &QuestAwardTemplate{}
	case "TBL_QUEST_REQUIRE":
		return &QuestRequireTemplate{}
	case "TBL_SCENEITEM_INSTANCE":
		return &SceneitemInstanceTemplate{}
	case "TBL_SCENEITEM_TEMPLATE":
		return &SceneitemTemplateTemplate{}
	case "TBL_SHOP_SLOT":
		return &ShopSlotTemplate{}
	case "TBL_SKILL":
		return &SkillTemplate{}
	case "TBL_SHOP":
		return &ShopTemplate{}
	case "TBL_SKILL_KIND":
		return &SkillKindTemplate{}
	case "TBL_SKILL_POOL":
		return &SkillPoolTemplate{}
	case "TBL_SKILL_TYPE":
		return &SkillTypeTemplate{}
	case "TBL_QUEST_LOOP":
		return &QuestLoopTemplate{}
	case "TBL_TITLE":
		return &TitleTemplate{}
	case "TBL_MAP_CELL":
		return &MapCellTemplate{}
	case "TBL_ANSWER":
		return &AnswerTemplate{}
	case "TBL_QUEST_PRE":
		return &QuestPreTemplate{}
	case "TBL_BUFF":
		return &BuffTemplate{}
	case "TBL_FEAST":
		return &FeastTemplate{}
	case "TBL_BUILDING":
		return &BuildingTemplate{}
	case "TBL_EXTEND_POSITION":
		return &ExtendPositionTemplate{}
	case "TBL_EQUIPT_SUIT":
		return &EquiptSuitTemplate{}
	case "TBL_ACHIEVEMENT":
		return &AchievementTemplate{}
	case "TBL_ACHIEVEMENT_REQUIRE":
		return &AchievementRequireTemplate{}
	case "TBL_GUIDE":
		return &GuideTemplate{}
	case "TBL_NAME_LIB":
		return &NameLibTemplate{}
	case "TBL_MINERAL_TEMPLATE":
		return &MineralTemplateTemplate{}
	case "TBL_DIARY":
		return &DiaryTemplate{}
	case "TBL_FAIRY_TEMPALTE":
		return &FairyTempalteTemplate{}
	case "TBL_STARS_TEMPLATE":
		return &StarsTemplateTemplate{}
	case "TBL_WAR_MAP":
		return &WarMapTemplate{}
	case "TBL_PET_SOUL":
		return &PetSoulTemplate{}
	case "TBL_PM_RIGHT":
		return &PmRightTemplate{}
	case "TBL_MOUNT":
		return &MountTemplate{}
	case "TBL_MOUNT_DRESS":
		return &MountDressTemplate{}
	case "TBL_MEDAL":
		return &MedalTemplate{}
	case "TBL_MAZE":
		return &MazeTemplate{}
	case "TBL_CREATURE_HANDBOOK":
		return &CreatureHandbookTemplate{}
	case "TBL_PET_TALENT":
		return &PetTalentTemplate{}
	case "TBL_ARTIFACT":
		return &ArtifactTemplate{}
	case "TBL_DRESS":
		return &DressTemplate{}
	case "TBL_RECIPE":
		return &RecipeTemplate{}
	case "TBL_RECIPE_PLAN":
		return &RecipePlanTemplate{}
	case "TBL_CREDIT":
		return &CreditTemplate{}
	case "TBL_SUBLIMATION":
		return &SublimationTemplate{}
	case "TBL_SUBLIMATION_PET":
		return &SublimationPetTemplate{}
	case "TBL_AWAKENING":
		return &AwakeningTemplate{}
	case "TBL_AWAKENING_SKILL":
		return &AwakeningSkillTemplate{}
	case "TBL_RECYCLING":
		return &RecyclingTemplate{}
	case "TBL_SOUL":
		return &SoulTemplate{}
	case "TBL_PET_CONTRACT":
		return &PetContractTemplate{}
	case "TBL_DECO_HOLE":
		return &DecoHoleTemplate{}
	case "TBL_DECO_RUNE":
		return &DecoRuneTemplate{}
	case "TBL_DECO_SHOW":
		return &DecoShowTemplate{}
	case "TBL_MYSTRE_RECIPE":
		return &MystreRecipeTemplate{}
	case "TBL_MYSTRE":
		return &MystreTemplate{}
	case "TBL_RUNE_CHIP":
		return &RuneChipTemplate{}
	case "TBL_PRS_TREE":
		return &PrsTreeTemplate{}
	case "TBL_PRS_SHOW":
		return &PrsShowTemplate{}
	case "TBL_PRS_CHIP":
		return &PrsChipTemplate{}
	case "TBL_MEVENT_MAP":
		return &MeventMapTemplate{}
	case "TBL_MEVENT_TYPE":
		return &MeventTypeTemplate{}
	case "TBL_WAR_SPRITE":
		return &WarSpriteTemplate{}
	case "TBL_CREATUREH_HEART":
		return &CreaturehHeartTemplate{}
	case "TBL_CREATUREH_COMBINE":
		return &CreaturehCombineTemplate{}
	case "TBL_CREATUREH_CONTAIN":
		return &CreaturehContainTemplate{}
	case "TBL_CREATUREH_POINT":
		return &CreaturehPointTemplate{}
	case "TBL_PET_GUARD":
		return &PetGuardTemplate{}
	case "TBL_PET_STONE":
		return &PetStoneTemplate{}
	case "TBL_EXPLORER_MEDAL":
		return &ExplorerMedalTemplate{}
	case "TBL_CARVE":
		return &CarveTemplate{}
	case "TBL_CARVE_AWARD":
		return &CarveAwardTemplate{}
	case "TBL_CARVE_MASTER":
		return &CarveMasterTemplate{}
	case "TBL_MYTC_SUIT":
		return &MytcSuitTemplate{}
	case "TBL_MYTC_DETAIL":
		return &MytcDetailTemplate{}
	case "TBL_ITEM_AWARD":
		return &ItemAwardTemplate{}
	case "TBL_HEIYAOSHI_POINT":
		return &HeiyaoshiPointTemplate{}
	case "TBL_HEIYAOSHI_POINT_LINK":
		return &HeiyaoshiPointLinkTemplate{}
	case "TBL_HEIYAOSHI_AREA":
		return &HeiyaoshiAreaTemplate{}
	case "TBL_HEIYAOSHI_AREA_ATTRIBUTE":
		return &HeiyaoshiAreaAttributeTemplate{}
	case "TBL_HEIYAOSHI_FULL_BUFF":
		return &HeiyaoshiFullBuffTemplate{}
	default:
		return nil
	}
}
