// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// RuneChipTemplate represents TBL_RUNE_CHIP (table_id=124)
type RuneChipTemplate struct {
	ID int64 `json:"id" db:"id"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	Kind float64 `json:"kind" db:"kind"`
	Name string `json:"name" db:"name"`
	Num float64 `json:"num" db:"num"`
	Rid float64 `json:"rid" db:"rid"`
}

// TableName returns the table name for this template
func (t *RuneChipTemplate) TableName() string {
	return "TBL_RUNE_CHIP"
}

// TableID returns the table ID for this template
func (t *RuneChipTemplate) TableID() int {
	return 124
}

// GetID returns the record ID as int
func (t *RuneChipTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *RuneChipTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_RUNE_CHIP ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *RuneChipTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"icon_code": t.IconCode,
		"kind": t.Kind,
		"name": t.Name,
		"num": t.Num,
		"rid": t.Rid,
	}
}

