// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// SceneitemTemplateTemplate represents TBL_SCENEITEM_TEMPLATE (table_id=50)
type SceneitemTemplateTemplate struct {
	ID int64 `json:"id" db:"id"`
	BrightCode float64 `json:"bright_code" db:"bright_code"`
	ColorCode float64 `json:"color_code" db:"color_code"`
	Description string `json:"description" db:"description"`
	Gold float64 `json:"gold" db:"gold"`
	Honor float64 `json:"honor" db:"honor"`
	IconCode float64 `json:"icon_code" db:"icon_code"`
	KeepTime float64 `json:"keep_time" db:"keep_time"`
	Kind float64 `json:"kind" db:"kind"`
	Name string `json:"name" db:"name"`
	Price float64 `json:"price" db:"price"`
	ResCode float64 `json:"res_code" db:"res_code"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *SceneitemTemplateTemplate) TableName() string {
	return "TBL_SCENEITEM_TEMPLATE"
}

// TableID returns the table ID for this template
func (t *SceneitemTemplateTemplate) TableID() int {
	return 50
}

// GetID returns the record ID as int
func (t *SceneitemTemplateTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *SceneitemTemplateTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_SCENEITEM_TEMPLATE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *SceneitemTemplateTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"bright_code": t.BrightCode,
		"color_code": t.ColorCode,
		"description": t.Description,
		"gold": t.Gold,
		"honor": t.Honor,
		"icon_code": t.IconCode,
		"keep_time": t.KeepTime,
		"kind": t.Kind,
		"name": t.Name,
		"price": t.Price,
		"res_code": t.ResCode,
		"type": t.Type,
	}
}

