// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// SceneitemInstanceTemplate represents TBL_SCENEITEM_INSTANCE (table_id=49)
type SceneitemInstanceTemplate struct {
	ID int64 `json:"id" db:"id"`
	BrightCode float64 `json:"bright_code" db:"bright_code"`
	ColorCode float64 `json:"color_code" db:"color_code"`
	DeadLine float64 `json:"dead_line" db:"dead_line"`
	Layer float64 `json:"layer" db:"layer"`
	Maker float64 `json:"maker" db:"maker"`
	Name string `json:"name" db:"name"`
	OwnerID float64 `json:"owner_id" db:"owner_id"`
	OwnerType float64 `json:"owner_type" db:"owner_type"`
	PosDir float64 `json:"pos_dir" db:"pos_dir"`
	PosMapID float64 `json:"pos_map_id" db:"pos_map_id"`
	From int64 `json:"from" db:"from"`
	PosX float64 `json:"pos_x" db:"pos_x"`
	PosY float64 `json:"pos_y" db:"pos_y"`
	Tid float64 `json:"tid" db:"tid"`
}

// TableName returns the table name for this template
func (t *SceneitemInstanceTemplate) TableName() string {
	return "TBL_SCENEITEM_INSTANCE"
}

// TableID returns the table ID for this template
func (t *SceneitemInstanceTemplate) TableID() int {
	return 49
}

// GetID returns the record ID as int
func (t *SceneitemInstanceTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *SceneitemInstanceTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_SCENEITEM_INSTANCE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *SceneitemInstanceTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"bright_code": t.BrightCode,
		"color_code": t.ColorCode,
		"dead_line": t.DeadLine,
		"layer": t.Layer,
		"maker": t.Maker,
		"name": t.Name,
		"owner_id": t.OwnerID,
		"owner_type": t.OwnerType,
		"pos_dir": t.PosDir,
		"pos_map_id": t.PosMapID,
		"from": t.From,
		"pos_x": t.PosX,
		"pos_y": t.PosY,
		"tid": t.Tid,
	}
}

