// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// ShopSlotTemplate represents TBL_SHOP_SLOT (table_id=51)
type ShopSlotTemplate struct {
	ID int64 `json:"id" db:"id"`
	Amount float64 `json:"amount" db:"amount"`
	Gold float64 `json:"gold" db:"gold"`
	Gt float64 `json:"gt" db:"gt"`
	ItemID float64 `json:"item_id" db:"item_id"`
	Money float64 `json:"money" db:"money"`
	PNum1 float64 `json:"p_num1" db:"p_num1"`
	PNum2 float64 `json:"p_num2" db:"p_num2"`
	PType1 float64 `json:"p_type1" db:"p_type1"`
	PType2 float64 `json:"p_type2" db:"p_type2"`
	Point float64 `json:"point" db:"point"`
	Position float64 `json:"position" db:"position"`
	PriceAll float64 `json:"price_all" db:"price_all"`
	Quality float64 `json:"quality" db:"quality"`
	R float64 `json:"r" db:"r"`
	Sale float64 `json:"sale" db:"sale"`
	Sid float64 `json:"sid" db:"sid"`
	St float64 `json:"st" db:"st"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *ShopSlotTemplate) TableName() string {
	return "TBL_SHOP_SLOT"
}

// TableID returns the table ID for this template
func (t *ShopSlotTemplate) TableID() int {
	return 51
}

// GetID returns the record ID as int
func (t *ShopSlotTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *ShopSlotTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_SHOP_SLOT ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *ShopSlotTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"amount": t.Amount,
		"gold": t.Gold,
		"gt": t.Gt,
		"item_id": t.ItemID,
		"money": t.Money,
		"p_num1": t.PNum1,
		"p_num2": t.PNum2,
		"p_type1": t.PType1,
		"p_type2": t.PType2,
		"point": t.Point,
		"position": t.Position,
		"price_all": t.PriceAll,
		"quality": t.Quality,
		"r": t.R,
		"sale": t.Sale,
		"sid": t.Sid,
		"st": t.St,
		"type": t.Type,
	}
}

