// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// ShopTemplate represents TBL_SHOP (table_id=53)
type ShopTemplate struct {
	ID int64 `json:"id" db:"id"`
	Name string `json:"name" db:"name"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *ShopTemplate) TableName() string {
	return "TBL_SHOP"
}

// TableID returns the table ID for this template
func (t *ShopTemplate) TableID() int {
	return 53
}

// GetID returns the record ID as int
func (t *ShopTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *ShopTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_SHOP ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *ShopTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"name": t.Name,
		"type": t.Type,
	}
}

