// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// SkillPoolTemplate represents TBL_SKILL_POOL (table_id=56)
type SkillPoolTemplate struct {
	ID int64 `json:"id" db:"id"`
	Pi float64 `json:"pi" db:"pi"`
	Si float64 `json:"si" db:"si"`
}

// TableName returns the table name for this template
func (t *SkillPoolTemplate) TableName() string {
	return "TBL_SKILL_POOL"
}

// TableID returns the table ID for this template
func (t *SkillPoolTemplate) TableID() int {
	return 56
}

// GetID returns the record ID as int
func (t *SkillPoolTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *SkillPoolTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_SKILL_POOL ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *SkillPoolTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"pi": t.Pi,
		"si": t.Si,
	}
}

