// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// SkillKindTemplate represents TBL_SKILL_KIND (table_id=55)
type SkillKindTemplate struct {
	ID int64 `json:"id" db:"id"`
	Name string `json:"name" db:"name"`
}

// TableName returns the table name for this template
func (t *SkillKindTemplate) TableName() string {
	return "TBL_SKILL_KIND"
}

// TableID returns the table ID for this template
func (t *SkillKindTemplate) TableID() int {
	return 55
}

// GetID returns the record ID as int
func (t *SkillKindTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *SkillKindTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_SKILL_KIND ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *SkillKindTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"name": t.Name,
	}
}

