// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
	"strconv"
	"strings"
)

// SkillTemplate represents TBL_SKILL (table_id=52)
type SkillTemplate struct {
	ID               int64   `json:"id" db:"id"`
	AreaAttack       float64 `json:"area_attack" db:"area_attack"`
	AttackNum        float64 `json:"attack_num" db:"attack_num"`
	BuffID           float64 `json:"buff_id" db:"buff_id"`
	BuffRate         float64 `json:"buff_rate" db:"buff_rate"`
	BuffRound        float64 `json:"buff_round" db:"buff_round"`
	CodeName         string  `json:"code_name" db:"code_name"`
	CostGuildContrib float64 `json:"cost_guild_contrib" db:"cost_guild_contrib"`
	CreKind          string  `json:"cre_kind" db:"cre_kind"`
	Description      string  `json:"description" db:"description"`
	DexSkill         float64 `json:"dex_skill" db:"dex_skill"`
	Element          float64 `json:"element" db:"element"`
	ExSid1           float64 `json:"ex_sid1" db:"ex_sid1"`
	ExSid2           float64 `json:"ex_sid2" db:"ex_sid2"`
	ExSid3           float64 `json:"ex_sid3" db:"ex_sid3"`
	ExStoneSid       float64 `json:"ex_stone_sid" db:"ex_stone_sid"`
	ExpSkill         float64 `json:"exp_skill" db:"exp_skill"`
	Gold             float64 `json:"gold" db:"gold"`
	GuildDevExp      float64 `json:"guild_dev_exp" db:"guild_dev_exp"`
	GuildDevMoney    float64 `json:"guild_dev_money" db:"guild_dev_money"`
	IconCode         float64 `json:"icon_code" db:"icon_code"`
	Info             string  `json:"info" db:"info"`
	IsTest           float64 `json:"is_test" db:"is_test"`
	Kind             float64 `json:"kind" db:"kind"`
	Level            float64 `json:"level" db:"level"`
	MultiAttack      float64 `json:"multi_attack" db:"multi_attack"`
	Name             string  `json:"name" db:"name"`
	Price            float64 `json:"price" db:"price"`
	ReqCL            float64 `json:"req_c_l" db:"req_c_l"`
	ReqClass         string  `json:"req_class" db:"req_class"`
	ReqLevel         float64 `json:"req_level" db:"req_level"`
	RestoreSid       float64 `json:"restore_sid" db:"restore_sid"`
	RestoreStoneSid  float64 `json:"restore_stone_sid" db:"restore_stone_sid"`
	ScriptReqL       string  `json:"script_req_l" db:"script_req_l"`
	TargetNum        float64 `json:"target_num" db:"target_num"`
	TargetType       float64 `json:"target_type" db:"target_type"`
	Type             float64 `json:"type" db:"type"`
	UseEnv           float64 `json:"use_env" db:"use_env"`
	UseHP            float64 `json:"use_hp" db:"use_hp"`
	UseItemID        float64 `json:"use_item_id" db:"use_item_id"`
	UseItemNum       float64 `json:"use_item_num" db:"use_item_num"`
	UseItemType      float64 `json:"use_item_type" db:"use_item_type"`
	UseMP            float64 `json:"use_mp" db:"use_mp"`
	UseSP            float64 `json:"use_sp" db:"use_sp"`
	FrontEffID       float64 `json:"front_eff_id" db:"front_eff_id"`
	AttackEffID      float64 `json:"attack_eff_id" db:"attack_eff_id"`
	SkillEffID       float64 `json:"skill_eff_id" db:"skill_eff_id"`
	BulletID         float64 `json:"bullet_id" db:"bullet_id"`
}

// TableName returns the table name for this template
func (t *SkillTemplate) TableName() string {
	return "TBL_SKILL"
}

// TableID returns the table ID for this template
func (t *SkillTemplate) TableID() int {
	return 52
}

// GetID returns the record ID as int
func (t *SkillTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *SkillTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_SKILL ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *SkillTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id":                 t.ID,
		"area_attack":        t.AreaAttack,
		"attack_num":         t.AttackNum,
		"buff_id":            t.BuffID,
		"buff_rate":          t.BuffRate,
		"buff_round":         t.BuffRound,
		"code_name":          t.CodeName,
		"cost_guild_contrib": t.CostGuildContrib,
		"cre_kind":           t.CreKind,
		"description":        t.Description,
		"dex_skill":          t.DexSkill,
		"element":            t.Element,
		"ex_sid1":            t.ExSid1,
		"ex_sid2":            t.ExSid2,
		"ex_sid3":            t.ExSid3,
		"ex_stone_sid":       t.ExStoneSid,
		"exp_skill":          t.ExpSkill,
		"gold":               t.Gold,
		"guild_dev_exp":      t.GuildDevExp,
		"guild_dev_money":    t.GuildDevMoney,
		"icon_code":          t.IconCode,
		"info":               t.Info,
		"is_test":            t.IsTest,
		"kind":               t.Kind,
		"level":              t.Level,
		"multi_attack":       t.MultiAttack,
		"name":               t.Name,
		"price":              t.Price,
		"req_c_l":            t.ReqCL,
		"req_class":          t.ReqClass,
		"req_level":          t.ReqLevel,
		"restore_sid":        t.RestoreSid,
		"restore_stone_sid":  t.RestoreStoneSid,
		"script_req_l":       t.ScriptReqL,
		"target_num":         t.TargetNum,
		"target_type":        t.TargetType,
		"type":               t.Type,
		"use_env":            t.UseEnv,
		"use_hp":             t.UseHP,
		"use_item_id":        t.UseItemID,
		"use_item_num":       t.UseItemNum,
		"use_item_type":      t.UseItemType,
		"use_mp":             t.UseMP,
		"use_sp":             t.UseSP,
		"front_eff_id":       t.FrontEffID,
		"attack_eff_id":      t.AttackEffID,
		"skill_eff_id":       t.SkillEffID,
		"bullet_id":          t.BulletID,
	}
}

// ParsePipeDelimitedInts parses a pipe-delimited string like "|1|2|3|" into []int
func (t *SkillTemplate) ParsePipeDelimitedInts(s string) []int {
	if s == "" || s == "|" {
		return nil
	}
	s = strings.Trim(s, "|")
	parts := strings.Split(s, "|")
	result := make([]int, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue
		}
		if n, err := strconv.Atoi(p); err == nil {
			result = append(result, n)
		}
	}
	return result
}
