// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// SkillTypeTemplate represents TBL_SKILL_TYPE (table_id=57)
type SkillTypeTemplate struct {
	ID int64 `json:"id" db:"id"`
	Kid float64 `json:"kid" db:"kid"`
	Name string `json:"name" db:"name"`
}

// TableName returns the table name for this template
func (t *SkillTypeTemplate) TableName() string {
	return "TBL_SKILL_TYPE"
}

// TableID returns the table ID for this template
func (t *SkillTypeTemplate) TableID() int {
	return 57
}

// GetID returns the record ID as int
func (t *SkillTypeTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *SkillTypeTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_SKILL_TYPE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *SkillTypeTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"kid": t.Kid,
		"name": t.Name,
	}
}

