// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// SoulTemplate represents TBL_SOUL (table_id=116)
type SoulTemplate struct {
	ID int64 `json:"id" db:"id"`
	Prop1 float64 `json:"prop1" db:"prop1"`
	Prop10 float64 `json:"prop10" db:"prop10"`
	Prop2 float64 `json:"prop2" db:"prop2"`
	Prop3 float64 `json:"prop3" db:"prop3"`
	Prop4 float64 `json:"prop4" db:"prop4"`
	Prop5 float64 `json:"prop5" db:"prop5"`
	Prop6 float64 `json:"prop6" db:"prop6"`
	Prop7 float64 `json:"prop7" db:"prop7"`
	Prop8 float64 `json:"prop8" db:"prop8"`
	Prop9 float64 `json:"prop9" db:"prop9"`
	PropNum1 float64 `json:"prop_num1" db:"prop_num1"`
	PropNum10 float64 `json:"prop_num10" db:"prop_num10"`
	PropNum2 float64 `json:"prop_num2" db:"prop_num2"`
	PropNum3 float64 `json:"prop_num3" db:"prop_num3"`
	PropNum4 float64 `json:"prop_num4" db:"prop_num4"`
	PropNum5 float64 `json:"prop_num5" db:"prop_num5"`
	PropNum6 float64 `json:"prop_num6" db:"prop_num6"`
	PropNum7 float64 `json:"prop_num7" db:"prop_num7"`
	PropNum8 float64 `json:"prop_num8" db:"prop_num8"`
	PropNum9 float64 `json:"prop_num9" db:"prop_num9"`
	RequireNum float64 `json:"require_num" db:"require_num"`
}

// TableName returns the table name for this template
func (t *SoulTemplate) TableName() string {
	return "TBL_SOUL"
}

// TableID returns the table ID for this template
func (t *SoulTemplate) TableID() int {
	return 116
}

// GetID returns the record ID as int
func (t *SoulTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *SoulTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_SOUL ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *SoulTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"prop1": t.Prop1,
		"prop10": t.Prop10,
		"prop2": t.Prop2,
		"prop3": t.Prop3,
		"prop4": t.Prop4,
		"prop5": t.Prop5,
		"prop6": t.Prop6,
		"prop7": t.Prop7,
		"prop8": t.Prop8,
		"prop9": t.Prop9,
		"prop_num1": t.PropNum1,
		"prop_num10": t.PropNum10,
		"prop_num2": t.PropNum2,
		"prop_num3": t.PropNum3,
		"prop_num4": t.PropNum4,
		"prop_num5": t.PropNum5,
		"prop_num6": t.PropNum6,
		"prop_num7": t.PropNum7,
		"prop_num8": t.PropNum8,
		"prop_num9": t.PropNum9,
		"require_num": t.RequireNum,
	}
}

