// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// StarsTemplateTemplate represents TBL_STARS_TEMPLATE (table_id=88)
type StarsTemplateTemplate struct {
	ID int64 `json:"id" db:"id"`
	AddProp string `json:"add_prop" db:"add_prop"`
	AddValue float64 `json:"add_value" db:"add_value"`
	Description string `json:"description" db:"description"`
	Level float64 `json:"level" db:"level"`
	Name string `json:"name" db:"name"`
	ReqExp float64 `json:"req_exp" db:"req_exp"`
	ReqLevel float64 `json:"req_level" db:"req_level"`
	ReqMoney float64 `json:"req_money" db:"req_money"`
	ReqSeconds float64 `json:"req_seconds" db:"req_seconds"`
	ReqStarLevel float64 `json:"req_star_level" db:"req_star_level"`
	ResCode float64 `json:"res_code" db:"res_code"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *StarsTemplateTemplate) TableName() string {
	return "TBL_STARS_TEMPLATE"
}

// TableID returns the table ID for this template
func (t *StarsTemplateTemplate) TableID() int {
	return 88
}

// GetID returns the record ID as int
func (t *StarsTemplateTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *StarsTemplateTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_STARS_TEMPLATE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *StarsTemplateTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"add_prop": t.AddProp,
		"add_value": t.AddValue,
		"description": t.Description,
		"level": t.Level,
		"name": t.Name,
		"req_exp": t.ReqExp,
		"req_level": t.ReqLevel,
		"req_money": t.ReqMoney,
		"req_seconds": t.ReqSeconds,
		"req_star_level": t.ReqStarLevel,
		"res_code": t.ResCode,
		"type": t.Type,
	}
}

