// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// SublimationTemplate represents TBL_SUBLIMATION (table_id=108)
type SublimationTemplate struct {
	ID int64 `json:"id" db:"id"`
	ElementNum float64 `json:"element_num" db:"element_num"`
	ItemNum1 float64 `json:"item_num1" db:"item_num1"`
	ItemNum2 float64 `json:"item_num2" db:"item_num2"`
	Prop1 float64 `json:"prop1" db:"prop1"`
	Prop2 float64 `json:"prop2" db:"prop2"`
	Prop3 float64 `json:"prop3" db:"prop3"`
	Prop4 float64 `json:"prop4" db:"prop4"`
	PropNum1 float64 `json:"prop_num1" db:"prop_num1"`
	PropNum2 float64 `json:"prop_num2" db:"prop_num2"`
	PropNum3 float64 `json:"prop_num3" db:"prop_num3"`
	PropNum4 float64 `json:"prop_num4" db:"prop_num4"`
	Rate float64 `json:"rate" db:"rate"`
}

// TableName returns the table name for this template
func (t *SublimationTemplate) TableName() string {
	return "TBL_SUBLIMATION"
}

// TableID returns the table ID for this template
func (t *SublimationTemplate) TableID() int {
	return 108
}

// GetID returns the record ID as int
func (t *SublimationTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *SublimationTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_SUBLIMATION ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *SublimationTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"element_num": t.ElementNum,
		"item_num1": t.ItemNum1,
		"item_num2": t.ItemNum2,
		"prop1": t.Prop1,
		"prop2": t.Prop2,
		"prop3": t.Prop3,
		"prop4": t.Prop4,
		"prop_num1": t.PropNum1,
		"prop_num2": t.PropNum2,
		"prop_num3": t.PropNum3,
		"prop_num4": t.PropNum4,
		"rate": t.Rate,
	}
}

