// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// TitleTemplate represents TBL_TITLE (table_id=59)
type TitleTemplate struct {
	ID     int64  `json:"id" db:"id"`
	A      string `json:"a" db:"a"`
	B      float64 `json:"b" db:"b"`
	I      string `json:"i" db:"i"`
	K      float64 `json:"k" db:"k"`
	L      float64 `json:"l" db:"l"`
	N      string `json:"n" db:"n"`
	S      float64 `json:"s" db:"s"`
	T      float64 `json:"t" db:"t"`
	BuffID *int64 `json:"buff_id,omitempty" db:"buff_id"`
}

// TableName returns the table name for this template
func (t *TitleTemplate) TableName() string {
	return "TBL_TITLE"
}

// TableID returns the table ID for this template
func (t *TitleTemplate) TableID() int {
	return 59
}

// GetID returns the record ID as int
func (t *TitleTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *TitleTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_TITLE ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *TitleTemplate) ToDTO() map[string]interface{} {
	dto := map[string]interface{}{
		"id": t.ID,
		"a":  t.A,
		"b":  t.B,
		"i":  t.I,
		"k":  t.K,
		"l":  t.L,
		"n":  t.N,
		"s":  t.S,
		"t":  t.T,
	}
	if t.BuffID != nil {
		dto["buff_id"] = *t.BuffID
	}
	return dto
}

