// Open-sourced by BaoLT

// Code generated by cmd/codegen. DO NOT EDIT.
package models

import (
	"fmt"
)

// WarMapTemplate represents TBL_WAR_MAP (table_id=89)
type WarMapTemplate struct {
	ID int64 `json:"id" db:"id"`
	Name string `json:"name" db:"name"`
	Pid string `json:"pid" db:"pid"`
	Rc float64 `json:"rc" db:"rc"`
	Type float64 `json:"type" db:"type"`
}

// TableName returns the table name for this template
func (t *WarMapTemplate) TableName() string {
	return "TBL_WAR_MAP"
}

// TableID returns the table ID for this template
func (t *WarMapTemplate) TableID() int {
	return 89
}

// GetID returns the record ID as int
func (t *WarMapTemplate) GetID() int {
	return int(t.ID)
}

// Validate checks if the template data is valid
func (t *WarMapTemplate) Validate() error {
	if t.ID <= 0 {
		return fmt.Errorf("invalid TBL_WAR_MAP ID: %d", t.ID)
	}
	return nil
}

// ToDTO converts to client-compatible format
func (t *WarMapTemplate) ToDTO() map[string]interface{} {
	return map[string]interface{}{
		"id": t.ID,
		"name": t.Name,
		"pid": t.Pid,
		"rc": t.Rc,
		"type": t.Type,
	}
}

