// Open-sourced by BaoLT

// Crosswalk tables from legacy prop ID namespaces (Flash client) to the canonical PropID enum.
// Equipment prop IDs (1-29) and common-feature prop IDs (1-72) are separate legacy namespaces.
package stats

var EquipmentPropMap = map[int]PropID{
	1:  PropHP,
	2:  PropMP,
	3:  PropSP,
	4:  PropPhysAtk,
	5:  PropMagAtk,
	6:  PropPhysDef,
	7:  PropMagDef,
	8:  PropAccuracy,
	9:  PropDodge,
	10: PropCounter,
	11: PropSpeed,
	12: PropCombo,
	13: PropCritRate,
	14: PropDefy,
	20: PropStrength,
	21: PropStamina,
	22: PropIntelligence,
	23: PropEnergy,
	26: PropDeathImmune,
	27: PropResistCrit,
	28: PropResistDebuff,
	29: PropResistDefy,
}

var FeaturePropMap = map[int]PropID{
	1:  PropHP,
	2:  PropMP,
	3:  PropSP,
	4:  PropPhysAtk,
	5:  PropMagAtk,
	6:  PropPhysDef,
	7:  PropMagDef,
	8:  PropAccuracy,
	9:  PropDodge,
	10: PropCounter,
	11: PropSpeed,
	12: PropCombo,
	13: PropCritRate,
	14: PropDefy,
	17: PropResistStun,
	18: PropResistConfuse,
	19: PropResistSleep,
	20: PropResistPoison,
	23: PropResistLight,
	30: PropResistRage,
	31: PropResistCrit,
	32: PropDebuffHit,
	34: PropDeathImmune,
	43: PropResistStun,
	44: PropResistConfuse,
	45: PropResistSleep,
	46: PropResistPoison,
	49: PropResistLight,
	50: PropResistRage,
	51: PropResistCrit,
	52: PropConfuseAcc,
	53: PropStunAcc,
	54: PropPoisonAcc,
	55: PropRageAcc,
	56: PropSleepAcc,
	57: PropLightAcc,
	58: PropResistDebuff,
	59: PropFinalPhysDmgDown,
	60: PropFinalMagDmgDown,
	61: PropResistDefy,
	62: PropFinalPhysDmgUp,
	63: PropFinalMagDmgUp,
	71: PropCritDmgBonus,
	72: PropBreakDeathImmune,
}

var WireKeyPropMap = map[string]PropID{
	"finalCombo":         PropCombo,
	"finalCounter":       PropCounter,
	"finalRebornRate":    PropDeathImmune,
	"finalBreakReborn":   PropBreakDeathImmune,
	"finalDefy":          PropDefy,
	"finalResiDefy":      PropResistDefy,
	"finalResiCritical":  PropResistCrit,
	"finalDizzy":         PropStunAcc,
	"finalConfusion":     PropConfuseAcc,
	"finalSleep":         PropSleepAcc,
	"finalPoison":        PropPoisonAcc,
	"finalRage":          PropRageAcc,
	"finalLight":         PropLightAcc,
	"finalResiDizzy":     PropResistStun,
	"finalResiConfusion":  PropResistConfuse,
	"finalResiSleep":     PropResistSleep,
	"finalResiPoison":    PropResistPoison,
	"finalResiLight":     PropResistLight,
	"finalResiRage":      PropResistRage,
	"finalReduceHurt1":   PropPhysDmgCut,
	"finalReduceHurt2":   PropMagDmgCut,
	"finalEnhPhyHurt":    PropFinalPhysDmgUp,
	"finalEnhMagicHurt":  PropFinalMagDmgUp,
	"finalPraDef":        PropDefy,
	"finalPraMagDef":     PropMagDefy,
	"finalCriticalDamage": PropCritDmgBonus,
}
