
  create table "player"."character_quest_loops" (
    "id" bigint generated by default as identity not null,
    "character_id" bigint not null,
    "loop_id" integer not null,
    "ft" integer not null default 0,
    "take_date_ms" bigint not null,
    "active" boolean not null default true,
    "active_quest_id" integer,
    "updated_at" timestamp with time zone not null default now()
      );


CREATE UNIQUE INDEX character_quest_loops_character_id_loop_id_key ON player.character_quest_loops USING btree (character_id, loop_id);

CREATE UNIQUE INDEX character_quest_loops_pkey ON player.character_quest_loops USING btree (id);

CREATE INDEX idx_character_quest_loops_char ON player.character_quest_loops USING btree (character_id);

alter table "player"."character_quest_loops" add constraint "character_quest_loops_pkey" PRIMARY KEY using index "character_quest_loops_pkey";

alter table "player"."character_quest_loops" add constraint "character_quest_loops_character_id_loop_id_key" UNIQUE using index "character_quest_loops_character_id_loop_id_key";

grant delete on table "player"."character_quest_loops" to "service_role";

grant insert on table "player"."character_quest_loops" to "service_role";

grant references on table "player"."character_quest_loops" to "service_role";

grant select on table "player"."character_quest_loops" to "service_role";

grant trigger on table "player"."character_quest_loops" to "service_role";

grant truncate on table "player"."character_quest_loops" to "service_role";

grant update on table "player"."character_quest_loops" to "service_role";


