ALTER TABLE player.characters ADD COLUMN IF NOT EXISTS element_type INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player.characters ADD COLUMN IF NOT EXISTS element_rank INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player.characters ADD COLUMN IF NOT EXISTS element_max BOOLEAN NOT NULL DEFAULT FALSE;
