// Open-sourced by BaoLT

// Builds supabase/seeds/data_tbl_schedule_boss.sql from three sources:
//   1. frontend/s/sv/profile/activity.xml <Node name="Boss"> -> kind='ground' rows (lvl 5-140 world bosses)
//   2. data.data_tbl_npc (local Supabase) where type=10 AND layer=3 AND lv>0 -> kind='flying' rows
//   3. internal/domain/activity.BossDailyConfigs joined to data.data_tbl_npc -> kind='daily_only' rows
//
// Requires a running local Supabase stack (default DSN postgres://postgres:postgres@127.0.0.1:54322/postgres).
// Run: go run ./cmd/seed-schedule-bosses > supabase/seeds/data_tbl_schedule_boss.sql
package main

import (
	"context"
	"encoding/xml"
	"flag"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/jackc/pgx/v5"

	"mcgame-server/internal/domain/activity"
)

type bossXMLEntry struct {
	Name        string `xml:"Name,attr"`
	NID         string `xml:"NID,attr"`
	MID         string `xml:"MID,attr"`
	Line        string `xml:"LINE,attr"`
	Level       string `xml:"Level,attr"`
	Description string `xml:"Description,attr"`
}

type bossNode struct {
	XMLName xml.Name       `xml:"Node"`
	Name    string         `xml:"name,attr"`
	Bosses  []bossXMLEntry `xml:"Boss"`
}

type activityPanel struct {
	XMLName xml.Name   `xml:"Panel"`
	Nodes   []bossNode `xml:"Node"`
}

type scheduleBossRow struct {
	NID          int
	Name         string
	MapID        int
	Level        int
	Kind         string
	Tier         string
	ChannelScope string
	Description  string
	DailyBossID  *int
}

func main() {
	xmlPath := flag.String("xml", "frontend/s/sv/profile/activity.xml", "path to activity.xml")
	dsn := flag.String("dsn", "postgres://postgres:postgres@127.0.0.1:54322/postgres?sslmode=disable", "Postgres DSN for local Supabase")
	flag.Parse()

	ctx := context.Background()

	conn, err := pgx.Connect(ctx, *dsn)
	if err != nil {
		fmt.Fprintf(os.Stderr, "connect: %v\n", err)
		os.Exit(1)
	}
	defer conn.Close(ctx)

	groundRows, err := readGroundRowsFromXML(*xmlPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "xml: %v\n", err)
		os.Exit(1)
	}

	known := make(map[int]struct{}, len(groundRows))
	for _, r := range groundRows {
		known[r.NID] = struct{}{}
	}

	flyingRows, err := readFlyingRowsFromDB(ctx, conn, known)
	if err != nil {
		fmt.Fprintf(os.Stderr, "flying: %v\n", err)
		os.Exit(1)
	}
	for _, r := range flyingRows {
		known[r.NID] = struct{}{}
	}

	dailyRows, err := readDailyOnlyRowsFromDB(ctx, conn, known)
	if err != nil {
		fmt.Fprintf(os.Stderr, "daily: %v\n", err)
		os.Exit(1)
	}

	all := append(append(append([]scheduleBossRow{}, groundRows...), flyingRows...), dailyRows...)
	sort.Slice(all, func(i, j int) bool {
		if all[i].Kind != all[j].Kind {
			return kindOrder(all[i].Kind) < kindOrder(all[j].Kind)
		}
		return all[i].NID < all[j].NID
	})

	fmt.Println("-- Seed for data.data_tbl_schedule_boss")
	fmt.Printf("-- Sources: activity.xml (ground=%d) + data_tbl_npc layer=3 (flying=%d) + boss_config.go (daily_only=%d)\n",
		len(groundRows), len(flyingRows), len(dailyRows))
	fmt.Println("-- Generated by cmd/seed-schedule-bosses")
	fmt.Println("truncate data.data_tbl_schedule_boss restart identity cascade;")
	for _, r := range all {
		emitInsert(r)
	}
}

func kindOrder(k string) int {
	switch k {
	case "ground":
		return 0
	case "flying":
		return 1
	case "daily_only":
		return 2
	}
	return 3
}

func readGroundRowsFromXML(path string) ([]scheduleBossRow, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var panel activityPanel
	if err := xml.Unmarshal(raw, &panel); err != nil {
		return nil, err
	}
	var out []scheduleBossRow
	for _, n := range panel.Nodes {
		if n.Name != "Boss" {
			continue
		}
		for _, b := range n.Bosses {
			nid, _ := strconv.Atoi(strings.TrimSpace(b.NID))
			if nid <= 0 {
				continue
			}
			mid, _ := strconv.Atoi(strings.TrimSpace(b.MID))
			lv, _ := strconv.Atoi(strings.TrimSpace(b.Level))
			tier := "normal"
			scope := "all"
			if !strings.Contains(b.Line, "Các kênh") {
				tier = "mythic"
				scope = "channel:1"
			}
			out = append(out, scheduleBossRow{
				NID:          nid,
				Name:         b.Name,
				MapID:        mid,
				Level:        lv,
				Kind:         "ground",
				Tier:         tier,
				ChannelScope: scope,
				Description:  b.Description,
			})
		}
	}
	return out, nil
}

func readFlyingRowsFromDB(ctx context.Context, conn *pgx.Conn, exclude map[int]struct{}) ([]scheduleBossRow, error) {
	rows, err := conn.Query(ctx, `
		select n.id, coalesce(n.name, ''), n.pos_map_id::int, n.lv::int
		from data.data_tbl_npc n
		where n.type::int = 10
		  and n.layer::int = 3
		  and n.lv::int > 0
		  and n.pos_map_id::int <> 200
		order by n.lv::int, n.id
	`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []scheduleBossRow
	for rows.Next() {
		var nid int
		var name string
		var mapID int
		var lv int
		if err := rows.Scan(&nid, &name, &mapID, &lv); err != nil {
			return nil, err
		}
		if _, dup := exclude[nid]; dup {
			continue
		}
		out = append(out, scheduleBossRow{
			NID:          nid,
			Name:         name,
			MapID:        mapID,
			Level:        lv,
			Kind:         "flying",
			Tier:         "normal",
			ChannelScope: "all",
			Description:  "Auto-classified flying via data_tbl_npc.layer=3",
		})
	}
	return out, rows.Err()
}

func readDailyOnlyRowsFromDB(ctx context.Context, conn *pgx.Conn, exclude map[int]struct{}) ([]scheduleBossRow, error) {
	dailyIDs := make([]int, 0, len(activity.BossDailyConfigs))
	for id := range activity.BossDailyConfigs {
		dailyIDs = append(dailyIDs, id)
	}
	sort.Ints(dailyIDs)

	rows, err := conn.Query(ctx, `
		select id, coalesce(name, '') as name, coalesce(lv::int, 0) as lv
		from data.data_tbl_npc
		where id = any($1)
	`, dailyIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	npcByID := make(map[int]struct {
		Name  string
		Level int
	}, len(dailyIDs))
	for rows.Next() {
		var id int
		var name string
		var lv int
		if err := rows.Scan(&id, &name, &lv); err != nil {
			return nil, err
		}
		npcByID[id] = struct {
			Name  string
			Level int
		}{Name: name, Level: lv}
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}

	out := make([]scheduleBossRow, 0, len(dailyIDs))
	for _, id := range dailyIDs {
		if _, dup := exclude[id]; dup {
			continue
		}
		cfg := activity.BossDailyConfigs[id]
		tier := "normal"
		if cfg != nil && cfg.IsSuper == 1 {
			tier = "mythic"
		}
		info := npcByID[id]
		name := info.Name
		desc := "Daily-only registry row (boss_config.go)"
		if name == "" {
			name = fmt.Sprintf("Daily Boss %d", id)
			desc = "Daily-only registry row: name missing in data_tbl_npc, please backfill"
		}
		dailyID := id
		out = append(out, scheduleBossRow{
			NID:          id,
			Name:         name,
			MapID:        0,
			Level:        info.Level,
			Kind:         "daily_only",
			Tier:         tier,
			ChannelScope: "all",
			Description:  desc,
			DailyBossID:  &dailyID,
		})
	}
	return out, nil
}

func emitInsert(r scheduleBossRow) {
	name := sqlEscape(r.Name)
	desc := sqlEscape(r.Description)
	if r.DailyBossID != nil {
		fmt.Printf(
			"insert into data.data_tbl_schedule_boss (nid, name, map_id, level, kind, tier, channel_scope, description, daily_boss_id) values (%d, '%s', %d, %d, '%s', '%s', '%s', '%s', %d);\n",
			r.NID, name, r.MapID, r.Level, r.Kind, r.Tier, r.ChannelScope, desc, *r.DailyBossID,
		)
		return
	}
	fmt.Printf(
		"insert into data.data_tbl_schedule_boss (nid, name, map_id, level, kind, tier, channel_scope, description) values (%d, '%s', %d, %d, '%s', '%s', '%s', '%s');\n",
		r.NID, name, r.MapID, r.Level, r.Kind, r.Tier, r.ChannelScope, desc,
	)
}

func sqlEscape(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}
